#ifndef _ftkoopa_h_
#define _ftkoopa_h_

#include "ft/fighter.h"

#include <baselib/gobj.h>

typedef struct _ftKoopaAttributes {
    f32 x0;
    u32 x4;
    f32 x8;
    f32 xC;
    f32 x10;
    f32 x14;
    f32 x18;
    f32 x1C;
    u32 x20;
    f32 x24;
    f32 x28;
    u32 x2C;
    f32 x30;
    f32 x34;
    f32 x38;
    f32 x3C;
    f32 x40;
    f32 x44;
    f32 x48;
    f32 x4C;
    u32 unk50;
    f32 x54;
    f32 x58;
    f32 x5C;
    f32 x60;
    f32 x64;
    f32 x68;
    f32 x6C;
    f32 x70;
    f32 x74;
    f32 x78;
    f32 x7C;
    f32 x80;
    f32 x84;
    f32 x88;
    f32 x8C;
    f32 x90;
    f32 x94;
    f32 x98;
    f32 x9C;
} ftKoopaAttributes;

typedef struct _ftKoopaVars {
    f32 x0;
    f32 x4;
} ftKoopaVars;

extern MotionState ftKp_Init_MotionStateTable[];
extern char ftKp_Init_DatFilename[];
extern char ftKp_Init_DataName[];
extern Fighter_CostumeStrings ftKp_Init_CostumeStrings[];
extern char ftKp_Init_AnimDatFilename[];
extern Fighter_DemoStrings ftKp_Init_DemoMotionFilenames;

void ftKp_SpecialS_Enter(HSD_GObj* gobj);
void ftKp_SpecialS_8013302C(HSD_GObj* gobj);
void ftKp_SpecialS_801330E4(HSD_GObj* gobj);
void ftKp_Init_UnkMotionStates3(HSD_GObj* gobj);
void ftKp_Init_OnLoadForGKoopa(Fighter* fp);
void ftKp_Init_LoadSpecialAttrs(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132DC0(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132DD0(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132DE0(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132DF0(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132E00(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132E10(HSD_GObj* gobj);
f32 ftKp_SpecialS_80132E20(HSD_GObj* gobj);
void ftKp_Init_OnDeath(HSD_GObj* gobj);
void ftKp_SpecialS_80132E30(HSD_GObj* gobj);
void ftKp_SpecialAirS_Enter(HSD_GObj* gobj);
void ftKp_SpecialS_8013319C(HSD_GObj* gobj);
void ftKp_SpecialS_8013322C(HSD_GObj* gobj);
void ftKp_SpecialS_801332C4(HSD_GObj* gobj);
void ftKp_SpecialS_80133324(HSD_GObj* gobj);
void ftKp_SpecialS_80133398(HSD_GObj* gobj);
void ftKp_SpecialS_801333F8(HSD_GObj* gobj);
void ftKp_SpecialS_80133484(HSD_GObj* gobj);
void ftKp_SpecialS_801334E4(HSD_GObj* gobj);
void ftKp_SpecialS_8013359C(HSD_GObj* gobj);
void ftKp_SpecialS_Anim(HSD_GObj* gobj);
void ftKp_SpecialAirS_Anim(HSD_GObj* gobj);
void ftKp_SpecialSCatch_Anim(HSD_GObj* gobj);
void ftKp_Init_OnLoad(HSD_GObj* gobj);
void ftKp_Init_80132B38(void);
void ftKp_Init_OnItemPickup(HSD_GObj* gobj, bool bool);
void ftKp_Init_OnItemInvisible(HSD_GObj* gobj);
void ftKp_Init_OnItemVisible(HSD_GObj* gobj);
void ftKp_Init_OnItemDrop(HSD_GObj* gobj, bool bool1);
void ftKp_Init_OnKnockbackEnter(HSD_GObj* gobj);
void ftKp_Init_OnKnockbackExit(HSD_GObj* gobj);
void ftKp_SpecialNStart_Anim(HSD_GObj*);
void ftKp_SpecialNStart_IASA(HSD_GObj*);
void ftKp_SpecialNStart_Phys(HSD_GObj*);
void ftKp_SpecialNStart_Coll(HSD_GObj*);
void ftKp_SpecialNLoop_Anim(HSD_GObj*);
void ftKp_SpecialNLoop_IASA(HSD_GObj*);
void ftKp_SpecialNLoop_Phys(HSD_GObj*);
void ftKp_SpecialNLoop_Coll(HSD_GObj*);
void ftKp_SpecialNEnd_Anim(HSD_GObj*);
void ftKp_SpecialNEnd_IASA(HSD_GObj*);
void ftKp_SpecialNEnd_Phys(HSD_GObj*);
void ftKp_SpecialNEnd_Coll(HSD_GObj*);
void ftKp_SpecialAirNStart_Anim(HSD_GObj*);
void ftKp_SpecialAirNStart_IASA(HSD_GObj*);
void ftKp_SpecialAirNStart_Phys(HSD_GObj*);
void ftKp_SpecialAirNStart_Coll(HSD_GObj*);
void ftKp_SpecialAirNLoop_Anim(HSD_GObj*);
void ftKp_SpecialAirNLoop_IASA(HSD_GObj*);
void ftKp_SpecialAirNLoop_Phys(HSD_GObj*);
void ftKp_SpecialAirNLoop_Coll(HSD_GObj*);
void ftKp_SpecialAirNEnd_Anim(HSD_GObj*);
void ftKp_SpecialAirNEnd_IASA(HSD_GObj*);
void ftKp_SpecialAirNEnd_Phys(HSD_GObj*);
void ftKp_SpecialAirNEnd_Coll(HSD_GObj*);
void ftKp_SpecialS_Anim(HSD_GObj*);
void ftKp_SpecialS_Phys(HSD_GObj*);
void ftKp_SpecialS_Coll(HSD_GObj*);
void ftKp_SpecialSCatch_Anim(HSD_GObj*);
void ftKp_SpecialSCatch_IASA(HSD_GObj*);
void ftKp_SpecialSCatch_Phys(HSD_GObj*);
void ftKp_SpecialSCatch_Coll(HSD_GObj*);
void ftKp_SpecialSCatch_Anim(HSD_GObj*);
void ftKp_SpecialSCatch_IASA(HSD_GObj*);
void ftKp_SpecialSCatch_Phys(HSD_GObj*);
void ftKp_SpecialSCatch_Coll(HSD_GObj*);
void ftKp_SpecialSWait_Anim(HSD_GObj*);
void ftKp_SpecialSWait_IASA(HSD_GObj*);
void ftKp_SpecialSWait_Phys(HSD_GObj*);
void ftKp_SpecialSWait_Coll(HSD_GObj*);
void ftKp_SpecialSThrowF_Anim(HSD_GObj*);
void ftKp_SpecialSThrowF_Phys(HSD_GObj*);
void ftKp_SpecialSThrowF_Coll(HSD_GObj*);
void ftKp_SpecialSThrowB_Anim(HSD_GObj*);
void ftKp_SpecialSThrowB_Phys(HSD_GObj*);
void ftKp_SpecialSThrowB_Coll(HSD_GObj*);
void ftKp_SpecialAirS_Anim(HSD_GObj*);
void ftKp_SpecialAirS_Phys(HSD_GObj*);
void ftKp_SpecialAirS_Coll(HSD_GObj*);
void ftKp_SpecialAirSCatch_Anim(HSD_GObj*);
void ftKp_SpecialAirSCatch_IASA(HSD_GObj*);
void ftKp_SpecialAirSCatch_Phys(HSD_GObj*);
void ftKp_SpecialAirSCatch_Coll(HSD_GObj*);
void ftKp_SpecialAirSCatch_Anim(HSD_GObj*);
void ftKp_SpecialAirSCatch_IASA(HSD_GObj*);
void ftKp_SpecialAirSCatch_Phys(HSD_GObj*);
void ftKp_SpecialAirSCatch_Coll(HSD_GObj*);
void ftKp_SpecialAirSWait_Anim(HSD_GObj*);
void ftKp_SpecialAirSWait_IASA(HSD_GObj*);
void ftKp_SpecialAirSWait_Phys(HSD_GObj*);
void ftKp_SpecialAirSWait_Coll(HSD_GObj*);
void ftKp_SpecialAirSThrowF_Anim(HSD_GObj*);
void ftKp_SpecialAirSThrowF_Phys(HSD_GObj*);
void ftKp_SpecialAirSThrowF_Coll(HSD_GObj*);
void ftKp_SpecialAirSThrowB_Anim(HSD_GObj*);
void ftKp_SpecialAirSThrowB_Phys(HSD_GObj*);
void ftKp_SpecialAirSThrowB_Coll(HSD_GObj*);
void ftKp_SpecialHi_Anim(HSD_GObj*);
void ftKp_SpecialHi_IASA(HSD_GObj*);
void ftKp_SpecialHi_Phys(HSD_GObj*);
void ftKp_SpecialHi_Coll(HSD_GObj*);
void ftKp_SpecialAirHi_Anim(HSD_GObj*);
void ftKp_SpecialAirHi_IASA(HSD_GObj*);
void ftKp_SpecialAirHi_Phys(HSD_GObj*);
void ftKp_SpecialAirHi_Coll(HSD_GObj*);
void ftKp_SpecialLwStart_Anim(HSD_GObj*);
void ftKp_SpecialLwStart_Phys(HSD_GObj*);
void ftKp_SpecialLwStart_Coll(HSD_GObj*);
void ftKp_SpecialAirLw_Anim(HSD_GObj*);
void ftKp_SpecialAirLw_Phys(HSD_GObj*);
void ftKp_SpecialAirLw_Coll(HSD_GObj*);
void ftKp_SpecialLwLanding_Anim(HSD_GObj*);
void ftKp_SpecialLwLanding_Phys(HSD_GObj*);
void ftKp_SpecialLwLanding_Coll(HSD_GObj*);
void ftKp_SpecialAirHi_Enter(HSD_GObj*);
void ftKp_SpecialAirLw_Enter(HSD_GObj*);
void ftKp_SpecialAirN_Enter(HSD_GObj*);
void ftKp_SpecialN_Enter(HSD_GObj*);
void ftKp_SpecialLw_Enter(HSD_GObj*);
void ftKp_SpecialHi_Enter(HSD_GObj*);

#endif
