#ifndef MELEE_FT_CHARA_FTCAPTAIN_FORWARD_H
#define MELEE_FT_CHARA_FTCAPTAIN_FORWARD_H

#include "ft/forward.h"

typedef enum ftCaptainAction {
    AS_CAPTAIN_SWING42_SWORD = ASID_MAX,
    AS_CAPTAIN_SWING42_2,
    AS_CAPTAIN_SWING42_3,
    AS_CAPTAIN_SWING42_4,
    AS_CAPTAIN_SWING42_5,
    AS_CAPTAIN_SWING42_6,
    AS_CAPTAIN_SPECIALN,
    AS_CAPTAIN_SPECIALAIRN,
    AS_CAPTAIN_SPECIALS_START,
    AS_CAPTAIN_SPECIALS,
    AS_CAPTAIN_SPECIALAIRS_START,
    AS_CAPTAIN_SPECIALAIRS,
    AS_CAPTAIN_SPECIALHI,
    AS_CAPTAIN_SPECIALAIRHI,
    AS_CAPTAIN_SPECIALHI_CATCH,
    AS_CAPTAIN_SPECIALHI_THROW,
} ftCaptainAction;

#endif
