name: Deploy to GitHub Pages

on:
  push:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout extern assets
        uses: actions/checkout@v4
        with:
          repository: doldecomp/assets
          path: assets
          fetch-depth: 1
          sparse-checkout: melee/progress

      - name: Acquire assets
        run: |
          src='assets/melee/progress'
          static='static/extern'
          lib='src/lib/extern'

          # fonts
          fonts_url='https://media.fontsgeek.com/download/zip/a/-/a-otf-folk-pro_WeXVg.zip'
          fonts_zip=$(mktemp)
          curl -L "$fonts_url" -o $fonts_zip
          unzip $fonts_zip -d fonts
          mv 'fonts/A-OTF Folk Pro M/A-OTF Folk Pro M.otf' "$lib"

          # git assets
          mv "$src/background.gif" "$lib"
          mv "$src/favicon.png" "$static"

          # progress
          progress_url='https://progress.decomp.club/data/melee/GALE01?format=json&mode=all'
          curl -s -L "$progress_url" -o "$lib/progress.json"
          
          # cleanup
          find . -type f -name '.gitkeep' -delete

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build-site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
