#ifndef MELEE_FT_CHARA_FTLUIGI_FORWARD_H
#define MELEE_FT_CHARA_FTLUIGI_FORWARD_H

#include "ftCommon/forward.h"

typedef enum ftLuigiAction {
    MS_LUIGI_SPECIALN = ftCo_MS_Count,
    MS_LUIGI_SPECIALAIRN,
    MS_LUIGI_SPECIALS_START,
    MS_LUIGI_SPECIALS_HOLD,
    MS_LUIGI_SPECIALS_FLY,
    MS_LUIGI_SPECIALS_END,
    MS_LUIGI_SPECIALS_LAUNCH,
    MS_LUIGI_SPECIALS_MISFIRE,
    MS_LUIGI_SPECIALAIRS_START,
    MS_LUIGI_SPECIALAIRS_HOLD,
    MS_LUIGI_SPECIALAIRS_FLY,
    MS_LUIGI_SPECIALAIRS_END,
    MS_LUIGI_SPECIALAIRS_LAUNCH,
    MS_LUIGI_SPECIALAIRS_MISFIRE,
    MS_LUIGI_SPECIALHI,
    MS_LUIGI_SPECIALAIRHI,
    MS_LUIGI_SPECIALLW,
    MS_LUIGI_SPECIALAIRLW,
} ftLuigiAction;
#endif
