#ifndef MELEE_FT_CHARA_FTNESS_FORWARD_H
#define MELEE_FT_CHARA_FTNESS_FORWARD_H

#include "ftCommon/forward.h"

typedef enum ftNessAction {
    MS_NESS_ATTACKS4 = ftCo_MS_Count,
    MS_NESS_ATTACKHI4,
    MS_NESS_ATTACKHI4_CHARGE,
    MS_NESS_ATTACKHI4_RELEASE,
    MS_NESS_ATTACKLW4,
    MS_NESS_ATTACKLW4_CHARGE,
    MS_NESS_ATTACKLW4_RELEASE,
    MS_NESS_SPECIALN_START,
    MS_NESS_SPECIALN_HOLD,
    MS_NESS_SPECIALN_HOLD_RELEASE,
    MS_NESS_SPECIALN_END,
    MS_NESS_SPECIALAIRN_START,
    MS_NESS_SPECIALAIRN_HOLD,
    MS_NESS_SPECIALAIRN_HOLD_RELEASE,
    MS_NESS_SPECIALAIRN_END,
    MS_NESS_SPECIALS,
    MS_NESS_SPECIALAIRS,
    MS_NESS_SPECIALHI_START,
    MS_NESS_SPECIALHI_HOLD,
    MS_NESS_SPECIALHI_END,
    MS_NESS_SPECIALHI,
    MS_NESS_SPECIALAIRHI_START,
    MS_NESS_SPECIALAIRHI_HOLD,
    MS_NESS_SPECIALAIRHI_END,
    MS_NESS_SPECIALAIRHI,
    MS_NESS_SPECIALAIRHI_HITWALL,
    MS_NESS_SPECIALLW_START,
    MS_NESS_SPECIALLW_HOLD,
    MS_NESS_SPECIALLW_HIT,
    MS_NESS_SPECIALLW_END,
    MS_NESS_SPECIALLW_TURN,
    MS_NESS_SPECIALAIRLW_START,
    MS_NESS_SPECIALAIRLW_HOLD,
    MS_NESS_SPECIALAIRLW_HIT,
    MS_NESS_SPECIALAIRLW_END,
    MS_NESS_SPECIALAIRLW_TURN,
} ftNessAction;

#endif
