# Files with unscheduled epilogues.

EPILOGUE_UNSCHEDULED:=\
	$(EPILOGUE_DIR)/src/melee/lb/lblanguage.o\
	$(EPILOGUE_DIR)/src/melee/lb/lbcommand.o\
	$(EPILOGUE_DIR)/src/melee/lb/lbvector.o\
	$(EPILOGUE_DIR)/src/melee/lb/lbtime.o\
	$(EPILOGUE_DIR)/src/melee/lb/lbfile.o\
	$(EPILOGUE_DIR)/src/melee/lb/lbarchive.o\
	$(EPILOGUE_DIR)/src/melee/ft/ftcliffcommon.o 		\
	$(EPILOGUE_DIR)/src/melee/ft/ftwalljump.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftdrmario.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftdrmario_2.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftemblem.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftfalco.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftfox.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftganon.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftgigakoopa.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftkoopa.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftmario.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftness.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftpeach.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftpichu.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftsandbag.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftzakoboy.o\
	$(EPILOGUE_DIR)/src/melee/ft/chara/ftzakogirl.o\
	$(EPILOGUE_DIR)/src/melee/gr/stage.o\
	$(EPILOGUE_DIR)/src/melee/pl/player.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/tobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/aobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/fobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/robj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/wobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/texp.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/list.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/archive.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/displayfunc.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/controller.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/dobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/shadow.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/class.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/pobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/id.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/lobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/gobjgxlink.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/gobjuserdata.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/random.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/cobj.o\
	$(EPILOGUE_DIR)/src/sysdolphin/baselib/mobj.o\
