cmake_minimum_required(VERSION 3.20)

project(melee-native LANGUAGES C)

include(GNUInstallDirs)

set(SOURCES
    src/hsd/aobj.c
    src/hsd/archive.c
    src/hsd/axdriver.c
    src/hsd/bytecode.c
    src/hsd/class.c
    src/hsd/cobj.c
    src/hsd/controller.c
    src/hsd/devcom.c
    src/hsd/dobj.c
    src/hsd/fobj.c
    src/hsd/gobj.c
    src/hsd/gobjgxlink.c
    src/hsd/gobjobject.c
    src/hsd/gobjplink.c
    src/hsd/gobjproc.c
    src/hsd/gobjuserdata.c
    src/hsd/hash.c
    src/hsd/id.c
    src/hsd/initialize.c
    src/hsd/jobj.c
    src/hsd/leak.c
    src/hsd/list.c
    src/hsd/lobj.c
    src/hsd/mobj.c
    src/hsd/mtx.c
    src/hsd/objalloc.c
    src/hsd/object.c
    src/hsd/perf.c
    src/hsd/psappsrt.c
    src/hsd/psdisptev.c
    src/hsd/quatlib.c
    src/hsd/random.c
    src/hsd/robj.c
    src/hsd/rumble.c
    src/hsd/shadow.c
    src/hsd/state.c
    src/hsd/tev.c
    src/hsd/texp.c
    src/hsd/texpdag.c
    src/hsd/tobj.c
    src/hsd/util.c
    src/hsd/wobj.c
    src/melee/cm/camera.c
    src/melee/cm/cmsnap.c
    src/melee/db/dballoc.c
    src/melee/db/dbanim.c
    src/melee/db/dbbonus.c
    src/melee/db/dbcamera.c
    src/melee/db/dbcpu.c
    src/melee/db/dbeffect.c
    src/melee/db/dbinit.c
    src/melee/db/dbitem.c
    src/melee/db/dbscreenshot.c
    src/melee/db/dbsound.c
    src/melee/ef/efasync.c
    src/melee/ef/efdata.c
    src/melee/ef/eflib.c
    src/melee/ef/efsync.c
    src/melee/ft/chara/ftCaptain/ftCa_Init.c
    src/melee/ft/chara/ftCaptain/ftCa_SpecialHi.c
    src/melee/ft/chara/ftCaptain/ftCa_SpecialLw.c
    src/melee/ft/chara/ftCaptain/ftCa_SpecialN.c
    src/melee/ft/chara/ftCaptain/ftCa_SpecialS.c
    src/melee/ft/chara/ftCLink/ftCl_AppealS.c
    src/melee/ft/chara/ftCLink/ftCl_Init.c
    src/melee/ft/chara/ftCommon/ftCo_09C4.c
    src/melee/ft/chara/ftCommon/ftCo_09F4.c
    src/melee/ft/chara/ftCommon/ftCo_09F7.c
    src/melee/ft/chara/ftCommon/ftCo_0A01.c
    src/melee/ft/chara/ftCommon/ftCo_0C35.c
    src/melee/ft/chara/ftCommon/ftCo_0C60.c
    src/melee/ft/chara/ftCommon/ftCo_0D67.c
    src/melee/ft/chara/ftCommon/ftCo_0D72.c
    src/melee/ft/chara/ftCommon/ftCo_0D8E.c
    src/melee/ft/chara/ftCommon/ftCo_0D95.c
    src/melee/ft/chara/ftCommon/ftCo_0DC2.c
    src/melee/ft/chara/ftCommon/ftCo_AirCatch.c
    src/melee/ft/chara/ftCommon/ftCo_AppealS.c
    src/melee/ft/chara/ftCommon/ftCo_Attack100.c
    src/melee/ft/chara/ftCommon/ftCo_Attack1.c
    src/melee/ft/chara/ftCommon/ftCo_AttackAir.c
    src/melee/ft/chara/ftCommon/ftCo_AttackDash.c
    src/melee/ft/chara/ftCommon/ftCo_AttackHi3.c
    src/melee/ft/chara/ftCommon/ftCo_AttackHi4.c
    src/melee/ft/chara/ftCommon/ftCo_AttackLw3.c
    src/melee/ft/chara/ftCommon/ftCo_AttackLw4.c
    src/melee/ft/chara/ftCommon/ftCo_AttackS3.c
    src/melee/ft/chara/ftCommon/ftCo_AttackS4.c
    src/melee/ft/chara/ftCommon/ftCo_Barrel.c
    src/melee/ft/chara/ftCommon/ftCo_BarrelWait.c
    src/melee/ft/chara/ftCommon/ftCo_Bury.c
    src/melee/ft/chara/ftCommon/ftCo_BuryWait.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureCaptain.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureCut.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureDamageKoopa.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureJump.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureKirby.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureKoopa.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureMewtwo.c
    src/melee/ft/chara/ftCommon/ftCo_CapturePulled.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureWait.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureWaitKirby.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureWaitKoopa.c
    src/melee/ft/chara/ftCommon/ftCo_CaptureYoshi.c
    src/melee/ft/chara/ftCommon/ftCo_CargoFall.c
    src/melee/ft/chara/ftCommon/ftCo_CargoJump.c
    src/melee/ft/chara/ftCommon/ftCo_CargoKneebend.c
    src/melee/ft/chara/ftCommon/ftCo_CargoLanding.c
    src/melee/ft/chara/ftCommon/ftCo_CargoThrow.c
    src/melee/ft/chara/ftCommon/ftCo_CargoTurn.c
    src/melee/ft/chara/ftCommon/ftCo_CargoWait.c
    src/melee/ft/chara/ftCommon/ftCo_CargoWalk.c
    src/melee/ft/chara/ftCommon/ftCo_CatchAttack.c
    src/melee/ft/chara/ftCommon/ftCo_Catch.c
    src/melee/ft/chara/ftCommon/ftCo_CatchCut.c
    src/melee/ft/chara/ftCommon/ftCo_CatchPull.c
    src/melee/ft/chara/ftCommon/ftCo_CatchWait.c
    src/melee/ft/chara/ftCommon/ftCo_CliffAttack.c
    src/melee/ft/chara/ftCommon/ftCo_CliffClimb.c
    src/melee/ft/chara/ftCommon/ftCo_CliffEscape.c
    src/melee/ft/chara/ftCommon/ftCo_CliffJump.c
    src/melee/ft/chara/ftCommon/ftCo_CliffWait.c
    src/melee/ft/chara/ftCommon/ftCo_DamageBind.c
    src/melee/ft/chara/ftCommon/ftCo_Damage.c
    src/melee/ft/chara/ftCommon/ftCo_DamageFall.c
    src/melee/ft/chara/ftCommon/ftCo_DamageIce.c
    src/melee/ft/chara/ftCommon/ftCo_DamageScrew.c
    src/melee/ft/chara/ftCommon/ftCo_DamageSong.c
    src/melee/ft/chara/ftCommon/ftCo_Dash.c
    src/melee/ft/chara/ftCommon/ftCo_DemoCallback0.c
    src/melee/ft/chara/ftCommon/ftCo_DownAttack.c
    src/melee/ft/chara/ftCommon/ftCo_DownBound.c
    src/melee/ft/chara/ftCommon/ftCo_Down.c
    src/melee/ft/chara/ftCommon/ftCo_DownDamage.c
    src/melee/ft/chara/ftCommon/ftCo_DownSpot.c
    src/melee/ft/chara/ftCommon/ftCo_DownStand.c
    src/melee/ft/chara/ftCommon/ftCo_EscapeAir.c
    src/melee/ft/chara/ftCommon/ftCo_Escape.c
    src/melee/ft/chara/ftCommon/ftCo_FallAerial.c
    src/melee/ft/chara/ftCommon/ftCo_Fall.c
    src/melee/ft/chara/ftCommon/ftCo_FallSpecial.c
    src/melee/ft/chara/ftCommon/ftCo_FlyReflect.c
    src/melee/ft/chara/ftCommon/ftCo_Furafura.c
    src/melee/ft/chara/ftCommon/ftCo_Guard.c
    src/melee/ft/chara/ftCommon/ftCo_HammerFall.c
    src/melee/ft/chara/ftCommon/ftCo_HammerJump.c
    src/melee/ft/chara/ftCommon/ftCo_HammerKneeBend.c
    src/melee/ft/chara/ftCommon/ftCo_HammerLanding.c
    src/melee/ft/chara/ftCommon/ftCo_HammerTurn.c
    src/melee/ft/chara/ftCommon/ftCo_HammerWait.c
    src/melee/ft/chara/ftCommon/ftCo_HammerWalk.c
    src/melee/ft/chara/ftCommon/ftCo_ItemParasolDamageFall.c
    src/melee/ft/chara/ftCommon/ftCo_ItemParasolFall.c
    src/melee/ft/chara/ftCommon/ftCo_ItemParasolFallSpecial.c
    src/melee/ft/chara/ftCommon/ftCo_ItemParasolOpen.c
    src/melee/ft/chara/ftCommon/ftCo_ItemScope.c
    src/melee/ft/chara/ftCommon/ftCo_ItemScopeFire.c
    src/melee/ft/chara/ftCommon/ftCo_ItemScopeRapid.c
    src/melee/ft/chara/ftCommon/ftCo_ItemScopeStart.c
    src/melee/ft/chara/ftCommon/ftCo_ItemScrew.c
    src/melee/ft/chara/ftCommon/ftCo_ItemThrow.c
    src/melee/ft/chara/ftCommon/ftCo_JumpAerial.c
    src/melee/ft/chara/ftCommon/ftCo_JumpAerialF1.c
    src/melee/ft/chara/ftCommon/ftCo_Jump.c
    src/melee/ft/chara/ftCommon/ftCo_KinokoGiantEnd.c
    src/melee/ft/chara/ftCommon/ftCo_KinokoGiantStart.c
    src/melee/ft/chara/ftCommon/ftCo_KinokoSmallEnd.c
    src/melee/ft/chara/ftCommon/ftCo_KinokoSmallStart.c
    src/melee/ft/chara/ftCommon/ftCo_KneeBend.c
    src/melee/ft/chara/ftCommon/ftCo_LandingAir.c
    src/melee/ft/chara/ftCommon/ftCo_Landing.c
    src/melee/ft/chara/ftCommon/ftCo_Lift.c
    src/melee/ft/chara/ftCommon/ftCo_MissFoot.c
    src/melee/ft/chara/ftCommon/ftCo_Ottotto.c
    src/melee/ft/chara/ftCommon/ftCo_Pass.c
    src/melee/ft/chara/ftCommon/ftCo_Passive.c
    src/melee/ft/chara/ftCommon/ftCo_PassiveCeil.c
    src/melee/ft/chara/ftCommon/ftCo_PassiveStand.c
    src/melee/ft/chara/ftCommon/ftCo_PassiveWall.c
    src/melee/ft/chara/ftCommon/ftCo_Rebound.c
    src/melee/ft/chara/ftCommon/ftCo_RunBrake.c
    src/melee/ft/chara/ftCommon/ftCo_Run.c
    src/melee/ft/chara/ftCommon/ftCo_RunDirect.c
    src/melee/ft/chara/ftCommon/ftCo_ShieldBreakDown.c
    src/melee/ft/chara/ftCommon/ftCo_ShieldBreakFall.c
    src/melee/ft/chara/ftCommon/ftCo_ShieldBreakFly.c
    src/melee/ft/chara/ftCommon/ftCo_ShieldBreakStand.c
    src/melee/ft/chara/ftCommon/ftCo_Shouldered.c
    src/melee/ft/chara/ftCommon/ftCo_SpecialAir.c
    src/melee/ft/chara/ftCommon/ftCo_SpecialS.c
    src/melee/ft/chara/ftCommon/ftCo_Squat.c
    src/melee/ft/chara/ftCommon/ftCo_SquatRv.c
    src/melee/ft/chara/ftCommon/ftCo_SquatWait.c
    src/melee/ft/chara/ftCommon/ftCo_StopCeil.c
    src/melee/ft/chara/ftCommon/ftCo_StopWall.c
    src/melee/ft/chara/ftCommon/ftCo_Throw.c
    src/melee/ft/chara/ftCommon/ftCo_Thrown.c
    src/melee/ft/chara/ftCommon/ftCo_ThrownKirby.c
    src/melee/ft/chara/ftCommon/ftCo_ThrownKoopa.c
    src/melee/ft/chara/ftCommon/ftCo_ThrownMewtwo.c
    src/melee/ft/chara/ftCommon/ftCo_Turn.c
    src/melee/ft/chara/ftCommon/ftCo_TurnRun.c
    src/melee/ft/chara/ftCommon/ftCo_Wait.c
    src/melee/ft/chara/ftCommon/ftCo_Walk.c
    src/melee/ft/chara/ftCommon/ftCo_WarpStar.c
    src/melee/ft/chara/ftCommon/ftCo_YoshiEgg.c
    src/melee/ft/chara/ftCommon/ftpickupitem.c
    src/melee/ft/chara/ftCrazyHand/ftCh_BackAirplane1.c
    src/melee/ft/chara/ftCrazyHand/ftCh_BackAirplane2.c
    src/melee/ft/chara/ftCrazyHand/ftCh_BackAirplane3.c
    src/melee/ft/chara/ftCrazyHand/ftCh_BackCrush.c
    src/melee/ft/chara/ftCrazyHand/ftCh_BackDisappear.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Cancel.c
    src/melee/ft/chara/ftCrazyHand/ftCh_CaptureCrazyHand.c
    src/melee/ft/chara/ftCrazyHand/ftCh_CaptureDamageCrazyHand.c
    src/melee/ft/chara/ftCrazyHand/ftCh_CaptureWaitCrazyHand.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Damage_0.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Drill.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Entry.c
    src/melee/ft/chara/ftCrazyHand/ftCh_FingerBeam_0.c
    src/melee/ft/chara/ftCrazyHand/ftCh_FingerBeam.c
    src/melee/ft/chara/ftCrazyHand/ftCh_FingerGun2.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Grab.c
    src/melee/ft/chara/ftCrazyHand/ftCh_GrabUnk1_B174.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Init.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Poke.c
    src/melee/ft/chara/ftCrazyHand/ftCh_RockCrush_0.c
    src/melee/ft/chara/ftCrazyHand/ftCh_RockCrush_1.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Slam.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Squeeze.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Squeezing_0.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Squeezing_1.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Sweep.c
    src/melee/ft/chara/ftCrazyHand/ftCh_SweepWait.c
    src/melee/ft/chara/ftCrazyHand/ftCh_TagCancel.c
    src/melee/ft/chara/ftCrazyHand/ftCh_TagGrab.c
    src/melee/ft/chara/ftCrazyHand/ftCh_TagRockPaper.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Throw.c
    src/melee/ft/chara/ftCrazyHand/ftCh_ThrownCrazyHand.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Wait1_0.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Wait1_1.c
    src/melee/ft/chara/ftCrazyHand/ftCh_Walk.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyFall.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyJump.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyLanding.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyTurn.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyWait0.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyWait1.c
    src/melee/ft/chara/ftDonkey/ftDk_HeavyWalk.c
    src/melee/ft/chara/ftDonkey/ftDk_Init.c
    src/melee/ft/chara/ftDonkey/ftDk_MS_345_0.c
    src/melee/ft/chara/ftDonkey/ftDk_SpecialHi.c
    src/melee/ft/chara/ftDonkey/ftDk_SpecialLw.c
    src/melee/ft/chara/ftDonkey/ftDk_SpecialN.c
    src/melee/ft/chara/ftDonkey/ftDk_SpecialS.c
    src/melee/ft/chara/ftDrMario/ftDr_AppealS.c
    src/melee/ft/chara/ftDrMario/ftDr_Init.c
    src/melee/ft/chara/ftEmblem/ftFe_Init.c
    src/melee/ft/chara/ftFalco/ftFc_Init.c
    src/melee/ft/chara/ftFox/ftFx_AppealS.c
    src/melee/ft/chara/ftFox/ftFx_Init.c
    src/melee/ft/chara/ftFox/ftFx_SpecialHi.c
    src/melee/ft/chara/ftFox/ftFx_SpecialLw.c
    src/melee/ft/chara/ftFox/ftFx_SpecialN.c
    src/melee/ft/chara/ftFox/ftFx_SpecialS.c
    src/melee/ft/chara/ftGameWatch/ftGw_Attack100.c
    src/melee/ft/chara/ftGameWatch/ftGw_Attack11.c
    src/melee/ft/chara/ftGameWatch/ftGw_AttackAir.c
    src/melee/ft/chara/ftGameWatch/ftGw_AttackLw3.c
    src/melee/ft/chara/ftGameWatch/ftGw_AttackS4.c
    src/melee/ft/chara/ftGameWatch/ftGw_Init.c
    src/melee/ft/chara/ftGameWatch/ftGw_SpecialHi.c
    src/melee/ft/chara/ftGameWatch/ftGw_SpecialLw.c
    src/melee/ft/chara/ftGameWatch/ftGw_SpecialN.c
    src/melee/ft/chara/ftGameWatch/ftGw_SpecialS.c
    src/melee/ft/chara/ftGanon/ftGn_Init.c
    src/melee/ft/chara/ftGigaKoopa/ftGk_Init.c
    src/melee/ft/chara/ftKirby/ftkirbyattackdash.c
    src/melee/ft/chara/ftKirby/ftkirby.c
    src/melee/ft/chara/ftKirby/ftkirbycaptureyoshi.c
    src/melee/ft/chara/ftKirby/ftkirbydata.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialcaptain.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialdonkey.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialfox.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialgamewatch.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialhi.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialiceclimber.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialkoopa.c
    src/melee/ft/chara/ftKirby/ftkirbyspeciallink.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialluigi.c
    src/melee/ft/chara/ftKirby/ftkirbyspeciallw.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialmario.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialmars.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialmewtwo.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialn.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialness.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialpeach.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialpikachu.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialpurin.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialsamus.c
    src/melee/ft/chara/ftKirby/ftkirbyspecials.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialseak.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialyoshi.c
    src/melee/ft/chara/ftKirby/ftkirbyspecialzelda.c
    src/melee/ft/chara/ftKirby/ftkirbyyoshiegg.c
    src/melee/ft/chara/ftKoopa/ftKp_Init.c
    src/melee/ft/chara/ftKoopa/ftKp_SpecialHi.c
    src/melee/ft/chara/ftKoopa/ftKp_SpecialLw.c
    src/melee/ft/chara/ftKoopa/ftKp_SpecialN.c
    src/melee/ft/chara/ftKoopa/ftKp_SpecialS.c
    src/melee/ft/chara/ftLink/ftLk_AttackAir.c
    src/melee/ft/chara/ftLink/ftLk_Init.c
    src/melee/ft/chara/ftLink/ftLk_SpecialHi.c
    src/melee/ft/chara/ftLink/ftLk_SpecialLw.c
    src/melee/ft/chara/ftLink/ftLk_SpecialN.c
    src/melee/ft/chara/ftLink/ftLk_SpecialS.c
    src/melee/ft/chara/ftLuigi/ftLg_Init.c
    src/melee/ft/chara/ftLuigi/ftLg_SpecialHi.c
    src/melee/ft/chara/ftLuigi/ftLg_SpecialLw.c
    src/melee/ft/chara/ftLuigi/ftLg_SpecialN.c
    src/melee/ft/chara/ftLuigi/ftLg_SpecialS.c
    src/melee/ft/chara/ftMario/ftMr_Init.c
    src/melee/ft/chara/ftMario/ftMr_SpecialHi.c
    src/melee/ft/chara/ftMario/ftMr_SpecialLw.c
    src/melee/ft/chara/ftMario/ftMr_SpecialN.c
    src/melee/ft/chara/ftMario/ftMr_SpecialS.c
    src/melee/ft/chara/ftMario/ftMr_Strings.c
    src/melee/ft/chara/ftMars/ftMs_Init.c
    src/melee/ft/chara/ftMars/ftMs_SpecialHi.c
    src/melee/ft/chara/ftMars/ftMs_SpecialLw.c
    src/melee/ft/chara/ftMars/ftMs_SpecialN.c
    src/melee/ft/chara/ftMars/ftMs_SpecialS.c
    src/melee/ft/chara/ftMasterHand/ftMh_BackAirplane1.c
    src/melee/ft/chara/ftMasterHand/ftMh_BackAirplane2.c
    src/melee/ft/chara/ftMasterHand/ftMh_BackAirplane3.c
    src/melee/ft/chara/ftMasterHand/ftMh_BackCrush_0.c
    src/melee/ft/chara/ftMasterHand/ftMh_BackCrush_1.c
    src/melee/ft/chara/ftMasterHand/ftMh_BackDisappear.c
    src/melee/ft/chara/ftMasterHand/ftMh_CaptureDamageMasterHand.c
    src/melee/ft/chara/ftMasterHand/ftMh_CaptureMasterHand.c
    src/melee/ft/chara/ftMasterHand/ftMh_Damage_0.c
    src/melee/ft/chara/ftMasterHand/ftMh_Drill.c
    src/melee/ft/chara/ftMasterHand/ftMh_Entry.c
    src/melee/ft/chara/ftMasterHand/ftMh_FingerBeam.c
    src/melee/ft/chara/ftMasterHand/ftMh_FingerGun3.c
    src/melee/ft/chara/ftMasterHand/ftMh_FingerGun.c
    src/melee/ft/chara/ftMasterHand/ftMh_Init.c
    src/melee/ft/chara/ftMasterHand/ftMh_PaperCrush.c
    src/melee/ft/chara/ftMasterHand/ftMh_Poke.c
    src/melee/ft/chara/ftMasterHand/ftMh_RockCrush.c
    src/melee/ft/chara/ftMasterHand/ftMh_Slam.c
    src/melee/ft/chara/ftMasterHand/ftMh_Slap.c
    src/melee/ft/chara/ftMasterHand/ftMh_Squeeze.c
    src/melee/ft/chara/ftMasterHand/ftMh_Squeezing.c
    src/melee/ft/chara/ftMasterHand/ftMh_Sweep.c
    src/melee/ft/chara/ftMasterHand/ftMh_SweepWait.c
    src/melee/ft/chara/ftMasterHand/ftMh_TagApplaud.c
    src/melee/ft/chara/ftMasterHand/ftMh_TagCancel.c
    src/melee/ft/chara/ftMasterHand/ftMh_TagCrush.c
    src/melee/ft/chara/ftMasterHand/ftMh_TagRockPaper.c
    src/melee/ft/chara/ftMasterHand/ftMh_Throw.c
    src/melee/ft/chara/ftMasterHand/ftMh_ThrownMasterHand.c
    src/melee/ft/chara/ftMasterHand/ftMh_Wait1_0.c
    src/melee/ft/chara/ftMasterHand/ftMh_Wait1_1.c
    src/melee/ft/chara/ftMasterHand/ftMh_Wait1_2.c
    src/melee/ft/chara/ftMasterHand/ftMh_Walk.c
    src/melee/ft/chara/ftMewtwo/ftMt_Init.c
    src/melee/ft/chara/ftMewtwo/ftMt_SpecialHi.c
    src/melee/ft/chara/ftMewtwo/ftMt_SpecialLw.c
    src/melee/ft/chara/ftMewtwo/ftMt_SpecialN.c
    src/melee/ft/chara/ftMewtwo/ftMt_SpecialS.c
    src/melee/ft/chara/ftNana/ftNn_Init.c
    src/melee/ft/chara/ftNana/ftNn_SpecialHi.c
    src/melee/ft/chara/ftNana/ftNn_SpecialS.c
    src/melee/ft/chara/ftNess/ftNs_AttackHi4.c
    src/melee/ft/chara/ftNess/ftNs_AttackLw4.c
    src/melee/ft/chara/ftNess/ftNs_AttackS4.c
    src/melee/ft/chara/ftNess/ftNs_Init.c
    src/melee/ft/chara/ftNess/ftNs_SpecialHi.c
    src/melee/ft/chara/ftNess/ftNs_SpecialLw.c
    src/melee/ft/chara/ftNess/ftNs_SpecialN.c
    src/melee/ft/chara/ftNess/ftNs_SpecialS.c
    src/melee/ft/chara/ftPeach/ftPe_AttackS4.c
    src/melee/ft/chara/ftPeach/ftPe_FloatAttack.c
    src/melee/ft/chara/ftPeach/ftPe_Float.c
    src/melee/ft/chara/ftPeach/ftPe_FloatFall.c
    src/melee/ft/chara/ftPeach/ftPe_Init.c
    src/melee/ft/chara/ftPeach/ftPe_SpecialHi.c
    src/melee/ft/chara/ftPeach/ftPe_SpecialLw.c
    src/melee/ft/chara/ftPeach/ftPe_SpecialN.c
    src/melee/ft/chara/ftPeach/ftPe_SpecialS.c
    src/melee/ft/chara/ftPichu/ftPc_Init.c
    src/melee/ft/chara/ftPikachu/ftPk_Init.c
    src/melee/ft/chara/ftPikachu/ftPk_SpecialHi.c
    src/melee/ft/chara/ftPikachu/ftPk_SpecialLw.c
    src/melee/ft/chara/ftPikachu/ftPk_SpecialN.c
    src/melee/ft/chara/ftPikachu/ftPk_SpecialS.c
    src/melee/ft/chara/ftPopo/ftPp_Init.c
    src/melee/ft/chara/ftPopo/ftPp_SpecialHi.c
    src/melee/ft/chara/ftPopo/ftPp_SpecialLw.c
    src/melee/ft/chara/ftPopo/ftPp_SpecialN.c
    src/melee/ft/chara/ftPopo/ftPp_SpecialS.c
    src/melee/ft/chara/ftPurin/ftPr_Init.c
    src/melee/ft/chara/ftPurin/ftPr_SpecialHi.c
    src/melee/ft/chara/ftPurin/ftPr_SpecialLw.c
    src/melee/ft/chara/ftPurin/ftPr_SpecialN.c
    src/melee/ft/chara/ftPurin/ftPr_SpecialS.c
    src/melee/ft/chara/ftSamus/ftSs_Init.c
    src/melee/ft/chara/ftSamus/ftSs_SpecialHi.c
    src/melee/ft/chara/ftSamus/ftSs_SpecialLw_0.c
    src/melee/ft/chara/ftSamus/ftSs_SpecialLw_1.c
    src/melee/ft/chara/ftSamus/ftSs_SpecialN.c
    src/melee/ft/chara/ftSamus/ftSs_SpecialS.c
    src/melee/ft/chara/ftSandbag/ftSb_Init.c
    src/melee/ft/chara/ftSeak/ftSk_Init.c
    src/melee/ft/chara/ftSeak/ftSk_SpecialHi.c
    src/melee/ft/chara/ftSeak/ftSk_SpecialLw.c
    src/melee/ft/chara/ftSeak/ftSk_SpecialN.c
    src/melee/ft/chara/ftSeak/ftSk_SpecialS.c
    src/melee/ft/chara/ftYoshi/ftYs_Guard.c
    src/melee/ft/chara/ftYoshi/ftyoshi.c
    src/melee/ft/chara/ftYoshi/ftYs_SpecialHi.c
    src/melee/ft/chara/ftYoshi/ftYs_SpecialLw.c
    src/melee/ft/chara/ftYoshi/ftYs_SpecialN.c
    src/melee/ft/chara/ftYoshi/ftYs_SpecialS.c
    src/melee/ft/chara/ftZakoBoy/ftBo_Init.c
    src/melee/ft/chara/ftZakoGirl/ftGl_Init.c
    src/melee/ft/chara/ftZelda/ftZd_Init.c
    src/melee/ft/chara/ftZelda/ftZd_SpecialHi.c
    src/melee/ft/chara/ftZelda/ftZd_SpecialLw.c
    src/melee/ft/chara/ftZelda/ftZd_SpecialN.c
    src/melee/ft/chara/ftZelda/ftZd_SpecialS.c
    src/melee/ft/fighter.c
    src/melee/ft/ft_07C1.c
    src/melee/ft/ft_07C6.c
    src/melee/ft/ft_0819.c
    src/melee/ft/ft_081B.c
    src/melee/ft/ft_084E.c
    src/melee/ft/ft_0852.c
    src/melee/ft/ft_0877.c
    src/melee/ft/ft_0881.c
    src/melee/ft/ft_0892.c
    src/melee/ft/ft_0899.c
    src/melee/ft/ft_08A1.c
    src/melee/ft/ft_0BEC.c
    src/melee/ft/ft_0BEF.c
    src/melee/ft/ft_0BF0.c
    src/melee/ft/ft_0C31.c
    src/melee/ft/ft_0C88.c
    src/melee/ft/ft_0C8C.c
    src/melee/ft/ft_0CD1.c
    src/melee/ft/ft_0CD3.c
    src/melee/ft/ft_0CDD.c
    src/melee/ft/ft_0CDF.c
    src/melee/ft/ft_0CE3.c
    src/melee/ft/ft_0D27.c
    src/melee/ft/ft_0D31.c
    src/melee/ft/ft_0D4D.c
    src/melee/ft/ft_0DF0.c
    src/melee/ft/ft_0DF1.c
    src/melee/ft/ft_459A.c
    src/melee/ft/ftaction.c
    src/melee/ft/ftafterimage.c
    src/melee/ft/ftanim.c
    src/melee/ft/ftattacks4combo.c
    src/melee/ft/ftbosslib.c
    src/melee/ft/ftcamera.c
    src/melee/ft/ftchangeparam.c
    src/melee/ft/ftcliffcommon.c
    src/melee/ft/ftcmdscript.c
    src/melee/ft/ftCo_800C703C.c
    src/melee/ft/ftCo_800C7070.c
    src/melee/ft/ftCo_800C70D0.c
    src/melee/ft/ftCo_800C7178.c
    src/melee/ft/ftCo_800C7220.c
    src/melee/ft/ftCo_800C739C.c
    src/melee/ft/ftCo_800C7434.c
    src/melee/ft/ftCo_800C7590.c
    src/melee/ft/ftCo_800C78B0.c
    src/melee/ft/ftCo_800C7CA0.c
    src/melee/ft/ftcolanim.c
    src/melee/ft/ftcoll.c
    src/melee/ft/ftcommon.c
    src/melee/ft/ftcpuattack.c
    src/melee/ft/ftdata.c
    src/melee/ft/ftdemo.c
    src/melee/ft/ftdevice.c
    src/melee/ft/ftdrawcommon.c
    src/melee/ft/ftdynamics.c
    src/melee/ft/ftlib.c
    src/melee/ft/ftlipstickswing.c
    src/melee/ft/ftmaterial.c
    src/melee/ft/ftmetal.c
    src/melee/ft/ftmotionstates.c
    src/melee/ft/ftparts.c
    src/melee/ft/ftstarrodswing.c
    src/melee/ft/ftswing.c
    src/melee/ft/ftwaitanim.c
    src/melee/ft/ftwalkcommon.c
    src/melee/ft/ftwalljump.c
    src/melee/gm/gm_1601.c
    src/melee/gm/gm_16AE.c
    src/melee/gm/gm_16F1.c
    src/melee/gm/gm_1736.c
    src/melee/gm/gm_17AD.c
    src/melee/gm/gm_17BA.c
    src/melee/gm/gm_1832.c
    src/melee/gm/gm_19EF.c
    src/melee/gm/gm_1A33.c
    src/melee/gm/gm_1A36.c
    src/melee/gm/gm_1A3F.c
    src/melee/gm/gm_1A45.c
    src/melee/gm/gm_1A7A.c
    src/melee/gm/gm_1A9B.c
    src/melee/gm/gm_1ADD.c
    src/melee/gm/gm_1AED.c
    src/melee/gm/gm_1B03.c
    src/melee/gm/gmmenumode.c
    src/melee/gm/gmvsmode.c
    src/melee/gm/gmevent.c
    src/melee/gm/gmboot.c
    src/melee/gm/gm_1BFA.c
    src/melee/gm/gmadventure.c
    src/melee/gm/gmallstar.c
    src/melee/gm/gmapproach.c
    src/melee/gm/gmcamera.c
    src/melee/gm/gmclassic.c
    src/melee/gm/gmfixedcamera.c
    src/melee/gm/gmgiant.c
    src/melee/gm/gmhomerun.c
    src/melee/gm/gmhowto.c
    src/melee/gm/gminvisible.c
    src/melee/gm/gmlightning.c
    src/melee/gm/gmmain_lib.c
    src/melee/gm/gmmenu.c
    src/melee/gm/gmmovieend.c
    src/melee/gm/gmmultiman.c
    src/melee/gm/gmomake15.c
    src/melee/gm/gmopening.c
    src/melee/gm/gmpause.c
    src/melee/gm/gmprogressive.c
    src/melee/gm/gmregclear.c
    src/melee/gm/gmregcommon.c
    src/melee/gm/gmregenddisp.c
    src/melee/gm/gmregtyfall.c
    src/melee/gm/gmresult.c
    src/melee/gm/gmresultplayer.c
    src/melee/gm/gmscdata.c
    src/melee/gm/gmsinglebutton.c
    src/melee/gm/gmslomo.c
    src/melee/gm/gmstaffroll.c
    src/melee/gm/gmstamina.c
    src/melee/gm/gmsupersudden.c
    src/melee/gm/gmtiny.c
    src/melee/gm/gmtitle.c
    src/melee/gm/gmtou_0.c
    src/melee/gm/gmtou_1.c
    src/melee/gm/gmtou_2.c
    src/melee/gm/gmtoulib.c
    src/melee/gm/gmvsmelee.c
    src/melee/gr/grbattle.c
    src/melee/gr/grcorneria.c
    src/melee/gr/grdatfiles.c
    src/melee/gr/grdisplay.c
    src/melee/gr/grdynamicattr.c
    src/melee/gr/grfigureget.c
    src/melee/gr/grfzerocar.c
    src/melee/gr/grmaterial.c
    src/melee/gr/ground.c
    src/melee/gr/grpstadium.c
    src/melee/gr/grzakogenerator.c
    src/melee/gr/stage.c
    src/melee/if/if_2F6E.c
    src/melee/if/if_2F72.c
    src/melee/if/if_2FD9.c
    src/melee/if/if_2FF2.c
    src/melee/if/ifall.c
    src/melee/if/ifcoget.c
    src/melee/if/ifhazard.c
    src/melee/if/ifmagnify.c
    src/melee/if/ifnametag.c
    src/melee/if/ifprize.c
    src/melee/if/ifstatus.c
    src/melee/if/ifstock.c
    src/melee/if/iftime.c
    src/melee/if/soundtest.c
    src/melee/if/textdraw.c
    src/melee/if/textlib.c
    src/melee/it/it_26B1.c
    src/melee/it/it_2725.c
    src/melee/it/it_279C.c
    src/melee/it/it_3F14.c
    src/melee/it/it_3F2F.c
    src/melee/it/itanimlist.c
    src/melee/it/itcoll.c
    src/melee/it/itdraw.c
    src/melee/it/itdrop.c
    src/melee/it/iteffect.c
    src/melee/it/item.c
    src/melee/it/items/it_2ADA.c
    src/melee/it/items/it_2E5A.c
    src/melee/it/items/it_2F28.c
    src/melee/it/items/itarwinglaser.c
    src/melee/it/items/itbat.c
    src/melee/it/items/itbombhei.c
    src/melee/it/items/itbox.c
    src/melee/it/items/itcapsule.c
    src/melee/it/items/itcerebi.c
    src/melee/it/items/itchicorita.c
    src/melee/it/items/itclimbersblizzard.c
    src/melee/it/items/itclimbersice.c
    src/melee/it/items/itclimbersstring.c
    src/melee/it/items/itclinkmilk.c
    src/melee/it/items/itcoin.c
    src/melee/it/items/itcrazyhandbomb.c
    src/melee/it/items/itdkinoko.c
    src/melee/it/items/itdosei.c
    src/melee/it/items/itdrmariopill.c
    src/melee/it/items/itegg.c
    src/melee/it/items/itentei.c
    src/melee/it/items/itevyoshiegg.c
    src/melee/it/items/itfflower.c
    src/melee/it/items/itfflowerflame.c
    src/melee/it/items/itfire.c
    src/melee/it/items/itflipper.c
    src/melee/it/items/itfoods.c
    src/melee/it/items/itfoxblaster.c
    src/melee/it/items/itfoxillusion.c
    src/melee/it/items/itfoxlaser.c
    src/melee/it/items/itfreeze.c
    src/melee/it/items/itfreezer.c
    src/melee/it/items/itfushigibana.c
    src/melee/it/items/itgamewatchbreath.c
    src/melee/it/items/itgamewatchchef.c
    src/melee/it/items/itgamewatchfire.c
    src/melee/it/items/itgamewatchgreenhouse.c
    src/melee/it/items/itgamewatchjudge.c
    src/melee/it/items/itgamewatchmanhole.c
    src/melee/it/items/itgamewatchpanic.c
    src/melee/it/items/itgamewatchparachute.c
    src/melee/it/items/itgamewatchrescue.c
    src/melee/it/items/itgamewatchturtle.c
    src/melee/it/items/itgreatfoxlaser.c
    src/melee/it/items/itgshell.c
    src/melee/it/items/ithammer.c
    src/melee/it/items/ithammerhead.c
    src/melee/it/items/itharisen.c
    src/melee/it/items/ithassam.c
    src/melee/it/items/itheart.c
    src/melee/it/items/itheiho.c
    src/melee/it/items/ithinoarashi.c
    src/melee/it/items/ithitodeman.c
    src/melee/it/items/ithouou.c
    src/melee/it/items/itkabigon.c
    src/melee/it/items/itkamex.c
    src/melee/it/items/itkinoko.c
    src/melee/it/items/itkirby_2F23.c
    src/melee/it/items/itkirbycutterbeam.c
    src/melee/it/items/itkirbygamewatchchefpan.c
    src/melee/it/items/itkirbyhammer.c
    src/melee/it/items/itkirbyyoshispecialn.c
    src/melee/it/items/itkireihana.c
    src/melee/it/items/itklap.c
    src/melee/it/items/itkoopaflame.c
    src/melee/it/items/itkusudama.c
    src/melee/it/items/itkyasarin.c
    src/melee/it/items/itkyasarinegg.c
    src/melee/it/items/itleadead.c
    src/melee/it/items/itlgunbeam.c
    src/melee/it/items/itlgun.c
    src/melee/it/items/itlgunray.c
    src/melee/it/items/itlikelike.c
    src/melee/it/items/itlinkarrow.c
    src/melee/it/items/itlinkbomb.c
    src/melee/it/items/itlinkboomerang.c
    src/melee/it/items/itlinkbow.c
    src/melee/it/items/itlinkhookshot.c
    src/melee/it/items/itlipstick.c
    src/melee/it/items/itlipstickspore.c
    src/melee/it/items/itlizardon.c
    src/melee/it/items/itlucky.c
    src/melee/it/items/itlugia.c
    src/melee/it/items/itluigifireball.c
    src/melee/it/items/itmaril.c
    src/melee/it/items/itmariocape.c
    src/melee/it/items/itmariofireball.c
    src/melee/it/items/itmarumine.c
    src/melee/it/items/itmasterhandbullet.c
    src/melee/it/items/itmasterhandlaser.c
    src/melee/it/items/itmatadogas.c
    src/melee/it/items/itmato.c
    src/melee/it/items/itmball.c
    src/melee/it/items/itmetalb.c
    src/melee/it/items/itmetamon.c
    src/melee/it/items/itmew.c
    src/melee/it/items/itmewtwoshadowball.c
    src/melee/it/items/itmsbomb.c
    src/melee/it/items/itnessbat.c
    src/melee/it/items/itnesspkfire.c
    src/melee/it/items/itnesspkfirepillar.c
    src/melee/it/items/itnesspkflash.c
    src/melee/it/items/itnesspkflashexplode.c
    src/melee/it/items/itnesspkthunderball.c
    src/melee/it/items/itnesspkthundertrail.c
    src/melee/it/items/itnessyoyo.c
    src/melee/it/items/itnokonoko.c
    src/melee/it/items/itoctarock.c
    src/melee/it/items/itoctarockstone.c
    src/melee/it/items/itoldkuri.c
    src/melee/it/items/itoldottosea.c
    src/melee/it/items/itparasol.c
    src/melee/it/items/itpatapata.c
    src/melee/it/items/itpeachexplode.c
    src/melee/it/items/itpeachparasol.c
    src/melee/it/items/itpeachtoad.c
    src/melee/it/items/itpeachtoadspore.c
    src/melee/it/items/itpeachturnip.c
    src/melee/it/items/itpikachuthunder.c
    src/melee/it/items/itpikachutjoltair.c
    src/melee/it/items/itpikachutjoltground.c
    src/melee/it/items/itpippi.c
    src/melee/it/items/itporygon2.c
    src/melee/it/items/itrabbitc.c
    src/melee/it/items/itraikou.c
    src/melee/it/items/itrshell.c
    src/melee/it/items/itsamusbomb.c
    src/melee/it/items/itsamuschargeshot.c
    src/melee/it/items/itsamusgrapple.c
    src/melee/it/items/itsamusmissile.c
    src/melee/it/items/itscball.c
    src/melee/it/items/itseakchain.c
    src/melee/it/items/itseakneedleheld.c
    src/melee/it/items/itseakneedlethrown.c
    src/melee/it/items/itseakvanish.c
    src/melee/it/items/itsonans.c
    src/melee/it/items/itspycloak.c
    src/melee/it/items/itsscopebeam.c
    src/melee/it/items/itsscope.c
    src/melee/it/items/itstar.c
    src/melee/it/items/itstarrod.c
    src/melee/it/items/itstarrodstar.c
    src/melee/it/items/itsuikun.c
    src/melee/it/items/itsword.c
    src/melee/it/items/ittaru.c
    src/melee/it/items/ittarucann.c
    src/melee/it/items/itthunder.c
    src/melee/it/items/ittincle.c
    src/melee/it/items/ittogepy.c
    src/melee/it/items/ittomato.c
    src/melee/it/items/ittools.c
    src/melee/it/items/ittosakinto.c
    src/melee/it/items/itunknown.c
    src/melee/it/items/itwhispyapple.c
    src/melee/it/items/itwhitebea.c
    src/melee/it/items/itwstar.c
    src/melee/it/items/ityaku.c
    src/melee/it/items/ityoshiegglay.c
    src/melee/it/items/ityoshieggthrow.c
    src/melee/it/items/ityoshistar.c
    src/melee/it/items/ityoshitongue.c
    src/melee/it/items/itzeldadinfire.c
    src/melee/it/items/itzeldadinfireexplode.c
    src/melee/it/items/itzgshell.c
    src/melee/it/items/itzrshell.c
    src/melee/it/itgroundcoll.c
    src/melee/it/ithitbox.c
    src/melee/it/itmaplib.c
    src/melee/it/itmaterial.c
    src/melee/it/itspawn.c
    src/melee/it/itzako.c
    src/melee/lb/lb_00B0.c
    src/melee/lb/lb_00CE.c
    src/melee/lb/lb_00F9.c
    src/melee/lb/lb_013B.c
    src/melee/lb/lb_0146.c
    src/melee/lb/lb_0192.c
    src/melee/lb/lbanim.c
    src/melee/lb/lbarchive.c
    src/melee/lb/lbarq.c
    src/melee/lb/lbaudio_ax.c
    src/melee/lb/lbbgflash.c
    src/melee/lb/lbcardgame.c
    src/melee/lb/lbcommand.c
    src/melee/lb/lbdvd.c
    src/melee/lb/lbfile.c
    src/melee/lb/lbgx.c
    src/melee/lb/lbheap.c
    src/melee/lb/lblanguage.c
    src/melee/lb/lbmemory.c
    src/melee/lb/lbrefract.c
    src/melee/lb/lbshadow.c
    src/melee/lb/lbsnap.c
    src/melee/lb/lbspdisplay.c
    src/melee/lb/lbtime.c
    src/melee/lb/lbtrigf.c
    src/melee/lb/lbvector.c
    src/melee/mn/mn_22EC.c
    src/melee/mn/mncharsel.c
    src/melee/mn/mncount.c
    src/melee/mn/mndatadel.c
    src/melee/mn/mndeflicker.c
    src/melee/mn/mndiagram2.c
    src/melee/mn/mndiagram3.c
    src/melee/mn/mndiagram.c
    src/melee/mn/mnevent.c
    src/melee/mn/mngallery.c
    src/melee/mn/mnhyaku.c
    src/melee/mn/mninfobonus.c
    src/melee/mn/mninfo.c
    src/melee/mn/mnitemsw.c
    src/melee/mn/mnlanguage.c
    src/melee/mn/mnmain.c
    src/melee/mn/mnmainrule.c
    src/melee/mn/mnname.c
    src/melee/mn/mnnamenew.c
    src/melee/mn/mnruleplus.c
    src/melee/mn/mnsnap.c
    src/melee/mn/mnsound.c
    src/melee/mn/mnsoundtest.c
    src/melee/mn/mnstagesel.c
    src/melee/mn/mnstagesw.c
    src/melee/mn/mnvibration.c
    src/melee/mp/mpcoll.c
    src/melee/mp/mpisland.c
    src/melee/mp/mplib.c
    src/melee/pl/pl_040D.c
    src/melee/pl/plattack.c
    src/melee/pl/player.c
    src/melee/pl/plbonus.c
    src/melee/pl/plbonuslib.c
    src/melee/pl/plstale.c
    src/melee/pl/pltrick.c
    src/melee/sfx/crowdsfx.c
    src/melee/sfx/sfx_unk.c
    src/melee/ty/toy.c
    src/melee/ty/tydisplay.c
    src/melee/ty/tyfigupon.c
    src/melee/ty/tylist.c
    src/melee/vi/vi0102.c
    src/melee/vi/vi0401.c
    src/melee/vi/vi0402.c
    src/melee/vi/vi0501.c
    src/melee/vi/vi0502.c
    src/melee/vi/vi0601.c
    src/melee/vi/vi0801.c
    src/melee/vi/vi1101.c
    src/melee/vi/vi1201v1.c
    src/melee/vi/vi1201v2.c
    src/melee/vi/vi1202.c
    src/melee/vi/vi.c
)

add_compile_definitions(TARGET_PC)

add_library(melee STATIC ${SOURCES})

target_include_directories(melee PRIVATE
    $ENV{AURORA_SRC}/include
    src
    src/Runtime
    src/melee
    src/melee/ft/chara
)

install(TARGETS melee LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}")
