#ifndef MELEE_FT_CHARA_FTPEACH_FTPEACH_H
#define MELEE_FT_CHARA_FTPEACH_FTPEACH_H

#include "ft/fighter.h"

#include <baselib/gobj.h>

typedef struct _ftPeachAttributes {
    f32 unk0;
    f32 unk4;
    u8 padding[0xB8];
} ftPeachAttributes;

extern MotionState ftPe_Init_MotionStateTable[];
extern char ftPe_Init_DatFilename[];
extern char ftPe_Init_DataName[];
extern Fighter_CostumeStrings ftPe_Init_CostumeStrings[];
extern char ftPe_Init_AnimDatFilename[];
extern Fighter_DemoStrings ftPe_Init_DemoMotionFilenames;

void ftPe_Init_OnDeath(HSD_GObj* gobj);
s32 ftPe_8011BA20(Fighter* fp);
void ftPe_Init_OnKnockbackEnter(HSD_GObj* gobj);
void ftPe_Init_OnKnockbackExit(HSD_GObj* gobj);
void ftPe_Init_OnLoad(HSD_GObj* gobj);
void ftPe_Init_8011B704(HSD_GObj* gobj);
void ftPe_Init_OnItemPickup(HSD_GObj* gobj, bool bool);
void ftPe_Init_OnItemInvisible(HSD_GObj* gobj);
void ftPe_Init_OnItemVisible(HSD_GObj* gobj);
void ftPe_Init_OnItemDrop(HSD_GObj* gobj, bool bool1);
void ftPe_Init_LoadSpecialAttrs(HSD_GObj* gobj);
void ftPe_Init_8011B93C(HSD_GObj* gobj);
void ftPe_Float_Anim(HSD_GObj*);
void ftPe_Float_IASA(HSD_GObj*);
void ftPe_Float_Phys(HSD_GObj*);
void ftPe_Float_Coll(HSD_GObj*);
void ftPe_FloatEnd_Anim(HSD_GObj*);
void ftPe_FloatEnd_IASA(HSD_GObj*);
void ftPe_FloatEnd_Phys(HSD_GObj*);
void ftPe_FloatEnd_Coll(HSD_GObj*);
void ftPe_FloatEnd_Anim(HSD_GObj*);
void ftPe_FloatEnd_IASA(HSD_GObj*);
void ftPe_FloatEnd_Phys(HSD_GObj*);
void ftPe_FloatEnd_Coll(HSD_GObj*);
void ftPe_FloatAttackAir_Anim(HSD_GObj*);
void ftPe_FloatAttackAir_IASA(HSD_GObj*);
void ftPe_FloatAttackAir_Phys(HSD_GObj*);
void ftPe_FloatAttackAir_Coll(HSD_GObj*);
void ftPe_FloatAttackAir_Anim(HSD_GObj*);
void ftPe_FloatAttackAir_IASA(HSD_GObj*);
void ftPe_FloatAttackAir_Phys(HSD_GObj*);
void ftPe_FloatAttackAir_Coll(HSD_GObj*);
void ftPe_FloatAttackAir_Anim(HSD_GObj*);
void ftPe_FloatAttackAir_IASA(HSD_GObj*);
void ftPe_FloatAttackAir_Phys(HSD_GObj*);
void ftPe_FloatAttackAir_Coll(HSD_GObj*);
void ftPe_FloatAttackAir_Anim(HSD_GObj*);
void ftPe_FloatAttackAir_IASA(HSD_GObj*);
void ftPe_FloatAttackAir_Phys(HSD_GObj*);
void ftPe_FloatAttackAir_Coll(HSD_GObj*);
void ftPe_FloatAttackAir_Anim(HSD_GObj*);
void ftPe_FloatAttackAir_IASA(HSD_GObj*);
void ftPe_FloatAttackAir_Phys(HSD_GObj*);
void ftPe_FloatAttackAir_Coll(HSD_GObj*);
void ftPe_AttackS4_Anim(HSD_GObj*);
void ftPe_AttackS4_IASA(HSD_GObj*);
void ftPe_AttackS4_Phys(HSD_GObj*);
void ftPe_AttackS4_Coll(HSD_GObj*);
void ftPe_AttackS4_Anim(HSD_GObj*);
void ftPe_AttackS4_IASA(HSD_GObj*);
void ftPe_AttackS4_Phys(HSD_GObj*);
void ftPe_AttackS4_Coll(HSD_GObj*);
void ftPe_AttackS4_Anim(HSD_GObj*);
void ftPe_AttackS4_IASA(HSD_GObj*);
void ftPe_AttackS4_Phys(HSD_GObj*);
void ftPe_AttackS4_Coll(HSD_GObj*);
void ftPe_SpecialLw_Anim(HSD_GObj*);
void ftPe_SpecialLw_Phys(HSD_GObj*);
void ftPe_SpecialLw_Coll(HSD_GObj*);
void ftPe_SpecialAirLw_Anim(HSD_GObj*);
void ftPe_SpecialAirLw_Phys(HSD_GObj*);
void ftPe_SpecialAirLw_Coll(HSD_GObj*);
void ftPe_SpecialSStart_Anim(HSD_GObj*);
void ftPe_SpecialSStart_IASA(HSD_GObj*);
void ftPe_SpecialSStart_Phys(HSD_GObj*);
void ftPe_SpecialSStart_Coll(HSD_GObj*);
void ftPe_SpecialSEnd_Anim(HSD_GObj*);
void ftPe_SpecialSEnd_IASA(HSD_GObj*);
void ftPe_SpecialSEnd_Phys(HSD_GObj*);
void ftPe_SpecialSEnd_Coll(HSD_GObj*);
void ftPe_SpecialAirSStart_Anim(HSD_GObj*);
void ftPe_SpecialAirSStart_IASA(HSD_GObj*);
void ftPe_SpecialAirSStart_Phys(HSD_GObj*);
void ftPe_SpecialAirSStart_Coll(HSD_GObj*);
void ftPe_SpecialAirSEnd_Anim(HSD_GObj*);
void ftPe_SpecialAirSEnd_IASA(HSD_GObj*);
void ftPe_SpecialAirSEnd_Phys(HSD_GObj*);
void ftPe_SpecialAirSEnd_Coll(HSD_GObj*);
void ftPe_SpecialAirSEnd_Anim(HSD_GObj*);
void ftPe_SpecialAirSEnd_IASA(HSD_GObj*);
void ftPe_SpecialAirSEnd_Phys(HSD_GObj*);
void ftPe_SpecialAirSEnd_Coll(HSD_GObj*);
void ftPe_SpecialAirS_Anim(HSD_GObj*);
void ftPe_SpecialAirS_IASA(HSD_GObj*);
void ftPe_SpecialAirS_Phys(HSD_GObj*);
void ftPe_SpecialAirS_Coll(HSD_GObj*);
void ftPe_SpecialHiStart_Anim(HSD_GObj*);
void ftPe_SpecialHiStart_IASA(HSD_GObj*);
void ftPe_SpecialHiStart_Phys(HSD_GObj*);
void ftPe_SpecialHiStart_Coll(HSD_GObj*);
void ftPe_MS_362_Anim(HSD_GObj*);
void ftPe_MS_362_IASA(HSD_GObj*);
void ftPe_MS_362_Phys(HSD_GObj*);
void ftPe_MS_362_Coll(HSD_GObj*);
void ftPe_SpecialAirHiStart_Anim(HSD_GObj*);
void ftPe_SpecialAirHiStart_IASA(HSD_GObj*);
void ftPe_SpecialAirHiStart_Phys(HSD_GObj*);
void ftPe_SpecialAirHiStart_Coll(HSD_GObj*);
void ftPe_MS_364_Anim(HSD_GObj*);
void ftPe_MS_364_IASA(HSD_GObj*);
void ftPe_MS_364_Phys(HSD_GObj*);
void ftPe_MS_364_Coll(HSD_GObj*);
void ftPe_SpecialN_Anim(HSD_GObj*);
void ftPe_SpecialN_IASA(HSD_GObj*);
void ftPe_SpecialN_Phys(HSD_GObj*);
void ftPe_SpecialN_Coll(HSD_GObj*);
void ftPe_SpecialNAttack_Anim(HSD_GObj*);
void ftPe_SpecialNAttack_IASA(HSD_GObj*);
void ftPe_SpecialNAttack_Phys(HSD_GObj*);
void ftPe_SpecialNAttack_Coll(HSD_GObj*);
void ftPe_SpecialAirN_Anim(HSD_GObj*);
void ftPe_SpecialAirN_IASA(HSD_GObj*);
void ftPe_SpecialAirN_Phys(HSD_GObj*);
void ftPe_SpecialAirN_Coll(HSD_GObj*);
void ftPe_SpecialAirNAttack_Anim(HSD_GObj*);
void ftPe_SpecialAirNAttack_IASA(HSD_GObj*);
void ftPe_SpecialAirNAttack_Phys(HSD_GObj*);
void ftPe_SpecialAirNAttack_Coll(HSD_GObj*);
void ftPe_SpecialS_Enter(HSD_GObj*);
void ftPe_SpecialAirHi_Enter(HSD_GObj*);
void ftPe_SpecialAirLw_Enter(HSD_GObj*);
void ftPe_SpecialAirS_Enter(HSD_GObj*);
void ftPe_SpecialAirN_Enter(HSD_GObj*);
void ftPe_SpecialN_Enter(HSD_GObj*);
void ftPe_SpecialLw_Enter(HSD_GObj*);
void ftPe_SpecialHi_Enter(HSD_GObj*);

#endif
