#ifndef MELEE_FT_CHARA_FTMASTERHAND_FORWARD_H
#define MELEE_FT_CHARA_FTMASTERHAND_FORWARD_H

#include "ftCommon/forward.h"

typedef struct ftMasterHand_SpecialAttrs ftMasterHand_SpecialAttrs;

typedef enum ftMasterHand_UnkEnum0 {
    ftMh_UnkEnum0_Unk00,
    ftMh_UnkEnum0_Unk01,
    ftMh_UnkEnum0_Unk02,
    ftMh_UnkEnum0_Unk03,
    ftMh_UnkEnum0_Unk04,
    ftMh_UnkEnum0_Unk05,
    ftMh_UnkEnum0_Unk06,
    ftMh_UnkEnum0_Unk07,
    ftMh_UnkEnum0_Unk08,
    ftMh_UnkEnum0_Unk09,
    ftMh_UnkEnum0_Unk10,
} ftMasterHand_UnkEnum0;

typedef enum ftMasterhand_MotionState {
    ftMh_MS_Unk341 = ftCo_MS_Count,
    ftMh_MS_Unk342,
    ftMh_MS_Unk343,
    ftMh_MS_Unk344,
    ftMh_MS_Unk345,
    ftMh_MS_Unk346,
    ftMh_MS_Slap_StartMotion,
    ftMh_MS_Unk348,
    ftMh_MS_Sweep_StartMotion,
    ftMh_MS_Unk350,
    ftMh_MS_Walk_StartMotion,
    ftMh_MS_Unk352,
    ftMh_MS_Unk353,
    ftMh_MS_Drill_StartMotion,
    ftMh_MS_Punch_StartMotion,
    ftMh_MS_Unk356,
    ftMh_MS_Unk357,
    ftMh_MS_GroundSlap_StartMotion,
    ftMh_MS_Poke_StartMotion,
    ftMh_MS_Unk360,
    ftMh_MS_Unk361,
    ftMh_MS_Lasers_StartMotion,
    ftMh_MS_Unk363,
    ftMh_MS_Unk364,
    ftMh_MS_Gun_StartMotion,
    ftMh_MS_Unk366,
    ftMh_MS_Jet_StartMotion,
    ftMh_MS_Unk368,
    ftMh_MS_Unk369,
    ftMh_MS_Ram_StartMotion,
    ftMh_MS_Crush_StartMotion,
    ftMh_MS_Unk372,
    ftMh_MS_Unk373,
    ftMh_MS_Unk374,
    ftMh_MS_Unk375,
    ftMh_MS_Unk376,
    ftMh_MS_Unk377,
    ftMh_MS_Unk378,
    ftMh_MS_Grab_Unk0_MotionStart,
    ftMh_MS_Grab_Unk1_MotionStart,
    ftMh_MS_Unk381,
    ftMh_MS_Unk382,
    ftMh_MS_Unk383,
    ftMh_MS_Unk384,
    ftMh_MS_Unk385,
    ftMh_MS_Unk386,
    ftMh_MS_Unk387,
    ftMh_MS_Unk388,
    ftMh_MS_Unk389,
    ftMh_MS_Unk390,
} ftMasterhand_MotionState;

typedef enum ftMh_AnimId {
    ftMh_AnimId_MS_341_0 = ftCo_AnimId_Count,
    ftMh_AnimId_MS_341_1,
    ftMh_AnimId_MS_343,
    ftMh_AnimId_MS_344,
    ftMh_AnimId_MS_345,
    ftMh_AnimId_MS_346,
    ftMh_AnimId_MS_347,
    ftMh_AnimId_MS_348,
    ftMh_AnimId_MS_349,
    ftMh_AnimId_MS_350,
    ftMh_AnimId_MS_351,
    ftMh_AnimId_MS_352,
    ftMh_AnimId_MS_353,
    ftMh_AnimId_MS_354,
    ftMh_AnimId_MS_355,
    ftMh_AnimId_MS_356,
    ftMh_AnimId_MS_357,
    ftMh_AnimId_MS_358,
    ftMh_AnimId_MS_359,
    ftMh_AnimId_MS_360,
    ftMh_AnimId_MS_361,
    ftMh_AnimId_MS_362,
    ftMh_AnimId_MS_363,
    ftMh_AnimId_MS_364,
    ftMh_AnimId_MS_365,
    ftMh_AnimId_MS_366,
    ftMh_AnimId_MS_367,
    ftMh_AnimId_MS_368,
    ftMh_AnimId_MS_369,
    ftMh_AnimId_MS_370,
    ftMh_AnimId_MS_371,
    ftMh_AnimId_MS_372,
    ftMh_AnimId_MS_373,
    ftMh_AnimId_MS_374,
    ftMh_AnimId_MS_375,
    ftMh_AnimId_MS_376_0,
    ftMh_AnimId_MS_376_1,
    ftMh_AnimId_MS_378,
    ftMh_AnimId_MS_379,
    ftMh_AnimId_MS_380,
    ftMh_AnimId_MS_381,
    ftMh_AnimId_MS_382,
    ftMh_AnimId_MS_383,
    ftMh_AnimId_MS_384,
    ftMh_AnimId_MS_385,
    ftMh_AnimId_MS_386,
    ftMh_AnimId_MS_387,
    ftMh_AnimId_MS_388,
    ftMh_AnimId_MS_389_0,
    ftMh_AnimId_MS_389_1,
} ftMh_AnimId;

#endif
