#ifndef MELEE_FT_CHARA_FTMASTERHAND_FORWARD_H
#define MELEE_FT_CHARA_FTMASTERHAND_FORWARD_H

#include "ftCommon/forward.h"

typedef struct ftMasterHand_SpecialAttrs ftMasterHand_SpecialAttrs;

typedef enum ftMasterHand_UnkEnum0 {
    ftMh_UnkEnum0_Unk00,
    ftMh_UnkEnum0_Unk01,
    ftMh_UnkEnum0_Unk02,
    ftMh_UnkEnum0_Unk03,
    ftMh_UnkEnum0_Unk04,
    ftMh_UnkEnum0_Unk05,
    ftMh_UnkEnum0_Unk06,
    ftMh_UnkEnum0_Unk07,
    ftMh_UnkEnum0_Unk08,
    ftMh_UnkEnum0_Unk09,
    ftMh_UnkEnum0_Unk10,
} ftMasterHand_UnkEnum0;

typedef enum ftMasterhand_MotionState {
    ftMh_MS_Wait1_0 = ftCo_MS_Count,
    ftMh_MS_Wait2_0,
    ftMh_MS_Entry,
    ftMh_MS_Damage,
    ftMh_MS_Damage2,
    ftMh_MS_WaitSweep,
    ftMh_MS_SweepLoop,
    ftMh_MS_SweepWait,
    ftMh_MS_Slap,
    ftMh_MS_Walk2,
    ftMh_MS_WalkLoop,
    ftMh_MS_WalkWait,
    ftMh_MS_WalkShoot,
    ftMh_MS_Drill,
    ftMh_MS_RockCrushUp,
    ftMh_MS_RockCrushWait,
    ftMh_MS_RockCrushDown,
    ftMh_MS_PaperCrush,
    ftMh_MS_Poke1,
    ftMh_MS_Poke2,
    ftMh_MS_FingerBeamStart,
    ftMh_MS_FingerBeamLoop,
    ftMh_MS_FingerBeamEnd,
    ftMh_MS_FingerGun1,
    ftMh_MS_FingerGun2,
    ftMh_MS_FingerGun3,
    ftMh_MS_BackAirplane1,
    ftMh_MS_BackAirplane2,
    ftMh_MS_BackAirplane3,
    ftMh_MS_BackPunch,
    ftMh_MS_BackCrush,
    ftMh_MS_BackDisappear,
    ftMh_MS_Wait1_1,
    ftMh_MS_Grab,
    ftMh_MS_Cancel,
    ftMh_MS_Squeezing0,
    ftMh_MS_Squeezing1,
    ftMh_MS_Squeeze,
    ftMh_MS_Throw,
    ftMh_MS_Slam,
    ftMh_MS_Fail,
    ftMh_MS_TagCrush,
    ftMh_MS_TagApplaud,
    ftMh_MS_TagRockPaper,
    ftMh_MS_TagGrab,
    ftMh_MS_TagSqueeze,
    ftMh_MS_TagFail,
    ftMh_MS_TagCancel,
    ftMh_MS_Wait1_2,
    ftMh_MS_Wait2_1,
    ftMh_MS_Count,
    ftMh_MS_SelfCount = ftMh_MS_Count - ftCo_MS_Count,
} ftMasterhand_MotionState;

typedef enum ftMh_Submotion {
    ftMh_SM_Wait1_0 = ftCo_SM_Count,
    ftMh_SM_Wait2_0,
    ftMh_SM_Entry,
    ftMh_SM_Damage,
    ftMh_SM_Damage2,
    ftMh_SM_WaitSweep,
    ftMh_SM_SweepLoop,
    ftMh_SM_SweepWait,
    ftMh_SM_Slap,
    ftMh_SM_Walk2,
    ftMh_SM_WalkLoop,
    ftMh_SM_WalkWait,
    ftMh_SM_WalkShoot,
    ftMh_SM_Drill,
    ftMh_SM_RockCrushUp,
    ftMh_SM_RockCrushWait,
    ftMh_SM_RockCrushDown,
    ftMh_SM_PaperCrush,
    ftMh_SM_Poke1,
    ftMh_SM_Poke2,
    ftMh_SM_FingerBeamStart,
    ftMh_SM_FingerBeamLoop,
    ftMh_SM_FingerBeamEnd,
    ftMh_SM_FingerGun1,
    ftMh_SM_FingerGun2,
    ftMh_SM_FingerGun3,
    ftMh_SM_BackAirplane1,
    ftMh_SM_BackAirplane2,
    ftMh_SM_BackAirplane3,
    ftMh_SM_BackPunch,
    ftMh_SM_BackCrush,
    ftMh_SM_BackDisappear,
    ftMh_SM_Wait1_1,
    ftMh_SM_Grab,
    ftMh_SM_Cancel,
    ftMh_SM_Squeezing0,
    ftMh_SM_Squeezing1,
    ftMh_SM_Squeeze,
    ftMh_SM_Throw,
    ftMh_SM_Slam,
    ftMh_SM_Fail,
    ftMh_SM_TagCrush,
    ftMh_SM_TagApplaud,
    ftMh_SM_TagRockPaper,
    ftMh_SM_TagGrab,
    ftMh_SM_TagSqueeze,
    ftMh_SM_TagFail,
    ftMh_SM_TagCancel,
    ftMh_SM_Wait1_2,
    ftMh_SM_Wait2_1,
    ftMh_SM_Count,
    ftMh_SM_SelfCount = ftMh_SM_Count - ftCo_SM_Count,
} ftMh_Submotion;

#endif
