#ifndef MELEE_FT_CHARA_FTMASTERHAND_FORWARD_H
#define MELEE_FT_CHARA_FTMASTERHAND_FORWARD_H

#include "ftCommon/forward.h"

typedef struct ftMasterHand_SpecialAttrs ftMasterHand_SpecialAttrs;

typedef enum ftMasterHand_UnkEnum0 {
    ftMh_UnkEnum0_Unk00,
    ftMh_UnkEnum0_Unk01,
    ftMh_UnkEnum0_Unk02,
    ftMh_UnkEnum0_Unk03,
    ftMh_UnkEnum0_Unk04,
    ftMh_UnkEnum0_Unk05,
    ftMh_UnkEnum0_Unk06,
    ftMh_UnkEnum0_Unk07,
    ftMh_UnkEnum0_Unk08,
    ftMh_UnkEnum0_Unk09,
    ftMh_UnkEnum0_Unk10,
} ftMasterHand_UnkEnum0;

typedef enum ftMasterhand_MotionState {
    ftMh_MS_Unk341 = ftCo_MS_Count,
    ftMh_MS_Unk342,
    ftMh_MS_Unk343,
    ftMh_MS_Unk344,
    ftMh_MS_Unk345,
    ftMh_MS_Unk346,
    ftMh_MS_Slap_StartMotion,
    ftMh_MS_Unk348,
    ftMh_MS_Sweep_StartMotion,
    ftMh_MS_Unk350,
    ftMh_MS_Walk_StartMotion,
    ftMh_MS_Unk352,
    ftMh_MS_Unk353,
    ftMh_MS_Drill_StartMotion,
    ftMh_MS_Punch_StartMotion,
    ftMh_MS_Unk356,
    ftMh_MS_Unk357,
    ftMh_MS_GroundSlap_StartMotion,
    ftMh_MS_Poke_StartMotion,
    ftMh_MS_Unk360,
    ftMh_MS_Unk361,
    ftMh_MS_Lasers_StartMotion,
    ftMh_MS_Unk363,
    ftMh_MS_Unk364,
    ftMh_MS_Gun_StartMotion,
    ftMh_MS_Unk366,
    ftMh_MS_Jet_StartMotion,
    ftMh_MS_Unk368,
    ftMh_MS_Unk369,
    ftMh_MS_Ram_StartMotion,
    ftMh_MS_Crush_StartMotion,
    ftMh_MS_Unk372,
    ftMh_MS_Unk373,
    ftMh_MS_Unk374,
    ftMh_MS_Unk375,
    ftMh_MS_Unk376,
    ftMh_MS_Unk377,
    ftMh_MS_Unk378,
    ftMh_MS_Grab_Unk0_MotionStart,
    ftMh_MS_Grab_Unk1_MotionStart,
    ftMh_MS_Unk381,
    ftMh_MS_Unk382,
    ftMh_MS_Unk383,
    ftMh_MS_Unk384,
    ftMh_MS_Unk385,
    ftMh_MS_Unk386,
    ftMh_MS_Unk387,
    ftMh_MS_Unk388,
    ftMh_MS_Unk389,
    ftMh_MS_Unk390,
} ftMasterhand_MotionState;

typedef enum ftMh_Submotion {
    ftMh_SM_Wait1_0 = ftCo_SM_Count,
    ftMh_SM_Wait2_0,
    ftMh_SM_Entry,
    ftMh_SM_Damage,
    ftMh_SM_Damage2,
    ftMh_SM_WaitSweep,
    ftMh_SM_SweepLoop,
    ftMh_SM_SweepWait,
    ftMh_SM_Slap,
    ftMh_SM_Walk2,
    ftMh_SM_WalkLoop,
    ftMh_SM_WalkWait,
    ftMh_SM_WalkShoot,
    ftMh_SM_Drill,
    ftMh_SM_RockCrushUp,
    ftMh_SM_RockCrushWait,
    ftMh_SM_RockCrushDown,
    ftMh_SM_PaperCrush,
    ftMh_SM_Poke1,
    ftMh_SM_Poke2,
    ftMh_SM_FingerBeamStart,
    ftMh_SM_FingerBeamLoop,
    ftMh_SM_FingerBeamEnd,
    ftMh_SM_FingerGun1,
    ftMh_SM_FingerGun2,
    ftMh_SM_FingerGun3,
    ftMh_SM_BackAirplane1,
    ftMh_SM_BackAirplane2,
    ftMh_SM_BackAirplane3,
    ftMh_SM_BackPunch,
    ftMh_SM_BackCrush,
    ftMh_SM_BackDisappear,
    ftMh_SM_Wait1_1,
    ftMh_SM_Grab,
    ftMh_SM_Cancel,
    ftMh_SM_Squeezing0,
    ftMh_SM_Squeezing1,
    ftMh_SM_Squeeze,
    ftMh_SM_Throw,
    ftMh_SM_Slam,
    ftMh_SM_Fail,
    ftMh_SM_TagCrush,
    ftMh_SM_TagApplaud,
    ftMh_SM_TagRockPaper,
    ftMh_SM_TagGrab,
    ftMh_SM_TagSqueeze,
    ftMh_SM_TagFail,
    ftMh_SM_TagCancel,
    ftMh_SM_Wait1_2,
    ftMh_SM_Wait2_1,
} ftMh_Submotion;

#endif
