#ifndef MELEE_FT_CHARA_FTPIKACHU_FTPIKACHU_H
#define MELEE_FT_CHARA_FTPIKACHU_FTPIKACHU_H

#include <platform.h>
#include <baselib/forward.h>

#include "ft/ftcommon.h"
#include "ft/types.h"
#include "lb/lbvector.h"

extern MotionState ftPk_Init_MotionStateTable[];
extern char ftPk_Init_DatFilename[];
extern char ftPk_Init_DataName[];
extern Fighter_CostumeStrings ftPk_Init_CostumeStrings[];
extern char ftPk_Init_AnimDatFilename[];
extern Fighter_DemoStrings ftPk_Init_DemoMotionFilenames;

void ftPk_Init_LoadSpecialAttrs(HSD_GObj*);

/// pika1
void ftPk_Init_OnLoadForPichu(Fighter* fp);
void ftPk_Init_OnLoad(HSD_GObj* gobj);
void ftPk_Init_OnDeath(HSD_GObj* gobj);
void ftPk_Init_OnItemPickup(HSD_GObj* gobj, bool arg1);
void ftPk_Init_OnItemInvisible(HSD_GObj* gobj);
void ftPk_Init_OnItemVisible(HSD_GObj* gobj);
void ftPk_Init_OnItemDrop(HSD_GObj* gobj, bool arg1);
void ftPk_Init_UnkMotionStates1(HSD_GObj* gobj);
void ftPk_Init_UnkMotionStates2(HSD_GObj* gobj);
void ftPk_Init_LoadSpecialAttrs(HSD_GObj* gobj);
void ftPk_Init_OnKnockbackEnter(HSD_GObj* gobj);
void ftPk_Init_OnKnockbackExit(HSD_GObj* gobj);

/// pika2
void ftPk_SpecialN_Enter(HSD_GObj* gobj);
void ftPk_SpecialAirN_Enter(HSD_GObj* gobj);
void ftPk_SpecialN_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirN_Anim(HSD_GObj* gobj);
void ftPk_SpecialN_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirN_Phys(HSD_GObj* gobj);
void ftPk_SpecialN_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirN_Coll(HSD_GObj* gobj);
void ftPk_SpecialN_SpawnEffect0(HSD_GObj* gobj);
void ftPk_SpecialN_SpawnEffect1(HSD_GObj* gobj);
void ftPk_SpecialN_80124DC8(HSD_GObj* gobj);

// pika3
void ftPk_SpecialS_Enter(HSD_GObj* gobj);
void ftPk_SpecialAirS_Enter(HSD_GObj* gobj);
void ftPk_SpecialS_ZeroVelocity(HSD_GObj* gobj);
void ftPk_SpecialSStart_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirSStart_Anim(HSD_GObj* gobj);
void ftPk_SpecialSStart_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirSStart_Phys(HSD_GObj* gobj);
void ftPk_SpecialSStart_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirSStart_Coll(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk00(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk01(HSD_GObj* gobj);
void ftPk_SpecialSCharge_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirSCharge_Anim(HSD_GObj* gobj);
void ftPk_SpecialSCharge_IASA(HSD_GObj* gobj);
void ftPk_SpecialAirSCharge_IASA(HSD_GObj* gobj);
void ftPk_SpecialSCharge_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirSCharge_Phys(HSD_GObj* gobj);
void ftPk_SpecialSCharge_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirSCharge_Coll(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk02(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk03(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk04(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk05(HSD_GObj* gobj);
void ftPk_SpecialSLaunch_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirSLaunch_Anim(HSD_GObj* gobj);
void ftPk_SpecialSLaunch_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirSLaunch_Phys(HSD_GObj* gobj);
void ftPk_SpecialSLaunch_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirSLaunch_Coll(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk06(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk07(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk08(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk09(HSD_GObj* gobj);
void ftPk_SpecialAirS_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirS_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirS_Coll(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk10(HSD_GObj* gobj);
void ftPk_SpecialSLanding_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirSEnd_Anim(HSD_GObj* gobj);
void ftPk_SpecialSLanding_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirSEnd_Phys(HSD_GObj* gobj);
void ftPk_SpecialSLanding_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirSEnd_Coll(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk11(HSD_GObj* gobj);
void ftPk_SpecialS_ChangeMotion_Unk12(HSD_GObj* gobj);

/// pika4
void ftPk_SpecialHi_UpdateVel(HSD_GObj* gobj);
void ftPk_SpecialHi_Enter(HSD_GObj* gobj);
void ftPk_SpecialAirHi_Enter(HSD_GObj* gobj);
void ftPk_SpecialHiStart_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirHiStart_Anim(HSD_GObj* gobj);
void ftPk_SpecialHiStart_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirHiStart_Phys(HSD_GObj* gobj);
void ftPk_SpecialHiStart_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirHiStart_Coll(HSD_GObj* gobj);
void ftPk_SpecialHi_ChangeMotion_Unk00(HSD_GObj* gobj);
void ftPk_SpecialHi_ChangeMotion_Unk01(HSD_GObj* gobj);
void ftPk_SpecialHi_Anim(HSD_GObj* gobj);
void ftPk_SpecialAir_Anim(HSD_GObj* gobj);
void ftPk_SpecialHi_8012642C(HSD_GObj* gobj);
void ftPk_SpecialHi_Phys(HSD_GObj* gobj);
void ftPk_SpecialAir_Phys(HSD_GObj* gobj);
void ftPk_SpecialHi_Coll(HSD_GObj* gobj);
void ftPk_SpecialAir_Coll(HSD_GObj* gobj);
void ftPk_SpecialHi_ChangeMotion_Unk02(HSD_GObj* gobj);
void ftPk_SpecialHi_ChangeMotion_Unk03(HSD_GObj* gobj);
void ftPk_SpecialHi_80126C0C(HSD_GObj* gobj);
void ftPk_SpecialHi_80126E1C(HSD_GObj* gobj);
bool ftPk_SpecialHi_80127064(HSD_GObj* gobj);
void ftPk_SpecialHiEnd_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirEnd_Anim(HSD_GObj* gobj);
void ftPk_SpecialHiEnd_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirEnd_Phys(HSD_GObj* gobj);
void ftPk_SpecialHiEnd_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirEnd_Coll(HSD_GObj* gobj);
void ftPk_SpecialHi_ChangeMotion_Unk04(HSD_GObj* gobj);
void ftPk_SpecialHi_MotionChangeUpdateVel_Unk0(HSD_GObj* gobj);
void ftPk_SpecialHi_MotionChangeUpdateVel_Unk1(HSD_GObj* gobj);

// pika5
bool ftPk_SpecialLw_CheckProperty(HSD_GObj* gobj);
void ftPk_SpecialLw_80127608(HSD_GObj* gobj);
void ftPk_SpecialLw_SetState_Unk0(HSD_GObj* gobj);
bool ftPk_SpecialLw_8012765C(HSD_GObj* gobj);
void ftPk_SpecialLw_SetState_Unk1(HSD_GObj* gobj);
void ftPk_SpecialLw_SpawnEffect(HSD_GObj* gobj);
void ftPk_SpecialLw_Enter(HSD_GObj* gobj);
void ftPk_SpecialAirLw_Enter(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk00(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk01(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk02(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk03(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk04(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk05(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk06(HSD_GObj* gobj);
void ftPk_SpecialLw_ChangeMotion_Unk07(HSD_GObj* gobj);
void ftPk_SpecialLwStart_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirLwStart_Anim(HSD_GObj* gobj);
void ftPk_SpecialLw_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirLw_Anim(HSD_GObj* gobj);
void ftPk_SpecialLwHit_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirLwHit_Anim(HSD_GObj* gobj);
void ftPk_SpecialLwEnd_Anim(HSD_GObj* gobj);
void ftPk_SpecialAirLwEnd_Anim(HSD_GObj* gobj);
void ftPk_SpecialLwStart_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirLwStart_Phys(HSD_GObj* gobj);
void ftPk_SpecialLw_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirLw_Phys(HSD_GObj* gobj);
void ftPk_SpecialLwHit_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirLwHit_Phys(HSD_GObj* gobj);
void ftPk_SpecialLwEnd_Phys(HSD_GObj* gobj);
void ftPk_SpecialAirLwEnd_Phys(HSD_GObj* gobj);
void ftPk_SpecialLwStart_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirLwStart_Coll(HSD_GObj* gobj);
void ftPk_SpecialLw_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirLw_Coll(HSD_GObj* gobj);
void ftPk_SpecialLwHit_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirLwHit_Coll(HSD_GObj* gobj);
void ftPk_SpecialLwEnd_Coll(HSD_GObj* gobj);
void ftPk_SpecialAirLwEnd_Coll(HSD_GObj* gobj);

void ftPk_SpecialN_Anim(HSD_GObj*);
void ftPk_SpecialN_IASA(HSD_GObj*);
void ftPk_SpecialN_Phys(HSD_GObj*);
void ftPk_SpecialN_Coll(HSD_GObj*);
void ftPk_SpecialAirN_Anim(HSD_GObj*);
void ftPk_SpecialAirN_IASA(HSD_GObj*);
void ftPk_SpecialAirN_Phys(HSD_GObj*);
void ftPk_SpecialAirN_Coll(HSD_GObj*);
void ftPk_SpecialSStart_Anim(HSD_GObj*);
void ftPk_SpecialSStart_IASA(HSD_GObj*);
void ftPk_SpecialSStart_Phys(HSD_GObj*);
void ftPk_SpecialSStart_Coll(HSD_GObj*);
void ftPk_SpecialSCharge_Anim(HSD_GObj*);
void ftPk_SpecialSCharge_IASA(HSD_GObj*);
void ftPk_SpecialSCharge_Phys(HSD_GObj*);
void ftPk_SpecialSCharge_Coll(HSD_GObj*);
void ftPk_MS_345_Anim(HSD_GObj*);
void ftPk_MS_345_IASA(HSD_GObj*);
void ftPk_MS_345_Phys(HSD_GObj*);
void ftPk_MS_345_Coll(HSD_GObj*);
void ftPk_SpecialSLanding_Anim(HSD_GObj*);
void ftPk_SpecialSLanding_IASA(HSD_GObj*);
void ftPk_SpecialSLanding_Phys(HSD_GObj*);
void ftPk_SpecialSLanding_Coll(HSD_GObj*);
void ftPk_SpecialSLaunch_Anim(HSD_GObj*);
void ftPk_SpecialSLaunch_IASA(HSD_GObj*);
void ftPk_SpecialSLaunch_Phys(HSD_GObj*);
void ftPk_SpecialSLaunch_Coll(HSD_GObj*);
void ftPk_SpecialAirSStart_Anim(HSD_GObj*);
void ftPk_SpecialAirSStart_IASA(HSD_GObj*);
void ftPk_SpecialAirSStart_Phys(HSD_GObj*);
void ftPk_SpecialAirSStart_Coll(HSD_GObj*);
void ftPk_SpecialAirSCharge_Anim(HSD_GObj*);
void ftPk_SpecialAirSCharge_IASA(HSD_GObj*);
void ftPk_SpecialAirSCharge_Phys(HSD_GObj*);
void ftPk_SpecialAirSCharge_Coll(HSD_GObj*);
void ftPk_SpecialAirS_Anim(HSD_GObj*);
void ftPk_SpecialAirS_IASA(HSD_GObj*);
void ftPk_SpecialAirS_Phys(HSD_GObj*);
void ftPk_SpecialAirS_Coll(HSD_GObj*);
void ftPk_SpecialAirSEnd_Anim(HSD_GObj*);
void ftPk_SpecialAirSEnd_IASA(HSD_GObj*);
void ftPk_SpecialAirSEnd_Phys(HSD_GObj*);
void ftPk_SpecialAirSEnd_Coll(HSD_GObj*);
void ftPk_SpecialAirSLaunch_Anim(HSD_GObj*);
void ftPk_SpecialAirSLaunch_IASA(HSD_GObj*);
void ftPk_SpecialAirSLaunch_Phys(HSD_GObj*);
void ftPk_SpecialAirSLaunch_Coll(HSD_GObj*);
void ftPk_SpecialHiStart_Anim(HSD_GObj*);
void ftPk_SpecialHiStart_IASA(HSD_GObj*);
void ftPk_SpecialHiStart_Phys(HSD_GObj*);
void ftPk_SpecialHiStart_Coll(HSD_GObj*);
void ftPk_SpecialHi_Anim(HSD_GObj*);
void ftPk_SpecialHi_IASA(HSD_GObj*);
void ftPk_SpecialHi_Phys(HSD_GObj*);
void ftPk_SpecialHi_Coll(HSD_GObj*);
void ftPk_SpecialHiEnd_Anim(HSD_GObj*);
void ftPk_SpecialHiEnd_IASA(HSD_GObj*);
void ftPk_SpecialHiEnd_Phys(HSD_GObj*);
void ftPk_SpecialHiEnd_Coll(HSD_GObj*);
void ftPk_SpecialAirHiStart_Anim(HSD_GObj*);
void ftPk_SpecialAirHiStart_IASA(HSD_GObj*);
void ftPk_SpecialAirHiStart_Phys(HSD_GObj*);
void ftPk_SpecialAirHiStart_Coll(HSD_GObj*);
void ftPk_SpecialAir_Anim(HSD_GObj*);
void ftPk_SpecialAir_IASA(HSD_GObj*);
void ftPk_SpecialAir_Phys(HSD_GObj*);
void ftPk_SpecialAir_Coll(HSD_GObj*);
void ftPk_SpecialAirEnd_Anim(HSD_GObj*);
void ftPk_SpecialAirEnd_IASA(HSD_GObj*);
void ftPk_SpecialAirEnd_Phys(HSD_GObj*);
void ftPk_SpecialAirEnd_Coll(HSD_GObj*);
void ftPk_SpecialLwStart_Anim(HSD_GObj*);
void ftPk_SpecialLwStart_Phys(HSD_GObj*);
void ftPk_SpecialLwStart_Coll(HSD_GObj*);
void ftPk_SpecialLw_Anim(HSD_GObj*);
void ftPk_SpecialLw_Phys(HSD_GObj*);
void ftPk_SpecialLw_Coll(HSD_GObj*);
void ftPk_SpecialLwHit_Anim(HSD_GObj*);
void ftPk_SpecialLwHit_Phys(HSD_GObj*);
void ftPk_SpecialLwHit_Coll(HSD_GObj*);
void ftPk_SpecialLwEnd_Anim(HSD_GObj*);
void ftPk_SpecialLwEnd_Phys(HSD_GObj*);
void ftPk_SpecialLwEnd_Coll(HSD_GObj*);
void ftPk_SpecialAirLwStart_Anim(HSD_GObj*);
void ftPk_SpecialAirLwStart_Phys(HSD_GObj*);
void ftPk_SpecialAirLwStart_Coll(HSD_GObj*);
void ftPk_SpecialAirLw_Anim(HSD_GObj*);
void ftPk_SpecialAirLw_Phys(HSD_GObj*);
void ftPk_SpecialAirLw_Coll(HSD_GObj*);
void ftPk_SpecialAirLwHit_Anim(HSD_GObj*);
void ftPk_SpecialAirLwHit_Phys(HSD_GObj*);
void ftPk_SpecialAirLwHit_Coll(HSD_GObj*);
void ftPk_SpecialAirLwEnd_Anim(HSD_GObj*);
void ftPk_SpecialAirLwEnd_Phys(HSD_GObj*);
void ftPk_SpecialAirLwEnd_Coll(HSD_GObj*);

#endif
