#include <stdio.h>
#include <console_io.h>

FILE __files[3] = {
    {
        0,
        0,
        1,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        (unsigned char*)&(stdin)->char_buffer,
        1,
        (unsigned char*)&(stdin)->char_buffer,
        0,
        0,
        0,
        0,
        NULL,
        __read_console,
        __write_console,
        __close_console,
        NULL,
    },
    {
        0,
        0,
        2,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        (unsigned char*)&(stdout)->char_buffer,
        1,
        (unsigned char*)&(stdout)->char_buffer,
        0,
        0,
        0,
        0,
        NULL,
        __read_console,
        __write_console,
        __close_console,
        NULL,
    },
    {
        0,
        0,
        2,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        (unsigned char*)&(stderr)->char_buffer,
        1,
        (unsigned char*)&(stderr)->char_buffer,
        0,
        0,
        0,
        0,
        NULL,
        __read_console,
        __write_console,
        __close_console,
        NULL,
    },
};
