static void cbForCancelSync(s32, DVDCommandBlock*);
static void cbForStateBusy(u32 intType);
static void cbForStateCheckID1(u32 intType);
static void cbForStateCheckID2(u32);
static void cbForStateCheckID3(u32);
static void cbForStateCoverClosed(u32 intType);
static void cbForStateError(u32 intType);
static void cbForStateGettingError(u32 intType);
static void cbForStateGoToRetry(u32 intType);
static void cbForStateMotorStopped(u32 intType);
static void cbForStateReadingFST(u32 intType);
static void cbForUnrecoveredError(u32 intType);
static void cbForUnrecoveredErrorRetry(u32 intType);
static void stateBusy(DVDCommandBlock*);
static void stateCheckID2(DVDCommandBlock*);
static void stateCheckID3(DVDCommandBlock*);
static void stateCoverClosed(void);
static void stateCoverClosed_CMD(DVDCommandBlock*);
static void stateGettingError(void);
static void stateGoToRetry(void);
static void stateMotorStopped(void);
static void stateReady(void);
static void stateTimeout(void);
