#ifndef MELEE_PL_FORWARD_H
#define MELEE_PL_FORWARD_H

#define PL_SLOT_MAX 6

typedef struct StaleMoveTable StaleMoveTable;
typedef struct plAllocInfo2 plAllocInfo2;
typedef struct plActionStats plActionStats;
typedef struct pl_800386E8_arg0_t pl_800386E8_arg0_t;
typedef struct pl_804D6470_t pl_804D6470_t;
typedef struct pl_StaleMoveTableExt_t pl_StaleMoveTableExt_t;

typedef enum {
    Gm_PKind_Human,
    Gm_PKind_Cpu,
    Gm_PKind_Demo,
    Gm_PKind_NA,
    Gm_PKind_Boss,
} Gm_PKind;

typedef enum {
    /* 00 */ StatsAttack_None,
    /* 01 */ StatsAttack_Attack11,
    /* 02 */ StatsAttack_Attack12,
    /* 03 */ StatsAttack_Attack13,
    /* 04 */ StatsAttack_Attack100,
    /* 05 */ StatsAttack_AttackDash,
    /* 06 */ StatsAttack_AttackS3,
    /* 07 */ StatsAttack_AttackHi3,
    /* 08 */ StatsAttack_AttackLw3,
    /* 09 */ StatsAttack_AttackS4,
    /* 0A */ StatsAttack_AttackHi4,
    /* 0B */ StatsAttack_AttackLw4,
    /* 0C */ StatsAttack_AttackAirN,
    /* 0D */ StatsAttack_AttackAirF,
    /* 0E */ StatsAttack_AttackAirB,
    /* 0F */ StatsAttack_AttackAirHi,
    /* 10 */ StatsAttack_AttackAirLw,
    /* 11 */ StatsAttack_SpecialN,
    /* 12 */ StatsAttack_SpecialS,
    /* 13 */ StatsAttack_SpecialHi,
    /* 14 */ StatsAttack_SpecialLw,
    /* 15 */ StatsAttack_KbSpecialNMr,
    /* 16 */ StatsAttack_KbSpecialNFx,
    /* 17 */ StatsAttack_KbSpecialNCa,
    /* 18 */ StatsAttack_KbSpecialNDk,
    /* 19 */ StatsAttack_KbSpecialNKp,
    /* 1A */ StatsAttack_KbSpecialNLk,
    /* 1B */ StatsAttack_KbSpecialNSk,
    /* 1C */ StatsAttack_KbSpecialNNs,
    /* 1D */ StatsAttack_KbSpecialNPe,
    /* 1E */ StatsAttack_KbSpecialNPp,
    /* 1F */ StatsAttack_KbSpecialNPk,
    /* 20 */ StatsAttack_KbSpecialNSs,
    /* 21 */ StatsAttack_KbSpecialNYs,
    /* 22 */ StatsAttack_KbSpecialNPr,
    /* 23 */ StatsAttack_KbSpecialNMt,
    /* 24 */ StatsAttack_KbSpecialNLg,
    /* 25 */ StatsAttack_KbSpecialNMs,
    /* 26 */ StatsAttack_KbSpecialNZd,
    /* 27 */ StatsAttack_KbSpecialNCl,
    /* 28 */ StatsAttack_KbSpecialNDr,
    /* 29 */ StatsAttack_KbSpecialNFc,
    /* 2A */ StatsAttack_KbSpecialNPc,
    /* 2B */ StatsAttack_KbSpecialNGw,
    /* 2C */ StatsAttack_KbSpecialNGn,
    /* 2D */ StatsAttack_KbSpecialNFe,
    /* 2E */ StatsAttack_KbSpecialNGk,
    /* 2F */ StatsAttack_47,
    /* 30 */ StatsAttack_48,
    /* 31 */ StatsAttack_DownAttackU,
    /* 32 */ StatsAttack_DownAttackD,
    /* 33 */ StatsAttack_Catch,
    /* 34 */ StatsAttack_CatchAttack,
    /* 35 */ StatsAttack_ThrowF,
    /* 36 */ StatsAttack_ThrowB,
    /* 37 */ StatsAttack_ThrowHi,
    /* 38 */ StatsAttack_ThrowLw,
    /* 39 */ StatsAttack_CargoThrowF,
    /* 3A */ StatsAttack_CargoThrowB,
    /* 3B */ StatsAttack_CargoThrowHi,
    /* 3C */ StatsAttack_CargoThrowLw,
    /* 3D */ StatsAttack_61,
    /* 3E */ StatsAttack_LedgeAttackSlow,
    /* 3F */ StatsAttack_LedgeAttackQuick,
    /* 40 */ StatsAttack_SwordSwing1,
    /* 41 */ StatsAttack_SwordSwing3,
    /* 42 */ StatsAttack_SwordSwing4,
    /* 43 */ StatsAttack_SwordSwingDash,
    /* 44 */ StatsAttack_BatSwing1,
    /* 45 */ StatsAttack_BatSwing3,
    /* 46 */ StatsAttack_BatSwing4,
    /* 47 */ StatsAttack_BatSwingDash,
    /* 48 */ StatsAttack_ParasolSwing1,
    /* 49 */ StatsAttack_ParasolSwing3,
    /* 4A */ StatsAttack_ParasolSwing4,
    /* 4B */ StatsAttack_ParasolSwingDash,
    /* 4C */ StatsAttack_HarisenSwing1,
    /* 4D */ StatsAttack_HarisenSwing3,
    /* 4E */ StatsAttack_HarisenSwing4,
    /* 4F */ StatsAttack_HarisenSwingDash,
    /* 50 */ StatsAttack_StarRodSwing1,
    /* 51 */ StatsAttack_StarRodSwing3,
    /* 52 */ StatsAttack_StarRodSwing4,
    /* 53 */ StatsAttack_StarRodSwingDash,
    /* 54 */ StatsAttack_LipstickSwing1,
    /* 55 */ StatsAttack_LipstickSwing3,
    /* 56 */ StatsAttack_LipstickSwing4,
    /* 57 */ StatsAttack_LipstickSwingDash,
    /* 58 */ StatsAttack_Parasol,
    /* 59 */ StatsAttack_LGun, ///< ray gun
    /* 5A */ StatsAttack_FireFlowerShoot,
    /* 5B */ StatsAttack_Screw,
    /* 5C */ StatsAttack_ScopeRapid,
    /* 5D */ StatsAttack_ScopeFire,
    /* 5E */ StatsAttack_Hammer,
    /* 5F */ StatsAttack_WarpStarFall, ///< on fall
    /* 60 */ StatsAttack_Pokeball,     ///< on open
    /* 61 */ StatsAttack_MSBomb,       ///< on explode
    /* 62 */ StatsAttack_ItemThrow,
    /* 63 */ StatsAttack_99,
    /* 64 */ StatsAttack_Count,
} plStats_Attack;

#endif
