#ifndef MELEE_FT_FT_08A4_H
#define MELEE_FT_FT_08A4_H

#include <platform.h>
#include "ft/forward.h"
#include "ftCommon/forward.h"

#include <placeholder.h>

/* 096250 */ void ftCo_80096250(ftCo_GObj* gobj);
/* 096498 */ void ftCo_80096498(ftCo_GObj* gobj);
/* 0970E0 */ bool ftCo_800970E0(ftCo_GObj* gobj);
/* 097130 */ void ftCo_80097130(ftCo_GObj* gobj);
/* 0974C4 */ void ftCo_800974C4(ftCo_GObj* gobj);
/* 09794C */ void ftCo_8009794C(ftCo_GObj* gobj);
/* 097AF4 */ void ftCo_80097AF4(ftCo_GObj* gobj);
/* 098400 */ bool ftCo_80098400(ftCo_GObj* gobj);
/* 098D90 */ void ftCo_80098D90(ftCo_GObj* gobj);
/* 09BB64 */ /* static */ void ftCo_8009BB64(ftCo_GObj* gobj);
/* 09DD94 */ /* static */ UNK_RET ftCo_8009DD94(UNK_PARAMS);
/* 09E1D4 */ /* static */ UNK_RET ftCo_8009E1D4(UNK_PARAMS);
/* 09E4A8 */ /* static */ UNK_RET ftCo_8009E4A8(UNK_PARAMS);
/* 09E614 */ /* static */ UNK_RET ftCo_8009E614(UNK_PARAMS);
/* 09F75C */ UNK_RET ftCo_8009F75C(UNK_PARAMS);
/* 0B462C */ /* static */ UNK_RET ftCo_800B462C(UNK_PARAMS);
/* 0B46B8 */ /* static */ UNK_RET ftCo_800B46B8(UNK_PARAMS);
/* 0B4778 */ /* static */ UNK_RET ftCo_800B4778(UNK_PARAMS);
/* 0B4880 */ /* static */ UNK_RET ftCo_800B4880(UNK_PARAMS);
/* 0B49F4 */ /* static */ UNK_RET ftCo_800B49F4(UNK_PARAMS);
/* 0B4A78 */ /* static */ UNK_RET ftCo_800B4A78(UNK_PARAMS);
/* 0B4AB0 */ /* static */ UNK_RET ftCo_800B4AB0(UNK_PARAMS);
/* 0B52AC */ /* static */ UNK_RET ftCo_800B52AC(UNK_PARAMS);
/* 0B5AB0 */ /* static */ UNK_RET ftCo_800B5AB0(UNK_PARAMS);
/* 0B6208 */ /* static */ UNK_RET ftCo_800B6208(UNK_PARAMS);
/* 0B630C */ /* static */ UNK_RET ftCo_800B630C(UNK_PARAMS);
/* 0B63D8 */ /* static */ UNK_RET ftCo_800B63D8(UNK_PARAMS);
/* 0B658C */ /* static */ UNK_RET ftCo_800B658C(UNK_PARAMS);
/* 0B683C */ /* static */ UNK_RET ftCo_800B683C(UNK_PARAMS);
/* 0B7180 */ /* static */ UNK_RET ftCo_800B7180(UNK_PARAMS);
/* 0B732C */ /* static */ UNK_RET ftCo_800B732C(UNK_PARAMS);
/* 0B7638 */ /* static */ UNK_RET ftCo_800B7638(UNK_PARAMS);
/* 0B77E8 */ /* static */ UNK_RET ftCo_800B77E8(UNK_PARAMS);
/* 0B885C */ /* static */ UNK_RET ftCo_800B885C(UNK_PARAMS);
/* 0B89CC */ /* static */ UNK_RET ftCo_800B89CC(UNK_PARAMS);
/* 0B8A9C */ /* static */ UNK_RET ftCo_800B8A9C(UNK_PARAMS);
/* 0B9020 */ /* static */ UNK_RET ftCo_800B9020(UNK_PARAMS);
/* 0B920C */ /* static */ UNK_RET ftCo_800B920C(UNK_PARAMS);
/* 0B92D4 */ /* static */ UNK_RET ftCo_800B92D4(UNK_PARAMS);
/* 0B9340 */ /* static */ UNK_RET ftCo_800B9340(UNK_PARAMS);
/* 0B9504 */ /* static */ UNK_RET ftCo_800B9504(UNK_PARAMS);
/* 0B9704 */ /* static */ UNK_RET ftCo_800B9704(UNK_PARAMS);
/* 0B9790 */ /* static */ UNK_RET ftCo_800B9790(UNK_PARAMS);
/* 0B98C8 */ /* static */ UNK_RET ftCo_800B98C8(UNK_PARAMS);
/* 0B9A04 */ /* static */ UNK_RET ftCo_800B9A04(UNK_PARAMS);
/* 0B9CBC */ /* static */ UNK_RET ftCo_800B9CBC(UNK_PARAMS);
/* 0B9F6C */ /* static */ UNK_RET ftCo_800B9F6C(UNK_PARAMS);
/* 0B9F90 */ /* static */ UNK_RET ftCo_800B9F90(UNK_PARAMS);
/* 0BA080 */ /* static */ UNK_RET ftCo_800BA080(UNK_PARAMS);
/* 0BA160 */ /* static */ UNK_RET ftCo_800BA160(UNK_PARAMS);
/* 0BA224 */ /* static */ UNK_RET ftCo_800BA224(UNK_PARAMS);
/* 0BA2E8 */ /* static */ UNK_RET ftCo_800BA2E8(UNK_PARAMS);
/* 0BA674 */ /* static */ UNK_RET ftCo_800BA674(UNK_PARAMS);
/* 0BA9A0 */ /* static */ UNK_RET ftCo_800BA9A0(UNK_PARAMS);
/* 0BB104 */ /* static */ UNK_RET ftCo_800BB104(UNK_PARAMS);
/* 0BB220 */ /* static */ UNK_RET ftCo_800BB220(UNK_PARAMS);
/* 0BB768 */ /* static */ UNK_RET ftCo_800BB768(UNK_PARAMS);
/* 0BB9B4 */ /* static */ UNK_RET ftCo_800BB9B4(UNK_PARAMS);
/* 0C0658 */ /* static */ UNK_RET ftCo_800C0658(UNK_PARAMS);
/* 0C0874 */ UNK_RET ftCo_800C0874(UNK_PARAMS);
/* 0C0A28 */ UNK_RET ftCo_800C0A28(UNK_PARAMS);
/* 0C0C88 */ bool ftCo_800C0C88(int);
/* 0C0CB8 */ bool ftCo_800C0CB8(ftCo_GObj* gobj);
/* 0C0D0C */ UNK_RET ftCo_800C0D0C(UNK_PARAMS);
/* 0C124C */ UNK_RET ftCo_800C124C(UNK_PARAMS);
/* 0C13BC */ UNK_RET ftCo_800C13BC(UNK_PARAMS);
/* 0C15F4 */ UNK_RET ftCo_800C15F4(UNK_PARAMS);
/* 0C1718 */ UNK_RET ftCo_800C1718(UNK_PARAMS);
/* 0C17CC */ bool ftCo_800C17CC(ftCo_GObj* gobj);
/* 0C18A8 */ UNK_RET ftCo_800C18A8(UNK_PARAMS);
/* 0C1D38 */ bool ftCo_800C1D38(ftCo_GObj* gobj);
/* 0C1E0C */ UNK_RET ftCo_800C1E0C(UNK_PARAMS);
/* 0C23A0 */ bool ftCo_800C23A0(ftCo_GObj* gobj);
/* 0C23FC */ UNK_RET ftCo_800C23FC(UNK_PARAMS);
/* 0C27B4 */ UNK_RET ftCo_800C27B4(UNK_PARAMS);
/* 0C27C0 */ UNK_RET ftCo_800C27C0(UNK_PARAMS);
/* 0C27C8 */ UNK_RET ftCo_800C27C8(UNK_PARAMS);
/* 0C30C0 */ UNK_RET ftCo_800C30C0(UNK_PARAMS);
/* 0C318C */ void ftCo_800C318C(ftCo_GObj* gobj, bool);
/* 0C3390 */ UNK_RET ftCo_800C3390(UNK_PARAMS);
/* 0C3480 */ UNK_RET ftCo_800C3480(UNK_PARAMS);
/* 0C3538 */ bool ftCo_800C3538(ftCo_GObj* gobj);
/* 0C3598 */ void ftCo_800C3598(ftCo_GObj* gobj);
/* 0C36DC */ void ftCo_800C36DC(ftCo_GObj* gobj);
/* 0C3B10 */ bool ftCo_800C3B10(ftCo_GObj* gobj);
/* 0C3BE8 */ UNK_RET ftCo_800C3BE8(UNK_PARAMS);
/* 0C44CC */ bool ftCo_800C44CC(ftCo_GObj* gobj);
/* 0C4550 */ UNK_RET ftCo_800C4550(UNK_PARAMS);
/* 0C4724 */ void ftCo_800C4724(ftCo_GObj* gobj);
/* 0C4A38 */ UNK_RET ftCo_800C4A38(UNK_PARAMS);
/* 0C4E4C */ UNK_RET ftCo_800C4E4C(UNK_PARAMS);
/* 0C4E94 */ UNK_RET ftCo_800C4E94(UNK_PARAMS);
/* 0C4F64 */ UNK_RET ftCo_800C4F64(UNK_PARAMS);
/* 0C5284 */ void ftCo_800C5284(ftCo_GObj* gobj);
/* 0C52F4 */ void ftCo_800C52F4(ftCo_GObj* gobj);
/* 0C53E4 */ UNK_RET ftCo_800C53E4(UNK_PARAMS);
/* 0C5408 */ UNK_RET ftCo_800C5408(UNK_PARAMS);
/* 0C544C */ UNK_RET ftCo_800C544C(UNK_PARAMS);
/* 0C548C */ UNK_RET ftCo_800C548C(UNK_PARAMS);
/* 0C54C4 */ UNK_RET ftCo_800C54C4(UNK_PARAMS);
/* 0C554C */ void ftCo_800C554C(ftCo_Fighter* fp);
/* 0C5588 */ UNK_RET ftCo_800C5588(UNK_PARAMS);
/* 0C55CC */ UNK_RET ftCo_800C55CC(UNK_PARAMS);
/* 0C5614 */ UNK_RET ftCo_800C5614(UNK_PARAMS);
/* 0C576C */ UNK_RET ftCo_800C576C(UNK_PARAMS);
/* 0C57B4 */ UNK_RET ftCo_800C57B4(UNK_PARAMS);
/* 0C5A50 */ UNK_RET ftCo_800C5A50(UNK_PARAMS);
/* 0C5A98 */ void ftCo_800C5A98(ftCo_GObj* gobj);
/* 0C5B88 */ UNK_RET ftCo_800C5B88(UNK_PARAMS);
/* 0C5CD4 */ bool ftCo_800C5CD4(ftCo_GObj* gobj);
/* 0C5D34 */ UNK_RET ftCo_800C5D34(UNK_PARAMS);
/* 0C5DDC */ bool ftCo_800C5DDC(ftCo_GObj* gobj);
/* 0C5F88 */ UNK_RET ftCo_800C5F88(UNK_PARAMS);
/* 0C60C8 */ bool ftCo_800C60C8(ftCo_GObj* gobj);
/* 0C6110 */ UNK_RET ftCo_800C6110(UNK_PARAMS);
/* 0C6150 */ UNK_RET ftCo_800C6150(UNK_PARAMS);
/* 0C6408 */ UNK_RET ftCo_800C6408(UNK_PARAMS);
/* 0C6B6C */ UNK_RET ftCo_800C6B6C(UNK_PARAMS);
/* 0C7070 */ UNK_RET ftCo_800C7070(UNK_PARAMS);
/* 0C70D0 */ UNK_RET ftCo_800C70D0(UNK_PARAMS);
/* 0C7178 */ UNK_RET ftCo_800C7178(UNK_PARAMS);
/* 0C7220 */ UNK_RET ftCo_800C7220(UNK_PARAMS);
/* 0C7294 */ UNK_RET ftCo_800C7294(UNK_PARAMS);
/* 0C7308 */ UNK_RET ftCo_800C7308(UNK_PARAMS);
/* 0C739C */ UNK_RET ftCo_800C739C(UNK_PARAMS);
/* 0C7434 */ UNK_RET ftCo_800C7434(UNK_PARAMS);
/* 0C74F4 */ bool ftCo_800C74F4(ftCo_GObj* gobj);
/* 0C7590 */ UNK_RET ftCo_800C7590(UNK_PARAMS);
/* 0C7A30 */ UNK_RET ftCo_800C7A30(UNK_PARAMS);
/* 0C7CA0 */ bool ftCo_800C7CA0(ftCo_GObj* gobj);
/* 0C88D4 */ void ftCo_800C88D4(ftCo_GObj* gobj, int, bool);
/* 0C8B60 */ void ftCo_800C8B60(ftCo_Fighter* fp, int, s8);
/* 0C8B74 */ void ftCo_800C8B74(void);
/* 0C94B4 */ bool ftCo_800C94B4(ftCo_GObj* gobj);
/* 0CB024 */ bool ftCo_800CB024(ftCo_GObj* gobj);
/* 0CB8E0 */ bool ftCo_800CB8E0(ftCo_GObj* gobj);
/* 0CB950 */ UNK_RET ftCo_800CB950(UNK_PARAMS);
/* 0CBAC4 */ UNK_RET ftCo_800CBAC4(UNK_PARAMS);
/* 0CBBC0 */ UNK_RET ftCo_800CBBC0(UNK_PARAMS);
/* 0CBD18 */ UNK_RET ftCo_800CBD18(UNK_PARAMS);
/* 0CBE98 */ UNK_RET ftCo_800CBE98(UNK_PARAMS);
/* 0CC0E8 */ UNK_RET ftCo_800CC0E8(UNK_PARAMS);
/* 0CC238 */ UNK_RET ftCo_800CC238(UNK_PARAMS);
/* 0CC830 */ void ftCo_800CC830(ftCo_GObj* gobj);
/* 0CC988 */ void ftCo_800CC988(ftCo_GObj* gobj, float);
/* 0CCBE0 */ void ftCo_800CCBE0(ftCo_GObj* gobj, float*, FtMotionId,
                                FtMotionId, FtMotionId);
/* 0CD140 */ UNK_RET ftCo_800CD140(UNK_PARAMS);
/* 0CD1BC */ UNK_RET ftCo_800CD1BC(UNK_PARAMS);
/* 0CD204 */ UNK_RET ftCo_800CD204(UNK_PARAMS);
/* 0CD278 */ UNK_RET ftCo_800CD278(UNK_PARAMS);
/* 0CD2C4 */ UNK_RET ftCo_800CD2C4(UNK_PARAMS);
/* 0CD350 */ UNK_RET ftCo_800CD350(UNK_PARAMS);
/* 0CD418 */ UNK_RET ftCo_800CD418(UNK_PARAMS);
/* 0CD4E0 */ UNK_RET ftCo_800CD4E0(UNK_PARAMS);
/* 0CD5A8 */ UNK_RET ftCo_800CD5A8(UNK_PARAMS);
/* 0CD82C */ UNK_RET ftCo_800CD82C(UNK_PARAMS);
/* 0CDAB4 */ UNK_RET ftCo_800CDAB4(UNK_PARAMS);
/* 0CDE18 */ UNK_RET ftCo_800CDE18(UNK_PARAMS);
/* 0CDE54 */ UNK_RET ftCo_800CDE54(UNK_PARAMS);
/* 0CDE74 */ UNK_RET ftCo_800CDE74(UNK_PARAMS);
/* 0CDE94 */ UNK_RET ftCo_800CDE94(UNK_PARAMS);
/* 0CDF5C */ UNK_RET ftCo_800CDF5C(UNK_PARAMS);
/* 0CE010 */ UNK_RET ftCo_800CE010(UNK_PARAMS);
/* 0CE3E0 */ UNK_RET ftCo_800CE3E0(UNK_PARAMS);
/* 0CE480 */ UNK_RET ftCo_800CE480(UNK_PARAMS);
/* 0CECE8 */ bool ftCo_800CECE8(ftCo_GObj* gobj);
/* 0CED30 */ UNK_RET ftCo_800CED30(UNK_PARAMS);
/* 0CEE70 */ bool ftCo_800CEE70(ftCo_GObj* gobj);
/* 0CF138 */ float ftCo_CalcYScaledKnockback(float*, float, float, float);
/* 0CF3C8 */ UNK_RET ftCo_800CF3C8(UNK_PARAMS);
/* 0CF4DC */ void ftCo_800CF4DC(ftCo_GObj* gobj);
/* 0CF6E8 */ UNK_RET ftCo_800CF6E8(UNK_PARAMS);
/* 0D0CBC */ UNK_RET ftCo_800D0CBC(UNK_PARAMS);
/* 0D15D0 */ UNK_RET ftCo_800D15D0(UNK_PARAMS);
/* 0D170C */ UNK_RET ftCo_800D170C(UNK_PARAMS);
/* 0D18CC */ UNK_RET ftCo_800D18CC(UNK_PARAMS);
/* 0D1B04 */ UNK_RET ftCo_800D1B04(UNK_PARAMS);
/* 0D1BA0 */ UNK_RET ftCo_800D1BA0(UNK_PARAMS);
/* 0D1D10 */ UNK_RET ftCo_800D1D10(UNK_PARAMS);
/* 0D1F6C */ UNK_RET ftCo_800D1F6C(UNK_PARAMS);
/* 0D1FFC */ UNK_RET ftCo_800D1FFC(UNK_PARAMS);
/* 0D21BC */ UNK_RET ftCo_800D21BC(UNK_PARAMS);
/* 0D23F4 */ UNK_RET ftCo_800D23F4(UNK_PARAMS);
/* 0D2490 */ UNK_RET ftCo_800D2490(UNK_PARAMS);
/* 0D2600 */ UNK_RET ftCo_800D2600(UNK_PARAMS);
/* 0D2770 */ UNK_RET ftCo_800D2770(UNK_PARAMS);
/* 0D27C4 */ UNK_RET ftCo_800D27C4(UNK_PARAMS);
/* 0D2FA4 */ bool ftCo_800D2FA4(ftCo_GObj* gobj);
/* 0D3004 */ UNK_RET ftCo_800D3004(UNK_PARAMS);
/* 0D331C */ UNK_RET ftCo_800D331C(UNK_PARAMS);
/* 0D34E0 */ UNK_RET ftCo_800D34E0(UNK_PARAMS);
/* 0D35FC */ UNK_RET ftCo_800D35FC(UNK_PARAMS);
/* 0D3680 */ UNK_RET ftCo_800D3680(UNK_PARAMS);
/* 0D38B8 */ UNK_RET ftCo_800D38B8(UNK_PARAMS);
/* 0D3950 */ UNK_RET ftCo_800D3950(UNK_PARAMS);
/* 0D3E40 */ UNK_RET ftCo_800D3E40(UNK_PARAMS);
/* 0D40B8 */ UNK_RET ftCo_800D40B8(UNK_PARAMS);
/* 0D41C4 */ UNK_RET ftCo_800D41C4(UNK_PARAMS);
/* 0D4580 */ UNK_RET ftCo_800D4580(UNK_PARAMS);
/* 0D4780 */ UNK_RET ftCo_800D4780(UNK_PARAMS);
/* 0D47B8 */ UNK_RET ftCo_800D47B8(UNK_PARAMS);
/* 0D481C */ UNK_RET ftCo_800D481C(UNK_PARAMS);
/* 0D4E50 */ UNK_RET ftCo_800D4E50(UNK_PARAMS);
/* 0D5600 */ UNK_RET ftCo_800D5600(UNK_PARAMS);
/* 0D5B70 */ UNK_RET ftCo_800D5B70(UNK_PARAMS);
/* 0D5B80 */ UNK_RET ftCo_800D5B80(UNK_PARAMS);
/* 0D5B9C */ UNK_RET ftCo_800D5B9C(UNK_PARAMS);
/* 0D5FB0 */ bool ftCo_800D5FB0(ftCo_GObj* gobj);
/* 0D69C4 */ bool ftCo_800D69C4(ftCo_GObj* gobj);
/* 0D705C */ bool ftCo_800D705C(ftCo_GObj* gobj);
/* 0D7100 */ bool ftCo_800D7100(ftCo_GObj* gobj);
/* 0D8A38 */ UNK_RET ftCo_800D8A38(UNK_PARAMS);
/* 0D8AE0 */ bool ftCo_800D8AE0(void);
/* 0D8B9C */ bool ftCo_800D8B9C(ftCo_GObj* gobj);
/* 0D8C54 */ UNK_RET ftCo_800D8C54(UNK_PARAMS);
/* 0DC3A4 */ void ftCo_800DC3A4(ftCo_GObj* gobj);
/* 0DCE34 */ void ftCo_800DCE34(ftCo_GObj* gobj0, ftCo_GObj* gobj1);
/* 0DCFD4 */ void ftCo_800DCFD4(ftCo_GObj* gobj);
/* 0DD100 */ UNK_RET ftCo_800DD100(UNK_PARAMS);
/* 0DD1E4 */ UNK_RET ftCo_800DD1E4(UNK_PARAMS);
/* 0DD398 */ UNK_RET ftCo_800DD398(UNK_PARAMS);
/* 0DD4B0 */ UNK_RET ftCo_800DD4B0(UNK_PARAMS);
/* 0DD724 */ void ftCo_800DD724(ftCo_GObj* gobj);
/* 0DDDE4 */ UNK_RET ftCo_800DDDE4(UNK_PARAMS);
/* 0DE2F0 */ void ftCo_800DE2F0(ftCo_GObj* gobj);
/* 0DE3FC */ bool ftCo_800DE3FC(ftCo_GObj* gobj, FtMotionId msid, float arg2);
/* 0DE5A4 */ UNK_RET ftCo_800DE5A4(UNK_PARAMS);
/* 0DE854 */ void ftCo_800DE854(ftCo_GObj* gobj);
/* 0DE920 */ UNK_RET ftCo_800DE920(UNK_PARAMS);
/* 0DE974 */ UNK_RET ftCo_800DE974(UNK_PARAMS);
/* 0DE9B8 */ UNK_RET ftCo_800DE9B8(UNK_PARAMS);
/* 0DE9D8 */ bool ftCo_800DE9D8(ftCo_GObj* gobj);
/* 0DEA28 */ UNK_RET ftCo_800DEA28(UNK_PARAMS);
/* 0DEBD0 */ UNK_RET ftCo_800DEBD0(UNK_PARAMS);
/* 0DEE84 */ void ftCo_800DEE84(int, u8, char*, u32, float, float);
/* 0DF1C8 */ bool ftCo_800DF1C8(ftCo_Fighter* fp);
/* 0DF2D8 */ bool ftCo_800DF2D8(ftCo_Fighter* fp);
/* 0DF30C */ bool ftCo_800DF30C(ftCo_Fighter* fp);
/* 0DF3A8 */ bool ftCo_800DF3A8(ftCo_Fighter* fp);
/* 0DF3DC */ bool ftCo_800DF3DC(ftCo_Fighter* fp);
/* 0DF50C */ bool ftCo_800DF50C(ftCo_Fighter* fp);
/* 0DF608 */ bool ftCo_800DF608(ftCo_Fighter* fp);
/* 0DF644 */ bool ftCo_800DF644(ftCo_Fighter* fp);
/* 0DF678 */ bool ftCo_800DF678(Fighter* fp);
/* 0DF6F8 */ bool ftCo_800DF6F8(ftCo_Fighter* fp);
/* 0DF72C */ bool ftCo_800DF72C(ftCo_Fighter* fp);
/* 0DF79C */ bool ftCo_800DF79C(ftCo_Fighter* fp);
/* 0DF7F4 */ UNK_RET ftCo_800DF7F4(UNK_PARAMS);
/* 0DF844 */ UNK_RET ftCo_800DF844(UNK_PARAMS);
/* 0DF878 */ UNK_RET ftCo_800DF878(UNK_PARAMS);
/* 0DF8B0 */ bool ftCo_800DF8B0(ftCo_Fighter* fp);
/* 0DF8E8 */ bool ftCo_800DF8E8(ftCo_Fighter* fp);
/* 0DF910 */ UNK_RET ftCo_800DF910(UNK_PARAMS);
/* 459A68 */ extern UNK_T ft_80459A68;
/* 459A74 */ extern UNK_T ft_80459A74;
/* 459A8C */ extern UNK_T ft_80459A8C;
/* 4D6570 */ extern UNK_T ft_804D6570;
/* 4D6574 */ extern UNK_T ft_804D6574;
/* 4D6578 */ extern UNK_T ft_804D6578;
bool ftCo_800BFFD0(Fighter*, int, int);
bool ftCo_800C0694(Fighter*);
bool ftCo_800C5240(ftCo_GObj* gobj);
bool ftCo_800C8B2C(Fighter*, bool, bool);
bool ftCo_800C97A8(ftCo_GObj* gobj);
bool ftCo_800CAE80(ftCo_GObj* gobj);
bool ftCo_800CB870(ftCo_GObj* gobj);
bool ftCo_800D6824(ftCo_GObj* gobj);
bool ftCo_800D68C0(ftCo_GObj* gobj);
bool ftCo_800DF478(Fighter*);
bool ftCo_Attack100_CheckInput(ftCo_GObj* gobj);
bool ftCo_AttackLw4_CheckInput(ftCo_GObj* gobj);
bool ftCo_Catch_CheckInput(ftCo_GObj* gobj);
bool ftCo_Dash_CheckInput(ftCo_GObj* gobj);
bool ftCo_Jump_CheckInput(ftCo_GObj* gobj);
bool ftCo_Squat_CheckInput(ftCo_GObj* gobj);
bool ftCo_Turn_CheckInput(ftCo_GObj* gobj);
bool ftCo_Walk_CheckInput(ftCo_GObj* gobj);
f32 ftCo_800DA824(Fighter*);
float ftCo_800D0EC8(Fighter* fp);
ftCo_GObj* ftCo_800BE7E0(unk_t);
s32 ftCo_800D67C4(Fighter*);
s32 ftCo_800D688C(Fighter*);
s32 ftCo_800D6928(Fighter*);
u32 ftCo_800DEEE8(Fighter*, Vec2*);
UNK_RET ftCo_800C8D00(ftCo_GObj* gobj);
UNK_RET ftCo_800CC6C8(UNK_PARAMS);
unk_t ftCo_800C703C(void);
void ftCo_800928CC(ftCo_GObj* gobj);
void ftCo_80092BCC(ftCo_GObj* gobj);
void ftCo_80092BE8(ftCo_GObj* gobj);
void ftCo_80093BC0(ftCo_GObj* gobj);
void ftCo_8009750C(ftCo_GObj* gobj);
void ftCo_800BCF18(ftCo_GObj*, ftCo_GObj* gobj);
void ftCo_800BD000(ftCo_GObj*, ftCo_GObj* gobj);
void ftCo_800BEB60(int, int, int);
void ftCo_800BED84(ftCo_GObj* gobj);
void ftCo_800BEF00(ftCo_GObj* gobj);
void ftCo_800BEFD0(ftCo_GObj* gobj);
void ftCo_800BFB4C(ftCo_GObj*, s32*);
void ftCo_800BFD04(ftCo_GObj* gobj);
void ftCo_800BFFAC(Fighter*);
void ftCo_800C0074(Fighter*);
void ftCo_800C0134(Fighter*);
void ftCo_800C0200(Fighter*, int);
void ftCo_800C0358(Fighter*, Fighter*, s32);
void ftCo_800C0408(ftCo_GObj* gobj);
void ftCo_800C06C0(void);
void ftCo_800C09B4(ftCo_GObj* gobj);
void ftCo_800C0A98(ftCo_GObj* gobj);
void ftCo_800C1E64(ftCo_GObj* pPlayerEntityStruct, s32, s32, u8, f32);
void ftCo_800C2FD8(ftCo_GObj* gobj);
void ftCo_800C37A0(ftCo_GObj* gobj);
void ftCo_800C511C(ftCo_GObj* gobj);
void ftCo_800C5500(ftCo_GObj* gobj);
void ftCo_800C555C(ftCo_GObj* gobj);
void ftCo_800C61B0(ftCo_GObj* gobj);
void ftCo_800C7158(ftCo_GObj* gobj);
void ftCo_800C7200(ftCo_GObj* gobj);
void ftCo_800C737C(ftCo_GObj* gobj);
void ftCo_800C7414(ftCo_GObj* gobj);
void ftCo_800C74AC(ftCo_GObj* gobj);
void ftCo_800C8064(void);
void ftCo_800C8348(ftCo_GObj*, s32, s32);
void ftCo_800C8438(ftCo_GObj* gobj);
void ftCo_800C8540(ftCo_GObj* gobj);
void ftCo_800C884C(ftCo_GObj* gobj);
void ftCo_800C88A0(Fighter*);
void ftCo_800C89A0(ftCo_GObj* gobj);
void ftCo_800C8A64(ftCo_GObj* gobj);
void ftCo_800C8C84(ftCo_GObj* gobj);
void ftCo_800C8F6C(void);
void ftCo_800C8FC4(ftCo_GObj* gobj);
void ftCo_800C9034(ftCo_GObj* gobj);
void ftCo_800C9840(ftCo_GObj*, s32, s32, f32, f32, f32);
void ftCo_800C9924(ftCo_GObj* gobj);
void ftCo_800CB110(ftCo_GObj*, s32, f32);
void ftCo_800CB438(ftCo_GObj* gobj);
void ftCo_800CB59C(ftCo_GObj* gobj);
void ftCo_800CC730(ftCo_GObj* gobj);
void ftCo_800CCAAC(ftCo_GObj* gobj);
void ftCo_800CCDA8(ftCo_GObj* gobj);
void ftCo_800CDDA0(ftCo_GObj* gobj);
void ftCo_800CEFE0(ftCo_GObj* gobj, int);
void ftCo_800D0FA0(ftCo_GObj* gobj);
void ftCo_800D105C(ftCo_GObj* gobj);
void ftCo_800D14E4(ftCo_GObj* gobj);
void ftCo_800D1A8C(ftCo_GObj* gobj);
void ftCo_800D1E80(ftCo_GObj* gobj);
void ftCo_800D237C(ftCo_GObj* gobj);
void ftCo_800D3158(ftCo_GObj* gobj);
void ftCo_800D4F24(ftCo_GObj*, s32);
void ftCo_800D4FF4(ftCo_GObj* gobj);
void ftCo_800D5AEC(ftCo_GObj*, s32, s32, s32, f32, f32);
void ftCo_800D5BF8(ftCo_GObj* gobj);
void ftCo_800D5CB0(ftCo_GObj*, bool, float landing_lag);
void ftCo_800D638C(ftCo_GObj* gobj);
void ftCo_800D6B00(ftCo_GObj*, s32);
void ftCo_800D6C60(ftCo_GObj*, HSD_GObjEvent callback);
void ftCo_800D71D8(ftCo_GObj* gobj);
void ftCo_800D94D8(ftCo_GObj* gobj);
void ftCo_800D9C98(ftCo_GObj* gobj);
void ftCo_800DB368(Fighter*, Fighter*);
void ftCo_800DB464(ftCo_GObj* gobj);
void ftCo_800DC750(ftCo_GObj* gobj);
void ftCo_800DC920(ftCo_GObj*, ftCo_GObj* gobj);
void ftCo_800DD168(ftCo_GObj* gobj);
void ftCo_800DE2A8(ftCo_GObj*, ftCo_GObj* gobj);
void ftCo_800DE508(ftCo_GObj* gobj);
void ftCo_800DE7C0(ftCo_GObj*, s32, s32);
void ftCo_800DEAE8(ftCo_GObj* gobj, enum_t asid0, enum_t asid1);
void ftCo_800DEEA8(ftCo_GObj* gobj);
void ftCo_800DEEB8(void);
void ftCo_800DEF38(ftCo_GObj* gobj);
void ftCo_800DF0D0(ftCo_GObj* gobj);
void ftCo_AirCatch_Anim(ftCo_GObj* gobj);
void ftCo_AirCatch_Coll(ftCo_GObj* gobj);
void ftCo_AirCatchHit_Anim(ftCo_GObj* gobj);
void ftCo_AirCatchHit_IASA(ftCo_GObj* gobj);
void ftCo_AirCatchHit_Phys(ftCo_GObj* gobj);
void ftCo_AirCatch_IASA(ftCo_GObj* gobj);
void ftCo_AirCatch_Phys(ftCo_GObj* gobj);
void ftCo_AppealS_Anim(ftCo_GObj* gobj);
void ftCo_AppealS_Coll(ftCo_GObj* gobj);
void ftCo_AppealS_IASA(ftCo_GObj* gobj);
void ftCo_AppealS_Phys(ftCo_GObj* gobj);
void ftCo_Attack100End_Anim(ftCo_GObj* gobj);
void ftCo_Attack100End_Coll(ftCo_GObj* gobj);
void ftCo_Attack100End_Phys(ftCo_GObj* gobj);
void ftCo_Attack100Loop_Anim(ftCo_GObj* gobj);
void ftCo_Attack100Loop_Coll(ftCo_GObj* gobj);
void ftCo_Attack100Loop_IASA(ftCo_GObj* gobj);
void ftCo_Attack100Loop_Phys(ftCo_GObj* gobj);
void ftCo_Attack100Start_Anim(ftCo_GObj* gobj);
void ftCo_Attack100Start_Coll(ftCo_GObj* gobj);
void ftCo_Attack100Start_Phys(ftCo_GObj* gobj);
void ftCo_AttackS42_Anim(ftCo_GObj* gobj);
void ftCo_AttackS42_Coll(ftCo_GObj* gobj);
void ftCo_AttackS42_IASA(ftCo_GObj* gobj);
void ftCo_AttackS42_Phys(ftCo_GObj* gobj);
void ftCo_Barrel_Anim(ftCo_GObj* gobj);
void ftCo_Barrel_Coll(ftCo_GObj* gobj);
void ftCo_Barrel_IASA(ftCo_GObj* gobj);
void ftCo_Barrel_Phys(ftCo_GObj* gobj);
void ftCo_BarrelWait_Anim(ftCo_GObj* gobj);
void ftCo_BarrelWait_Coll(ftCo_GObj* gobj);
void ftCo_BarrelWait_IASA(ftCo_GObj* gobj);
void ftCo_BarrelWait_Phys(ftCo_GObj* gobj);
void ftCo_BatSwing_Anim(ftCo_GObj* gobj);
void ftCo_BatSwing_Coll(ftCo_GObj* gobj);
void ftCo_BatSwing_IASA(ftCo_GObj* gobj);
void ftCo_BatSwing_Phys(ftCo_GObj* gobj);
void ftCo_Bury_Anim(ftCo_GObj* gobj);
void ftCo_Bury_Coll(ftCo_GObj* gobj);
void ftCo_Bury_IASA(ftCo_GObj* gobj);
void ftCo_BuryJump_Anim(ftCo_GObj* gobj);
void ftCo_BuryJump_Coll(ftCo_GObj* gobj);
void ftCo_BuryJump_IASA(ftCo_GObj* gobj);
void ftCo_BuryJump_Phys(ftCo_GObj* gobj);
void ftCo_Bury_Phys(ftCo_GObj* gobj);
void ftCo_BuryWait_Anim(ftCo_GObj* gobj);
void ftCo_BuryWait_Coll(ftCo_GObj* gobj);
void ftCo_BuryWait_IASA(ftCo_GObj* gobj);
void ftCo_BuryWait_Phys(ftCo_GObj* gobj);
void ftCo_CaptureCaptain_Anim(ftCo_GObj* gobj);
void ftCo_CaptureCaptain_Coll(ftCo_GObj* gobj);
void ftCo_CaptureCaptain_IASA(ftCo_GObj* gobj);
void ftCo_CaptureCaptain_Phys(ftCo_GObj* gobj);
void ftCo_CaptureCut_Anim(ftCo_GObj* gobj);
void ftCo_CaptureCut_Coll(ftCo_GObj* gobj);
void ftCo_CaptureCut_IASA(ftCo_GObj* gobj);
void ftCo_CaptureCut_Phys(ftCo_GObj* gobj);
void ftCo_CaptureDamageHi_Anim(ftCo_GObj* gobj);
void ftCo_CaptureDamageHi_Coll(ftCo_GObj* gobj);
void ftCo_CaptureDamageHi_IASA(ftCo_GObj* gobj);
void ftCo_CaptureDamageHi_Phys(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_Anim(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_Coll(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_IASA(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_Phys(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopa_Anim(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopa_Coll(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopa_IASA(ftCo_GObj* gobj);
void ftCo_CaptureDamageKoopa_Phys(ftCo_GObj* gobj);
void ftCo_CaptureDamageLw_Anim(ftCo_GObj* gobj);
void ftCo_CaptureDamageLw_Coll(ftCo_GObj* gobj);
void ftCo_CaptureDamageLw_IASA(ftCo_GObj* gobj);
void ftCo_CaptureDamageLw_Phys(ftCo_GObj* gobj);
void ftCo_CaptureJump_Anim(ftCo_GObj* gobj);
void ftCo_CaptureJump_Coll(ftCo_GObj* gobj);
void ftCo_CaptureJump_IASA(ftCo_GObj* gobj);
void ftCo_CaptureJump_Phys(ftCo_GObj* gobj);
void ftCo_CaptureKoopaAir_Anim(ftCo_GObj* gobj);
void ftCo_CaptureKoopaAir_Coll(ftCo_GObj* gobj);
void ftCo_CaptureKoopaAir_IASA(ftCo_GObj* gobj);
void ftCo_CaptureKoopaAir_Phys(ftCo_GObj* gobj);
void ftCo_CaptureKoopa_Anim(ftCo_GObj* gobj);
void ftCo_CaptureKoopa_Coll(ftCo_GObj* gobj);
void ftCo_CaptureKoopa_IASA(ftCo_GObj* gobj);
void ftCo_CaptureKoopa_Phys(ftCo_GObj* gobj);
void ftCo_CaptureLeadead_Anim(ftCo_GObj* gobj);
void ftCo_CaptureLeadead_Coll(ftCo_GObj* gobj);
void ftCo_CaptureLeadead_IASA(ftCo_GObj* gobj);
void ftCo_CaptureLeadead_Phys(ftCo_GObj* gobj);
void ftCo_CaptureLikelike_Anim(ftCo_GObj* gobj);
void ftCo_CaptureLikelike_Coll(ftCo_GObj* gobj);
void ftCo_CaptureLikelike_IASA(ftCo_GObj* gobj);
void ftCo_CaptureLikelike_Phys(ftCo_GObj* gobj);
void ftCo_CapturePulledHi_Anim(ftCo_GObj* gobj);
void ftCo_CapturePulledHi_Coll(ftCo_GObj* gobj);
void ftCo_CapturePulledHi_IASA(ftCo_GObj* gobj);
void ftCo_CapturePulledHi_Phys(ftCo_GObj* gobj);
void ftCo_CapturePulledLw_Anim(ftCo_GObj* gobj);
void ftCo_CapturePulledLw_Coll(ftCo_GObj* gobj);
void ftCo_CapturePulledLw_IASA(ftCo_GObj* gobj);
void ftCo_CapturePulledLw_Phys(ftCo_GObj* gobj);
void ftCo_CaptureWaitHi_Anim(ftCo_GObj* gobj);
void ftCo_CaptureWaitHi_Coll(ftCo_GObj* gobj);
void ftCo_CaptureWaitHi_IASA(ftCo_GObj* gobj);
void ftCo_CaptureWaitHi_Phys(ftCo_GObj* gobj);
void ftCo_CaptureWaitKirby_Anim(ftCo_GObj* gobj);
void ftCo_CaptureWaitKirby_Coll(ftCo_GObj* gobj);
void ftCo_CaptureWaitKirby_IASA(ftCo_GObj* gobj);
void ftCo_CaptureWaitKirby_Phys(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_Anim(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_Coll(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_IASA(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_Phys(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopa_Anim(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopa_Coll(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopa_IASA(ftCo_GObj* gobj);
void ftCo_CaptureWaitKoopa_Phys(ftCo_GObj* gobj);
void ftCo_CaptureWaitLw_Anim(ftCo_GObj* gobj);
void ftCo_CaptureWaitLw_Coll(ftCo_GObj* gobj);
void ftCo_CaptureWaitLw_IASA(ftCo_GObj* gobj);
void ftCo_CaptureWaitLw_Phys(ftCo_GObj* gobj);
void ftCo_CaptureYoshi_Anim(ftCo_GObj* gobj);
void ftCo_CaptureYoshi_Coll(ftCo_GObj* gobj);
void ftCo_CaptureYoshi_IASA(ftCo_GObj* gobj);
void ftCo_CaptureYoshi_Phys(ftCo_GObj* gobj);
void ftCo_CargoFall_Anim(ftCo_GObj* gobj);
void ftCo_CargoFall_Coll(ftCo_GObj* gobj);
void ftCo_CargoFall_IASA(ftCo_GObj* gobj);
void ftCo_CargoFall_Phys(ftCo_GObj* gobj);
void ftCo_CargoKneebend_Anim(ftCo_GObj* gobj);
void ftCo_CargoKneebend_Coll(ftCo_GObj* gobj);
void ftCo_CargoKneebend_IASA(ftCo_GObj* gobj);
void ftCo_CargoKneebend_Phys(ftCo_GObj* gobj);
void ftCo_CargoLanding_Anim(ftCo_GObj* gobj);
void ftCo_CargoLanding_Coll(ftCo_GObj* gobj);
void ftCo_CargoLanding_Phys(ftCo_GObj* gobj);
void ftCo_CargoThrowAir_Anim(ftCo_GObj* gobj);
void ftCo_CargoThrowAir_Coll(ftCo_GObj* gobj);
void ftCo_CargoThrowAir_IASA(ftCo_GObj* gobj);
void ftCo_CargoThrowAir_Phys(ftCo_GObj* gobj);
void ftCo_CargoThrowB_Anim(ftCo_GObj* gobj);
void ftCo_CargoThrowB_Coll(ftCo_GObj* gobj);
void ftCo_CargoThrowB_IASA(ftCo_GObj* gobj);
void ftCo_CargoThrowB_Phys(ftCo_GObj* gobj);
void ftCo_CargoThrowF_Anim(ftCo_GObj* gobj);
void ftCo_CargoThrowF_Coll(ftCo_GObj* gobj);
void ftCo_CargoThrowF_IASA(ftCo_GObj* gobj);
void ftCo_CargoThrowF_Phys(ftCo_GObj* gobj);
void ftCo_CargoThrowHi_Anim(ftCo_GObj* gobj);
void ftCo_CargoThrowHi_Coll(ftCo_GObj* gobj);
void ftCo_CargoThrowHi_IASA(ftCo_GObj* gobj);
void ftCo_CargoThrowHi_Phys(ftCo_GObj* gobj);
void ftCo_CargoThrowLw_Anim(ftCo_GObj* gobj);
void ftCo_CargoThrowLw_Coll(ftCo_GObj* gobj);
void ftCo_CargoThrowLw_IASA(ftCo_GObj* gobj);
void ftCo_CargoThrowLw_Phys(ftCo_GObj* gobj);
void ftCo_CargoTurn_Anim(ftCo_GObj* gobj);
void ftCo_CargoTurn_Coll(ftCo_GObj* gobj);
void ftCo_CargoTurn_IASA(ftCo_GObj* gobj);
void ftCo_CargoTurn_Phys(ftCo_GObj* gobj);
void ftCo_CargoWait2_Anim(ftCo_GObj* gobj);
void ftCo_CargoWait2_Coll(ftCo_GObj* gobj);
void ftCo_CargoWait2_Phys(ftCo_GObj* gobj);
void ftCo_CargoWait_Anim(ftCo_GObj* gobj);
void ftCo_CargoWait_Coll(ftCo_GObj* gobj);
void ftCo_CargoWait_IASA(ftCo_GObj* gobj);
void ftCo_CargoWait_Phys(ftCo_GObj* gobj);
void ftCo_Catch_Anim(ftCo_GObj* gobj);
void ftCo_CatchAttack_Anim(ftCo_GObj* gobj);
void ftCo_CatchAttack_Coll(ftCo_GObj* gobj);
void ftCo_CatchAttack_IASA(ftCo_GObj* gobj);
void ftCo_CatchAttack_Phys(ftCo_GObj* gobj);
void ftCo_Catch_Coll(ftCo_GObj* gobj);
void ftCo_CatchCut_Anim(ftCo_GObj* gobj);
void ftCo_CatchCut_Coll(ftCo_GObj* gobj);
void ftCo_CatchCut_IASA(ftCo_GObj* gobj);
void ftCo_CatchCut_Phys(ftCo_GObj* gobj);
void ftCo_CatchDash_Anim(ftCo_GObj* gobj);
void ftCo_CatchDash_Coll(ftCo_GObj* gobj);
void ftCo_CatchDash_IASA(ftCo_GObj* gobj);
void ftCo_CatchDash_Phys(ftCo_GObj* gobj);
void ftCo_Catch_IASA(ftCo_GObj* gobj);
void ftCo_Catch_Phys(ftCo_GObj* gobj);
void ftCo_CatchPull_Anim(ftCo_GObj* gobj);
void ftCo_CatchPull_Coll(ftCo_GObj* gobj);
void ftCo_CatchPull_IASA(ftCo_GObj* gobj);
void ftCo_CatchPull_Phys(ftCo_GObj* gobj);
void ftCo_CatchWait_Anim(ftCo_GObj* gobj);
void ftCo_CatchWait_Coll(ftCo_GObj* gobj);
void ftCo_CatchWait_IASA(ftCo_GObj* gobj);
void ftCo_CatchWait_Phys(ftCo_GObj* gobj);
void ftCo_CliffAttack_Anim(ftCo_GObj* gobj);
void ftCo_CliffAttack_Coll(ftCo_GObj* gobj);
void ftCo_CliffAttack_IASA(ftCo_GObj* gobj);
void ftCo_CliffAttack_Phys(ftCo_GObj* gobj);
void ftCo_Cliff_Cam(ftCo_GObj* gobj);
void ftCo_CliffCatch_Anim(ftCo_GObj* gobj);
void ftCo_CliffCatch_Coll(ftCo_GObj* gobj);
void ftCo_CliffCatch_IASA(ftCo_GObj*);
void ftCo_CliffCatch_Phys(ftCo_GObj* gobj);
void ftCo_CliffClimb_Coll(ftCo_GObj* gobj);
void ftCo_CliffClimb_IASA(ftCo_GObj* gobj);
void ftCo_CliffClimb_Phys(ftCo_GObj* gobj);
void ftCo_CliffEscape_Anim(ftCo_GObj* gobj);
void ftCo_CliffEscape_Coll(ftCo_GObj* gobj);
void ftCo_CliffEscape_IASA(ftCo_GObj* gobj);
void ftCo_CliffEscape_Phys(ftCo_GObj* gobj);
void ftCo_CliffJump1_Anim(ftCo_GObj* gobj);
void ftCo_CliffJump1_Coll(ftCo_GObj* gobj);
void ftCo_CliffJump1_IASA(ftCo_GObj* gobj);
void ftCo_CliffJump1_Phys(ftCo_GObj* gobj);
void ftCo_CliffJump2_Anim(ftCo_GObj* gobj);
void ftCo_CliffJump2_Coll(ftCo_GObj* gobj);
void ftCo_CliffJump2_IASA(ftCo_GObj* gobj);
void ftCo_CliffJump2_Phys(ftCo_GObj* gobj);
void ftCo_CliffWait_Anim(ftCo_GObj* gobj);
void ftCo_CliffWait_Coll(ftCo_GObj* gobj);
void ftCo_CliffWait_IASA(ftCo_GObj* gobj);
void ftCo_CliffWait_Phys(ftCo_GObj* gobj);
void ftCo_Damage_Anim(ftCo_GObj* gobj);
void ftCo_DamageBind_Anim(ftCo_GObj* gobj);
void ftCo_DamageBind_Coll(ftCo_GObj* gobj);
void ftCo_DamageBind_IASA(ftCo_GObj* gobj);
void ftCo_DamageBind_Phys(ftCo_GObj* gobj);
void ftCo_Damage_Coll(ftCo_GObj* gobj);
void ftCo_DamageFall_Anim(ftCo_GObj* gobj);
void ftCo_DamageFall_Coll(ftCo_GObj* gobj);
void ftCo_DamageFall_IASA(ftCo_GObj* gobj);
void ftCo_DamageFall_Phys(ftCo_GObj* gobj);
void ftCo_DamageFly_Anim(ftCo_GObj* gobj);
void ftCo_DamageFly_Coll(ftCo_GObj* gobj);
void ftCo_DamageFly_IASA(ftCo_GObj* gobj);
void ftCo_DamageFly_Phys(ftCo_GObj* gobj);
void ftCo_DamageFlyRoll_Anim(ftCo_GObj* gobj);
void ftCo_DamageFlyRoll_Coll(ftCo_GObj* gobj);
void ftCo_DamageFlyRoll_IASA(ftCo_GObj* gobj);
void ftCo_DamageFlyRoll_Phys(ftCo_GObj* gobj);
void ftCo_Damage_IASA(ftCo_GObj* gobj);
void ftCo_DamageIce_Anim(ftCo_GObj* gobj);
void ftCo_DamageIce_Coll(ftCo_GObj* gobj);
void ftCo_DamageIce_IASA(ftCo_GObj* gobj);
void ftCo_DamageIceJump_Anim(ftCo_GObj* gobj);
void ftCo_DamageIceJump_Coll(ftCo_GObj* gobj);
void ftCo_DamageIceJump_IASA(ftCo_GObj* gobj);
void ftCo_DamageIceJump_Phys(ftCo_GObj* gobj);
void ftCo_DamageIce_Phys(ftCo_GObj* gobj);
void ftCo_Damage_Phys(ftCo_GObj* gobj);
void ftCo_DamageScrew_Anim(ftCo_GObj* gobj);
void ftCo_DamageScrew_Coll(ftCo_GObj* gobj);
void ftCo_DamageScrew_IASA(ftCo_GObj* gobj);
void ftCo_DamageScrew_Phys(ftCo_GObj* gobj);
void ftCo_DamageSong_Anim(ftCo_GObj* gobj);
void ftCo_DamageSong_Coll(ftCo_GObj* gobj);
void ftCo_DamageSong_IASA(ftCo_GObj* gobj);
void ftCo_DamageSong_Phys(ftCo_GObj* gobj);
void ftCo_DamageSongRv_Anim(ftCo_GObj* gobj);
void ftCo_DamageSongRv_Coll(ftCo_GObj* gobj);
void ftCo_DamageSongRv_IASA(ftCo_GObj* gobj);
void ftCo_DamageSongRv_Phys(ftCo_GObj* gobj);
void ftCo_DamageSongWait_Anim(ftCo_GObj* gobj);
void ftCo_DamageSongWait_Coll(ftCo_GObj* gobj);
void ftCo_DamageSongWait_IASA(ftCo_GObj* gobj);
void ftCo_DamageSongWait_Phys(ftCo_GObj* gobj);
void ftCo_Dash_Anim(ftCo_GObj* gobj);
void ftCo_Dash_Coll(ftCo_GObj* gobj);
void ftCo_Dash_IASA(ftCo_GObj* gobj);
void ftCo_Dash_Phys(ftCo_GObj* gobj);
void ftCo_DeadDown_Anim(ftCo_GObj* gobj);
void ftCo_DeadDown_Cam(ftCo_GObj* gobj);
void ftCo_DeadLeft_Anim(ftCo_GObj* gobj);
void ftCo_DeadLeft_Cam(ftCo_GObj* gobj);
void ftCo_DeadRight_Anim(ftCo_GObj* gobj);
void ftCo_DeadRight_Cam(ftCo_GObj* gobj);
void ftCo_DeadUp_Anim(ftCo_GObj* gobj);
void ftCo_DeadUp_Cam(ftCo_GObj* gobj);
void ftCo_DeadUpFall_Anim(ftCo_GObj* gobj);
void ftCo_DeadUpFall_Cam(ftCo_GObj* gobj);
void ftCo_DeadUpFall_Phys(ftCo_GObj* gobj);
void ftCo_DeadUpStar_Anim(ftCo_GObj* gobj);
void ftCo_DeadUpStar_Cam(ftCo_GObj* gobj);
void ftCo_Down_Anim(ftCo_GObj* gobj);
void ftCo_DownAttack_Anim(ftCo_GObj* gobj);
void ftCo_DownAttack_Coll(ftCo_GObj* gobj);
void ftCo_DownAttack_IASA(ftCo_GObj* gobj);
void ftCo_DownAttack_Phys(ftCo_GObj* gobj);
void ftCo_Down_Coll(ftCo_GObj* gobj);
void ftCo_DownDamage_Anim(ftCo_GObj* gobj);
void ftCo_DownDamage_Coll(ftCo_GObj* gobj);
void ftCo_DownDamage_IASA(ftCo_GObj* gobj);
void ftCo_DownDamage_Phys(ftCo_GObj* gobj);
void ftCo_Down_IASA(ftCo_GObj* gobj);
void ftCo_Down_Phys(ftCo_GObj* gobj);
void ftCo_DownReflect_Anim(ftCo_GObj* gobj);
void ftCo_DownReflect_Coll(ftCo_GObj* gobj);
void ftCo_DownReflect_IASA(ftCo_GObj* gobj);
void ftCo_DownReflect_Phys(ftCo_GObj* gobj);
void ftCo_DownSpot_Anim(ftCo_GObj* gobj);
void ftCo_DownSpot_Coll(ftCo_GObj* gobj);
void ftCo_DownSpot_IASA(ftCo_GObj* gobj);
void ftCo_DownSpot_Phys(ftCo_GObj* gobj);
void ftCo_DownStand_Anim(ftCo_GObj* gobj);
void ftCo_DownStand_Coll(ftCo_GObj* gobj);
void ftCo_DownStand_IASA(ftCo_GObj* gobj);
void ftCo_DownStand_Phys(ftCo_GObj* gobj);
void ftCo_Entry_Anim(ftCo_GObj* gobj);
void ftCo_Entry_Coll(ftCo_GObj* gobj);
void ftCo_EntryEnd_Anim(ftCo_GObj* gobj);
void ftCo_EntryEnd_Coll(ftCo_GObj* gobj);
void ftCo_EntryEnd_IASA(ftCo_GObj* gobj);
void ftCo_EntryEnd_Phys(ftCo_GObj* gobj);
void ftCo_Entry_IASA(ftCo_GObj* gobj);
void ftCo_Entry_Phys(ftCo_GObj* gobj);
void ftCo_EntryStart_Anim(ftCo_GObj* gobj);
void ftCo_EntryStart_Coll(ftCo_GObj* gobj);
void ftCo_EntryStart_IASA(ftCo_GObj* gobj);
void ftCo_EntryStart_Phys(ftCo_GObj* gobj);
void ftCo_EscapeAir_Anim(ftCo_GObj* gobj);
void ftCo_EscapeAir_Coll(ftCo_GObj* gobj);
void ftCo_EscapeAir_IASA(ftCo_GObj* gobj);
void ftCo_EscapeAir_Phys(ftCo_GObj* gobj);
void ftCo_Escape_Anim(ftCo_GObj* gobj);
void ftCo_Escape_Coll(ftCo_GObj* gobj);
void ftCo_Escape_IASA(ftCo_GObj* gobj);
void ftCo_EscapeN_Anim(ftCo_GObj* gobj);
void ftCo_EscapeN_Coll(ftCo_GObj* gobj);
void ftCo_EscapeN_IASA(ftCo_GObj* gobj);
void ftCo_EscapeN_Phys(ftCo_GObj* gobj);
void ftCo_Escape_Phys(ftCo_GObj* gobj);
void ftCo_FallAerial_Anim(ftCo_GObj* gobj);
void ftCo_FallAerial_Coll(ftCo_GObj* gobj);
void ftCo_FallAerial_IASA(ftCo_GObj* gobj);
void ftCo_FallAerial_Phys(ftCo_GObj* gobj);
void ftCo_Fall_Anim(ftCo_GObj* gobj);
void ftCo_Fall_Coll(ftCo_GObj* gobj);
void ftCo_Fall_IASA(ftCo_GObj* gobj);
void ftCo_Fall_Phys(ftCo_GObj* gobj);
void ftCo_FallSpecial_Anim(ftCo_GObj* gobj);
void ftCo_FallSpecial_Coll(ftCo_GObj* gobj);
void ftCo_FallSpecial_IASA(ftCo_GObj* gobj);
void ftCo_FallSpecial_Phys(ftCo_GObj* gobj);
void ftCo_FireFlowerShootAir_Anim(ftCo_GObj* gobj);
void ftCo_FireFlowerShootAir_Coll(ftCo_GObj* gobj);
void ftCo_FireFlowerShootAir_IASA(ftCo_GObj* gobj);
void ftCo_FireFlowerShootAir_Phys(ftCo_GObj* gobj);
void ftCo_FireFlowerShoot_Anim(ftCo_GObj* gobj);
void ftCo_FireFlowerShoot_Coll(ftCo_GObj* gobj);
void ftCo_FireFlowerShoot_IASA(ftCo_GObj* gobj);
void ftCo_FireFlowerShoot_Phys(ftCo_GObj* gobj);
void ftCo_FlyReflect_Anim(ftCo_GObj* gobj);
void ftCo_FlyReflect_Coll(ftCo_GObj* gobj);
void ftCo_FlyReflect_IASA(ftCo_GObj* gobj);
void ftCo_FlyReflect_Phys(ftCo_GObj* gobj);
void ftCo_Furafura_Anim(ftCo_GObj* gobj);
void ftCo_Furafura_Coll(ftCo_GObj* gobj);
void ftCo_Furafura_IASA(ftCo_GObj* gobj);
void ftCo_Furafura_Phys(ftCo_GObj* gobj);
void ftCo_Guard_Anim(ftCo_GObj* gobj);
void ftCo_Guard_Coll(ftCo_GObj* gobj);
void ftCo_Guard_IASA(ftCo_GObj* gobj);
void ftCo_GuardOff_Anim(ftCo_GObj* gobj);
void ftCo_GuardOff_Coll(ftCo_GObj* gobj);
void ftCo_GuardOff_IASA(ftCo_GObj* gobj);
void ftCo_GuardOff_Phys(ftCo_GObj* gobj);
void ftCo_GuardOn_Anim(ftCo_GObj* gobj);
void ftCo_GuardOn_Coll(ftCo_GObj* gobj);
void ftCo_GuardOn_IASA(ftCo_GObj* gobj);
void ftCo_GuardOn_Phys(ftCo_GObj* gobj);
void ftCo_Guard_Phys(ftCo_GObj* gobj);
void ftCo_GuardReflect_Anim(ftCo_GObj* gobj);
void ftCo_GuardReflect_Coll(ftCo_GObj* gobj);
void ftCo_GuardReflect_IASA(ftCo_GObj* gobj);
void ftCo_GuardReflect_Phys(ftCo_GObj* gobj);
void ftCo_GuardSetOff_Anim(ftCo_GObj* gobj);
void ftCo_GuardSetOff_Coll(ftCo_GObj* gobj);
void ftCo_GuardSetOff_IASA(ftCo_GObj* gobj);
void ftCo_GuardSetOff_Phys(ftCo_GObj* gobj);
void ftCo_HammerFall_Anim(ftCo_GObj* gobj);
void ftCo_HammerFall_Coll(ftCo_GObj* gobj);
void ftCo_HammerFall_IASA(ftCo_GObj* gobj);
void ftCo_HammerFall_Phys(ftCo_GObj* gobj);
void ftCo_HammerJump_Anim(ftCo_GObj* gobj);
void ftCo_HammerJump_Coll(ftCo_GObj* gobj);
void ftCo_HammerJump_IASA(ftCo_GObj* gobj);
void ftCo_HammerJump_Phys(ftCo_GObj* gobj);
void ftCo_HammerKneeBend_Anim(ftCo_GObj* gobj);
void ftCo_HammerKneeBend_Coll(ftCo_GObj* gobj);
void ftCo_HammerKneeBend_IASA(ftCo_GObj* gobj);
void ftCo_HammerKneeBend_Phys(ftCo_GObj* gobj);
void ftCo_HammerLanding_Anim(ftCo_GObj* gobj);
void ftCo_HammerLanding_Coll(ftCo_GObj* gobj);
void ftCo_HammerLanding_IASA(ftCo_GObj* gobj);
void ftCo_HammerLanding_Phys(ftCo_GObj* gobj);
void ftCo_HammerTurn_Anim(ftCo_GObj* gobj);
void ftCo_HammerTurn_Coll(ftCo_GObj* gobj);
void ftCo_HammerTurn_IASA(ftCo_GObj* gobj);
void ftCo_HammerTurn_Phys(ftCo_GObj* gobj);
void ftCo_HammerWait_Anim(ftCo_GObj* gobj);
void ftCo_HammerWait_Coll(ftCo_GObj* gobj);
void ftCo_HammerWait_IASA(ftCo_GObj* gobj);
void ftCo_HammerWait_Phys(ftCo_GObj* gobj);
void ftCo_HammerWalk_Anim(ftCo_GObj* gobj);
void ftCo_HammerWalk_Coll(ftCo_GObj* gobj);
void ftCo_HammerWalk_IASA(ftCo_GObj* gobj);
void ftCo_HammerWalk_Phys(ftCo_GObj* gobj);
void ftCo_HarisenSwing_Anim(ftCo_GObj* gobj);
void ftCo_HarisenSwing_Coll(ftCo_GObj* gobj);
void ftCo_HarisenSwing_IASA(ftCo_GObj* gobj);
void ftCo_HarisenSwing_Phys(ftCo_GObj* gobj);
void ftCo_HeavyThrow_Coll(ftCo_GObj* gobj);
void ftCo_ItemGet_Anim(ftCo_GObj* gobj);
void ftCo_ItemGet_Coll(ftCo_GObj* gobj);
void ftCo_ItemGet_IASA(ftCo_GObj* gobj);
void ftCo_ItemGet_Phys(ftCo_GObj* gobj);
void ftCo_ItemParasolDamageFall_Anim(ftCo_GObj* gobj);
void ftCo_ItemParasolDamageFall_Coll(ftCo_GObj* gobj);
void ftCo_ItemParasolDamageFall_IASA(ftCo_GObj* gobj);
void ftCo_ItemParasolDamageFall_Phys(ftCo_GObj* gobj);
void ftCo_ItemParasolFall_Anim(ftCo_GObj* gobj);
void ftCo_ItemParasolFall_Coll(ftCo_GObj* gobj);
void ftCo_ItemParasolFall_IASA(ftCo_GObj* gobj);
void ftCo_ItemParasolFall_Phys(ftCo_GObj* gobj);
void ftCo_ItemParasolFallSpecial_Anim(ftCo_GObj* gobj);
void ftCo_ItemParasolFallSpecial_Coll(ftCo_GObj* gobj);
void ftCo_ItemParasolFallSpecial_IASA(ftCo_GObj* gobj);
void ftCo_ItemParasolFallSpecial_Phys(ftCo_GObj* gobj);
void ftCo_ItemParasolOpen_Anim(ftCo_GObj* gobj);
void ftCo_ItemParasolOpen_Coll(ftCo_GObj* gobj);
void ftCo_ItemParasolOpen_IASA(ftCo_GObj* gobj);
void ftCo_ItemParasolOpen_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeAirEnd_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeAirEnd_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeAirEnd_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeAirEnd_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeAirFire_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeAirFire_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeAirFire_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeAirFire_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeAirRapid_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeAirRapid_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeAirRapid_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeAirRapid_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeAirStart_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeAirStart_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeAirStart_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeAirStart_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeEnd_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeEnd_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeEnd_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeEnd_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeFire_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeFire_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeFire_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeFire_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeRapid_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeRapid_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeRapid_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeRapid_Phys(ftCo_GObj* gobj);
void ftCo_ItemScopeStart_Anim(ftCo_GObj* gobj);
void ftCo_ItemScopeStart_Coll(ftCo_GObj* gobj);
void ftCo_ItemScopeStart_IASA(ftCo_GObj* gobj);
void ftCo_ItemScopeStart_Phys(ftCo_GObj* gobj);
void ftCo_ItemScrewAir_Anim(ftCo_GObj* gobj);
void ftCo_ItemScrewAir_Coll(ftCo_GObj* gobj);
void ftCo_ItemScrewAir_IASA(ftCo_GObj* gobj);
void ftCo_ItemScrewAir_Phys(ftCo_GObj* gobj);
void ftCo_ItemScrew_Anim(ftCo_GObj* gobj);
void ftCo_ItemScrew_Coll(ftCo_GObj* gobj);
void ftCo_ItemScrew_IASA(ftCo_GObj* gobj);
void ftCo_ItemScrew_Phys(ftCo_GObj* gobj);
void ftCo_ItemThrow_Anim(ftCo_GObj* gobj);
void ftCo_ItemThrow_IASA(ftCo_GObj* gobj);
void ftCo_ItemThrow_Phys(ftCo_GObj* gobj);
void ftCo_JumpAerial_Anim(ftCo_GObj* gobj);
void ftCo_JumpAerial_Coll(ftCo_GObj* gobj);
void ftCo_JumpAerialF1_Anim(ftCo_GObj* gobj);
void ftCo_JumpAerialF1_Coll(ftCo_GObj* gobj);
void ftCo_JumpAerialF1_IASA(ftCo_GObj* gobj);
void ftCo_JumpAerialF1_Phys(ftCo_GObj* gobj);
void ftCo_JumpAerial_IASA(ftCo_GObj* gobj);
void ftCo_JumpAerial_Phys(ftCo_GObj* gobj);
void ftCo_Jump_Anim(ftCo_GObj* gobj);
void ftCo_Jump_Coll(ftCo_GObj* gobj);
void ftCo_Jump_IASA(ftCo_GObj* gobj);
void ftCo_Jump_Phys(ftCo_GObj* gobj);
void ftCo_KinokoGiantEndAir_Anim(ftCo_GObj* gobj);
void ftCo_KinokoGiantEndAir_Coll(ftCo_GObj* gobj);
void ftCo_KinokoGiantEnd_Anim(ftCo_GObj* gobj);
void ftCo_KinokoGiantEnd_Coll(ftCo_GObj* gobj);
void ftCo_KinokoGiantStartAir_Anim(ftCo_GObj* gobj);
void ftCo_KinokoGiantStartAir_Coll(ftCo_GObj* gobj);
void ftCo_KinokoGiantStart_Anim(ftCo_GObj* gobj);
void ftCo_KinokoGiantStart_Coll(ftCo_GObj* gobj);
void ftCo_KinokoSmallEndAir_Anim(ftCo_GObj* gobj);
void ftCo_KinokoSmallEndAir_Coll(ftCo_GObj* gobj);
void ftCo_KinokoSmallEnd_Anim(ftCo_GObj* gobj);
void ftCo_KinokoSmallEnd_Coll(ftCo_GObj* gobj);
void ftCo_KinokoSmallStartAir_Anim(ftCo_GObj* gobj);
void ftCo_KinokoSmallStartAir_Coll(ftCo_GObj* gobj);
void ftCo_KinokoSmallStart_Anim(ftCo_GObj* gobj);
void ftCo_KinokoSmallStart_Coll(ftCo_GObj* gobj);
void ftCo_KneeBend_Anim(ftCo_GObj* gobj);
void ftCo_KneeBend_Coll(ftCo_GObj* gobj);
void ftCo_KneeBend_IASA(ftCo_GObj* gobj);
void ftCo_KneeBend_Phys(ftCo_GObj* gobj);
void ftCo_Landing_Anim(ftCo_GObj* gobj);
void ftCo_Landing_Coll(ftCo_GObj* gobj);
void ftCo_Landing_IASA(ftCo_GObj* gobj);
void ftCo_Landing_Phys(ftCo_GObj* gobj);
void ftCo_LGunShootAir_Anim(ftCo_GObj* gobj);
void ftCo_LGunShootAir_Coll(ftCo_GObj* gobj);
void ftCo_LGunShootAir_IASA(ftCo_GObj* gobj);
void ftCo_LGunShootAir_Phys(ftCo_GObj* gobj);
void ftCo_LGunShoot_Anim(ftCo_GObj* gobj);
void ftCo_LGunShoot_Coll(ftCo_GObj* gobj);
void ftCo_LGunShoot_IASA(ftCo_GObj* gobj);
void ftCo_LGunShoot_Phys(ftCo_GObj* gobj);
void ftCo_LiftTurn_Anim(ftCo_GObj* gobj);
void ftCo_LiftTurn_Coll(ftCo_GObj* gobj);
void ftCo_LiftTurn_IASA(ftCo_GObj* gobj);
void ftCo_LiftTurn_Phys(ftCo_GObj* gobj);
void ftCo_LiftWait_Anim(ftCo_GObj* gobj);
void ftCo_LiftWait_Coll(ftCo_GObj* gobj);
void ftCo_LiftWait_IASA(ftCo_GObj* gobj);
void ftCo_LiftWait_Phys(ftCo_GObj* gobj);
void ftCo_LiftWalk_Anim(ftCo_GObj* gobj);
void ftCo_LiftWalk_Coll(ftCo_GObj* gobj);
void ftCo_LiftWalk_IASA(ftCo_GObj* gobj);
void ftCo_LiftWalk_Phys(ftCo_GObj* gobj);
void ftCo_LightThrowAir_Coll(ftCo_GObj* gobj);
void ftCo_LightThrowAir_Phys(ftCo_GObj* gobj);
void ftCo_LightThrow_Coll(ftCo_GObj* gobj);
void ftCo_LipstickSwing_Anim(ftCo_GObj* gobj);
void ftCo_LipstickSwing_Coll(ftCo_GObj* gobj);
void ftCo_LipstickSwing_IASA(ftCo_GObj* gobj);
void ftCo_LipstickSwing_Phys(ftCo_GObj* gobj);
void ftCo_MissFoot_Anim(ftCo_GObj* gobj);
void ftCo_MissFoot_Coll(ftCo_GObj* gobj);
void ftCo_MissFoot_IASA(ftCo_GObj* gobj);
void ftCo_MissFoot_Phys(ftCo_GObj* gobj);
void ftCo_Ottotto_Anim(ftCo_GObj* gobj);
void ftCo_Ottotto_Coll(ftCo_GObj* gobj);
void ftCo_Ottotto_IASA(ftCo_GObj* gobj);
void ftCo_Ottotto_Phys(ftCo_GObj* gobj);
void ftCo_OttottoWait_Anim(ftCo_GObj* gobj);
void ftCo_OttottoWait_Coll(ftCo_GObj* gobj);
void ftCo_OttottoWait_IASA(ftCo_GObj* gobj);
void ftCo_OttottoWait_Phys(ftCo_GObj* gobj);
void ftCo_ParasolSwing_Anim(ftCo_GObj* gobj);
void ftCo_ParasolSwing_Coll(ftCo_GObj* gobj);
void ftCo_ParasolSwing_IASA(ftCo_GObj* gobj);
void ftCo_ParasolSwing_Phys(ftCo_GObj* gobj);
void ftCo_Pass_Anim(ftCo_GObj* gobj);
void ftCo_Pass_Coll(ftCo_GObj* gobj);
void ftCo_Pass_IASA(ftCo_GObj* gobj);
void ftCo_PassiveCeil_Anim(ftCo_GObj* gobj);
void ftCo_PassiveCeil_Coll(ftCo_GObj* gobj);
void ftCo_PassiveCeil_IASA(ftCo_GObj* gobj);
void ftCo_PassiveCeil_Phys(ftCo_GObj* gobj);
void ftCo_PassiveStand_Anim(ftCo_GObj* gobj);
void ftCo_PassiveStand_Coll(ftCo_GObj* gobj);
void ftCo_PassiveStand_IASA(ftCo_GObj* gobj);
void ftCo_PassiveStand_Phys(ftCo_GObj* gobj);
void ftCo_PassiveWall_Anim(ftCo_GObj* gobj);
void ftCo_PassiveWall_Coll(ftCo_GObj* gobj);
void ftCo_PassiveWall_IASA(ftCo_GObj* gobj);
void ftCo_PassiveWall_Phys(ftCo_GObj* gobj);
void ftCo_Pass_Phys(ftCo_GObj* gobj);
void ftCo_Rebirth_Anim(ftCo_GObj* gobj);
void ftCo_Rebirth_Cam(ftCo_GObj* gobj);
void ftCo_Rebirth_Coll(ftCo_GObj* gobj);
void ftCo_Rebirth_IASA(ftCo_GObj* gobj);
void ftCo_Rebirth_Phys(ftCo_GObj* gobj);
void ftCo_RebirthWait_Anim(ftCo_GObj* gobj);
void ftCo_RebirthWait_Coll(ftCo_GObj* gobj);
void ftCo_RebirthWait_IASA(ftCo_GObj* gobj);
void ftCo_RebirthWait_Phys(ftCo_GObj* gobj);
void ftCo_Rebound_Anim(ftCo_GObj* gobj);
void ftCo_Rebound_Coll(ftCo_GObj* gobj);
void ftCo_Rebound_IASA(ftCo_GObj* gobj);
void ftCo_Rebound_Phys(ftCo_GObj* gobj);
void ftCo_ReboundStop_Anim(ftCo_GObj* gobj);
void ftCo_Run_Anim(ftCo_GObj* gobj);
void ftCo_RunBrake_Anim(ftCo_GObj* gobj);
void ftCo_RunBrake_Coll(ftCo_GObj* gobj);
void ftCo_RunBrake_IASA(ftCo_GObj* gobj);
void ftCo_RunBrake_Phys(ftCo_GObj* gobj);
void ftCo_Run_Coll(ftCo_GObj* gobj);
void ftCo_RunDirect_Anim(ftCo_GObj* gobj);
void ftCo_RunDirect_Coll(ftCo_GObj* gobj);
void ftCo_RunDirect_IASA(ftCo_GObj* gobj);
void ftCo_RunDirect_Phys(ftCo_GObj* gobj);
void ftCo_Run_IASA(ftCo_GObj* gobj);
void ftCo_Run_Phys(ftCo_GObj* gobj);
void ftCo_SetFacingDirection(ftCo_GObj*, f32 facing_dir);
void ftCo_ShieldBreakDown_Anim(ftCo_GObj* gobj);
void ftCo_ShieldBreakDown_Coll(ftCo_GObj* gobj);
void ftCo_ShieldBreakDown_IASA(ftCo_GObj* gobj);
void ftCo_ShieldBreakDown_Phys(ftCo_GObj* gobj);
void ftCo_ShieldBreakFall_Anim(ftCo_GObj* gobj);
void ftCo_ShieldBreakFall_Coll(ftCo_GObj* gobj);
void ftCo_ShieldBreakFall_IASA(ftCo_GObj* gobj);
void ftCo_ShieldBreakFall_Phys(ftCo_GObj* gobj);
void ftCo_ShieldBreakFly_Anim(ftCo_GObj* gobj);
void ftCo_ShieldBreakFly_Coll(ftCo_GObj* gobj);
void ftCo_ShieldBreakFly_IASA(ftCo_GObj* gobj);
void ftCo_ShieldBreakFly_Phys(ftCo_GObj* gobj);
void ftCo_ShieldBreakStand_Anim(ftCo_GObj* gobj);
void ftCo_ShieldBreakStand_Coll(ftCo_GObj* gobj);
void ftCo_ShieldBreakStand_IASA(ftCo_GObj* gobj);
void ftCo_ShieldBreakStand_Phys(ftCo_GObj* gobj);
void ftCo_Shouldered_Anim(ftCo_GObj* gobj);
void ftCo_Shouldered_Coll(ftCo_GObj* gobj);
void ftCo_Shouldered_IASA(ftCo_GObj* gobj);
void ftCo_Shouldered_Phys(ftCo_GObj* gobj);
void ftCo_Sleep_Anim(ftCo_GObj* gobj);
void ftCo_Sleep_IASA(ftCo_GObj* gobj);
void ftCo_Squat_Anim(ftCo_GObj* gobj);
void ftCo_Squat_Coll(ftCo_GObj* gobj);
void ftCo_Squat_IASA(ftCo_GObj* gobj);
void ftCo_Squat_Phys(ftCo_GObj* gobj);
void ftCo_SquatRv_Anim(ftCo_GObj* gobj);
void ftCo_SquatRv_Coll(ftCo_GObj* gobj);
void ftCo_SquatRv_IASA(ftCo_GObj* gobj);
void ftCo_SquatRv_Phys(ftCo_GObj* gobj);
void ftCo_SquatWait_Anim(ftCo_GObj* gobj);
void ftCo_SquatWait_Coll(ftCo_GObj* gobj);
void ftCo_SquatWait_IASA(ftCo_GObj* gobj);
void ftCo_SquatWait_Phys(ftCo_GObj* gobj);
void ftCo_StarRodSwing_Anim(ftCo_GObj* gobj);
void ftCo_StarRodSwing_Coll(ftCo_GObj* gobj);
void ftCo_StarRodSwing_IASA(ftCo_GObj* gobj);
void ftCo_StarRodSwing_Phys(ftCo_GObj* gobj);
void ftCo_StopCeil_Anim(ftCo_GObj* gobj);
void ftCo_StopCeil_Coll(ftCo_GObj* gobj);
void ftCo_StopCeil_IASA(ftCo_GObj* gobj);
void ftCo_StopCeil_Phys(ftCo_GObj* gobj);
void ftCo_StopWall_Anim(ftCo_GObj* gobj);
void ftCo_StopWall_Coll(ftCo_GObj* gobj);
void ftCo_StopWall_IASA(ftCo_GObj* gobj);
void ftCo_StopWall_Phys(ftCo_GObj* gobj);
void ftCo_SwordSwing_Anim(ftCo_GObj* gobj);
void ftCo_SwordSwing_Coll(ftCo_GObj* gobj);
void ftCo_SwordSwing_IASA(ftCo_GObj* gobj);
void ftCo_SwordSwing_Phys(ftCo_GObj* gobj);
void ftCo_ThrowB_Anim(ftCo_GObj* gobj);
void ftCo_ThrowB_Coll(ftCo_GObj* gobj);
void ftCo_ThrowB_IASA(ftCo_GObj* gobj);
void ftCo_ThrowB_Phys(ftCo_GObj* gobj);
void ftCo_ThrowF_Anim(ftCo_GObj* gobj);
void ftCo_ThrowF_Coll(ftCo_GObj* gobj);
void ftCo_ThrowF_IASA(ftCo_GObj* gobj);
void ftCo_ThrowF_Phys(ftCo_GObj* gobj);
void ftCo_ThrowHi_Anim(ftCo_GObj* gobj);
void ftCo_ThrowHi_Cam(ftCo_GObj* gobj);
void ftCo_ThrowHi_Coll(ftCo_GObj* gobj);
void ftCo_ThrowHi_IASA(ftCo_GObj* gobj);
void ftCo_ThrowHi_Phys(ftCo_GObj* gobj);
void ftCo_ThrowLw_Anim(ftCo_GObj* gobj);
void ftCo_ThrowLw_Coll(ftCo_GObj* gobj);
void ftCo_ThrowLw_IASA(ftCo_GObj* gobj);
void ftCo_ThrowLw_Phys(ftCo_GObj* gobj);
void ftCo_ThrownB_Anim(ftCo_GObj* gobj);
void ftCo_ThrownB_Coll(ftCo_GObj* gobj);
void ftCo_ThrownB_IASA(ftCo_GObj* gobj);
void ftCo_ThrownB_Phys(ftCo_GObj* gobj);
void ftCo_ThrownCopyStar_Anim(ftCo_GObj* gobj);
void ftCo_ThrownCopyStar_Coll(ftCo_GObj* gobj);
void ftCo_ThrownCopyStar_IASA(ftCo_GObj* gobj);
void ftCo_ThrownCopyStar_Phys(ftCo_GObj* gobj);
void ftCo_ThrownF_Anim(ftCo_GObj* gobj);
void ftCo_ThrownF_Coll(ftCo_GObj* gobj);
void ftCo_ThrownF_IASA(ftCo_GObj* gobj);
void ftCo_ThrownF_Phys(ftCo_GObj* gobj);
void ftCo_ThrownHi_Anim(ftCo_GObj* gobj);
void ftCo_ThrownHi_Cam(ftCo_GObj* gobj);
void ftCo_ThrownHi_Coll(ftCo_GObj* gobj);
void ftCo_ThrownHi_IASA(ftCo_GObj* gobj);
void ftCo_ThrownHi_Phys(ftCo_GObj* gobj);
void ftCo_ThrownKirby_Anim(ftCo_GObj* gobj);
void ftCo_ThrownKirby_Coll(ftCo_GObj* gobj);
void ftCo_ThrownKirby_IASA(ftCo_GObj* gobj);
void ftCo_ThrownKirby_Phys(ftCo_GObj* gobj);
void ftCo_ThrownKirbyStar_Anim(ftCo_GObj* gobj);
void ftCo_ThrownKirbyStar_Coll(ftCo_GObj* gobj);
void ftCo_ThrownKirbyStar_IASA(ftCo_GObj* gobj);
void ftCo_ThrownKirbyStar_Phys(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirB_Anim(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirB_Coll(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirB_IASA(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirB_Phys(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirF_Anim(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirF_Coll(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirF_IASA(ftCo_GObj* gobj);
void ftCo_ThrownKoopaAirF_Phys(ftCo_GObj* gobj);
void ftCo_ThrownKoopaB_Anim(ftCo_GObj* gobj);
void ftCo_ThrownKoopaB_Coll(ftCo_GObj* gobj);
void ftCo_ThrownKoopaB_IASA(ftCo_GObj* gobj);
void ftCo_ThrownKoopaB_Phys(ftCo_GObj* gobj);
void ftCo_ThrownKoopaF_Anim(ftCo_GObj* gobj);
void ftCo_ThrownKoopaF_Coll(ftCo_GObj* gobj);
void ftCo_ThrownKoopaF_IASA(ftCo_GObj* gobj);
void ftCo_ThrownKoopaF_Phys(ftCo_GObj* gobj);
void ftCo_ThrownLw_Anim(ftCo_GObj* gobj);
void ftCo_ThrownLw_Coll(ftCo_GObj* gobj);
void ftCo_ThrownLw_IASA(ftCo_GObj* gobj);
void ftCo_ThrownLw_Phys(ftCo_GObj* gobj);
void ftCo_ThrownMewtwoAir_Anim(ftCo_GObj* gobj);
void ftCo_ThrownMewtwoAir_Coll(ftCo_GObj* gobj);
void ftCo_ThrownMewtwoAir_IASA(ftCo_GObj* gobj);
void ftCo_ThrownMewtwoAir_Phys(ftCo_GObj* gobj);
void ftCo_ThrownMewtwo_Anim(ftCo_GObj* gobj);
void ftCo_ThrownMewtwo_Coll(ftCo_GObj* gobj);
void ftCo_ThrownMewtwo_IASA(ftCo_GObj* gobj);
void ftCo_ThrownMewtwo_Phys(ftCo_GObj* gobj);
void ftCo_Turn_Anim(ftCo_GObj* gobj);
void ftCo_Turn_Coll(ftCo_GObj* gobj);
void ftCo_Turn_IASA(ftCo_GObj* gobj);
void ftCo_Turn_Phys(ftCo_GObj* gobj);
void ftCo_TurnRun_Anim(ftCo_GObj* gobj);
void ftCo_TurnRun_Coll(ftCo_GObj* gobj);
void ftCo_TurnRun_IASA(ftCo_GObj* gobj);
void ftCo_TurnRun_Phys(ftCo_GObj* gobj);
void ftCo_Wait_IASA(ftCo_GObj* gobj);
void ftCo_Walk_Anim(ftCo_GObj* gobj);
void ftCo_Walk_Coll(ftCo_GObj* gobj);
void ftCo_Walk_IASA(ftCo_GObj* gobj);
void ftCo_Walk_Phys(ftCo_GObj* gobj);
void ftCo_WarpStarFall_Anim(ftCo_GObj* gobj);
void ftCo_WarpStarFall_Cam(ftCo_GObj* gobj);
void ftCo_WarpStarFall_Coll(ftCo_GObj* gobj);
void ftCo_WarpStarFall_IASA(ftCo_GObj* gobj);
void ftCo_WarpStarFall_Phys(ftCo_GObj* gobj);
void ftCo_WarpStarJump_Anim(ftCo_GObj* gobj);
void ftCo_WarpStarJump_Cam(ftCo_GObj* gobj);
void ftCo_WarpStarJump_Coll(ftCo_GObj* gobj);
void ftCo_WarpStarJump_IASA(ftCo_GObj* gobj);
void ftCo_WarpStarJump_Phys(ftCo_GObj* gobj);
void ftCo_YoshiEgg_Anim(ftCo_GObj* gobj);
void ftCo_YoshiEgg_Coll(ftCo_GObj* gobj);
void ftCo_YoshiEgg_IASA(ftCo_GObj* gobj);
void ftCo_YoshiEgg_Phys(ftCo_GObj* gobj);
/* 0C0B20 */ UNK_RET ftCo_800C0B20(UNK_PARAMS);
/* 0C08A0 */ UNK_RET ftCo_800C08A0(UNK_PARAMS);
/* 0DA698 */ void ftCo_800DA698(ftCo_GObj* gobj, bool);
/* 0BCD00 */ void ftCo_800BCD00(ftCo_GObj* gobj);

#endif
