#ifndef MELEE_FT_FT_08A4_H
#define MELEE_FT_FT_08A4_H

#include <platform.h>
#include "ft/forward.h"
#include "ftCommon/forward.h"

#include <placeholder.h>

/* 096250 */ void ftCo_80096250(ftCo_GObj* gobj);
/* 096498 */ void ftCo_80096498(ftCo_GObj* gobj);
/* 0970E0 */ bool ftCo_800970E0(ftCo_GObj* gobj);
/* 097130 */ void ftCo_80097130(ftCo_GObj* gobj);
/* 0974C4 */ void ftCo_800974C4(ftCo_GObj* gobj);
/* 09794C */ void ftCo_8009794C(ftCo_GObj* gobj);
/* 097AF4 */ void ftCo_80097AF4(ftCo_GObj* gobj);
/* 098400 */ bool ftCo_80098400(ftCo_GObj* gobj);
/* 098D90 */ void ftCo_80098D90(ftCo_GObj* gobj);
/* 09BB64 */ /* static */ void ftCo_8009BB64(ftCo_GObj* gobj);
/* 09CB40 */ /* static */ UNK_RET ftCo_8009CB40(UNK_PARAMS);
/* 09DD94 */ /* static */ UNK_RET ftCo_8009DD94(UNK_PARAMS);
/* 09E140 */ void ftCo_8009E140(ftCo_Fighter* fp, bool);
/* 09E1D4 */ /* static */ UNK_RET ftCo_8009E1D4(UNK_PARAMS);
/* 09E318 */ void ftCo_8009E318(int, void*, float);
/* 09E4A8 */ /* static */ UNK_RET ftCo_8009E4A8(UNK_PARAMS);
/* 09E614 */ /* static */ UNK_RET ftCo_8009E614(UNK_PARAMS);
/* 09E714 */ void ftCo_8009E714(u8, s16, char*, u8, float, float, float, float,
                                float, float);
/* 09EB18 */ /* static */ UNK_RET ftCo_8009EB18(UNK_PARAMS);
/* 09EE30 */ /* static */ UNK_RET ftCo_8009EE30(UNK_PARAMS);
/* 09EFA4 */ /* static */ UNK_RET ftCo_8009EFA4(UNK_PARAMS);
/* 09F0F0 */ bool ftCo_8009F0F0(ftCo_GObj* gobj);
/* 09F184 */ UNK_RET ftCo_8009F184(UNK_PARAMS);
/* 09F75C */ UNK_RET ftCo_8009F75C(UNK_PARAMS);
/* 09F834 */ void ftCo_8009F834(ftCo_GObj*, int, int, int, int, Vec3*, Vec3*,
                                float);
/* 0A0098 */ UNK_RET ftCo_800A0098(UNK_PARAMS);
/* 0A0148 */ UNK_RET ftCo_800A0148(UNK_PARAMS);
/* 0A0384 */ UNK_RET ftCo_800A0384(UNK_PARAMS);
/* 0A0508 */ UNK_RET ftCo_800A0508(UNK_PARAMS);
/* 0A05F4 */ UNK_RET ftCo_800A05F4(UNK_PARAMS);
/* 0A0798 */ UNK_RET ftCo_800A0798(UNK_PARAMS);
/* 0A08F0 */ UNK_RET ftCo_800A08F0(UNK_PARAMS);
/* 0A0AF4 */ UNK_RET ftCo_800A0AF4(UNK_PARAMS);
/* 0A0C8C */ UNK_RET ftCo_800A0C8C(UNK_PARAMS);
/* 0A0CB0 */ UNK_RET ftCo_800A0CB0(UNK_PARAMS);
/* 0A0F00 */ UNK_RET ftCo_800A0F00(UNK_PARAMS);
/* 0A0FB0 */ UNK_RET ftCo_800A0FB0(UNK_PARAMS);
/* 0A2040 */ bool ftCo_800A2040(Fighter* fp);
/* 0C0CB8 */ bool ftCo_800C0CB8(ftCo_GObj* gobj);
/* 0C0D0C */ UNK_RET ftCo_800C0D0C(UNK_PARAMS);
/* 0C124C */ UNK_RET ftCo_800C124C(UNK_PARAMS);
/* 0C13BC */ UNK_RET ftCo_800C13BC(UNK_PARAMS);
/* 0C15F4 */ UNK_RET ftCo_800C15F4(UNK_PARAMS);
/* 0C1718 */ UNK_RET ftCo_800C1718(UNK_PARAMS);
/* 0C17CC */ bool ftCo_800C17CC(ftCo_GObj* gobj);
/* 0C18A8 */ UNK_RET ftCo_800C18A8(UNK_PARAMS);
/* 0C1D38 */ bool ftCo_800C1D38(ftCo_GObj* gobj);
/* 0C1E0C */ UNK_RET ftCo_800C1E0C(UNK_PARAMS);
/* 0C23A0 */ bool ftCo_800C23A0(ftCo_GObj* gobj);
/* 0C23FC */ UNK_RET ftCo_800C23FC(UNK_PARAMS);
/* 0C27B4 */ UNK_RET ftCo_800C27B4(UNK_PARAMS);
/* 0C27C0 */ UNK_RET ftCo_800C27C0(UNK_PARAMS);
/* 0C27C8 */ UNK_RET ftCo_800C27C8(UNK_PARAMS);
/* 0C30C0 */ UNK_RET ftCo_800C30C0(UNK_PARAMS);
/* 0C318C */ void ftCo_800C318C(ftCo_GObj* gobj, bool);
/* 0C3390 */ UNK_RET ftCo_800C3390(UNK_PARAMS);
/* 0C3480 */ UNK_RET ftCo_800C3480(UNK_PARAMS);
/* 0C3538 */ bool ftCo_800C3538(ftCo_GObj* gobj);
/* 0C3598 */ void ftCo_800C3598(ftCo_GObj* gobj);
/* 0C36DC */ void ftCo_800C36DC(ftCo_GObj* gobj);
/* 0C3B10 */ bool ftCo_800C3B10(ftCo_GObj* gobj);
/* 0C3BE8 */ UNK_RET ftCo_800C3BE8(UNK_PARAMS);
/* 0C44CC */ bool ftCo_800C44CC(ftCo_GObj* gobj);
/* 0C4550 */ UNK_RET ftCo_800C4550(UNK_PARAMS);
/* 0C4724 */ void ftCo_800C4724(ftCo_GObj* gobj);
/* 0C4A38 */ UNK_RET ftCo_800C4A38(UNK_PARAMS);
/* 0C4E4C */ UNK_RET ftCo_800C4E4C(UNK_PARAMS);
/* 0C4E94 */ UNK_RET ftCo_800C4E94(UNK_PARAMS);
/* 0C4F64 */ UNK_RET ftCo_800C4F64(UNK_PARAMS);
/* 0C5284 */ void ftCo_800C5284(ftCo_GObj* gobj);
/* 0C52F4 */ void ftCo_800C52F4(ftCo_GObj* gobj);
/* 0C53E4 */ UNK_RET ftCo_800C53E4(UNK_PARAMS);
/* 0C5408 */ UNK_RET ftCo_800C5408(UNK_PARAMS);
/* 0C544C */ UNK_RET ftCo_800C544C(UNK_PARAMS);
/* 0C548C */ UNK_RET ftCo_800C548C(UNK_PARAMS);
/* 0C54C4 */ UNK_RET ftCo_800C54C4(UNK_PARAMS);
/* 0C554C */ void ftCo_800C554C(ftCo_Fighter* fp);
/* 0C5588 */ UNK_RET ftCo_800C5588(UNK_PARAMS);
/* 0C55CC */ UNK_RET ftCo_800C55CC(UNK_PARAMS);
/* 0C5614 */ UNK_RET ftCo_800C5614(UNK_PARAMS);
/* 0C576C */ UNK_RET ftCo_800C576C(UNK_PARAMS);
/* 0C57B4 */ UNK_RET ftCo_800C57B4(UNK_PARAMS);
/* 0C5A50 */ UNK_RET ftCo_800C5A50(UNK_PARAMS);
/* 0C5A98 */ void ftCo_800C5A98(ftCo_GObj* gobj);
/* 0C5B88 */ UNK_RET ftCo_800C5B88(UNK_PARAMS);
/* 0C5CD4 */ bool ftCo_800C5CD4(ftCo_GObj* gobj);
/* 0C5D34 */ UNK_RET ftCo_800C5D34(UNK_PARAMS);
/* 0C5DDC */ bool ftCo_800C5DDC(ftCo_GObj* gobj);
/* 0C5F88 */ UNK_RET ftCo_800C5F88(UNK_PARAMS);
/* 0C60C8 */ bool ftCo_800C60C8(ftCo_GObj* gobj);
/* 0C6110 */ UNK_RET ftCo_800C6110(UNK_PARAMS);
/* 0C6150 */ UNK_RET ftCo_800C6150(UNK_PARAMS);
/* 0C6408 */ UNK_RET ftCo_800C6408(UNK_PARAMS);
/* 0C6B6C */ UNK_RET ftCo_800C6B6C(UNK_PARAMS);
/* 0C7070 */ UNK_RET ftCo_800C7070(UNK_PARAMS);
/* 0C70D0 */ UNK_RET ftCo_800C70D0(UNK_PARAMS);
/* 0C7178 */ UNK_RET ftCo_800C7178(UNK_PARAMS);
/* 0C7220 */ UNK_RET ftCo_800C7220(UNK_PARAMS);
/* 0C7294 */ UNK_RET ftCo_800C7294(UNK_PARAMS);
/* 0C7308 */ UNK_RET ftCo_800C7308(UNK_PARAMS);
/* 0C739C */ UNK_RET ftCo_800C739C(UNK_PARAMS);
/* 0C7434 */ UNK_RET ftCo_800C7434(UNK_PARAMS);
/* 0C74F4 */ bool ftCo_800C74F4(ftCo_GObj* gobj);
/* 0C7590 */ UNK_RET ftCo_800C7590(UNK_PARAMS);
/* 0C7A30 */ UNK_RET ftCo_800C7A30(UNK_PARAMS);
/* 0C7CA0 */ bool ftCo_800C7CA0(ftCo_GObj* gobj);
/* 0C88D4 */ void ftCo_800C88D4(ftCo_GObj* gobj, int, bool);
/* 0C8B60 */ void ftCo_800C8B60(ftCo_Fighter* fp, int, s8);
/* 0C8B74 */ void ftCo_800C8B74(void);
/* 0C94B4 */ bool ftCo_800C94B4(ftCo_GObj* gobj);
/* 0CB024 */ bool ftCo_800CB024(ftCo_GObj* gobj);
/* 0CB8E0 */ bool ftCo_800CB8E0(ftCo_GObj* gobj);
/* 0CB950 */ UNK_RET ftCo_800CB950(UNK_PARAMS);
/* 0CBAC4 */ UNK_RET ftCo_800CBAC4(UNK_PARAMS);
/* 0CBBC0 */ UNK_RET ftCo_800CBBC0(UNK_PARAMS);
/* 0CBD18 */ UNK_RET ftCo_800CBD18(UNK_PARAMS);
/* 0CBE98 */ UNK_RET ftCo_800CBE98(UNK_PARAMS);
/* 0CC0E8 */ UNK_RET ftCo_800CC0E8(UNK_PARAMS);
/* 0CC238 */ UNK_RET ftCo_800CC238(UNK_PARAMS);
/* 0CC830 */ UNK_RET ftCo_800CC830(UNK_PARAMS);
/* 0CC988 */ void ftCo_800CC988(ftCo_GObj* gobj, float);
/* 0CCBE0 */ void ftCo_800CCBE0(ftCo_GObj* gobj, float*, FtMotionId,
                                FtMotionId, FtMotionId);
/* 0CD140 */ UNK_RET ftCo_800CD140(UNK_PARAMS);
/* 0CD1BC */ UNK_RET ftCo_800CD1BC(UNK_PARAMS);
/* 0CD204 */ UNK_RET ftCo_800CD204(UNK_PARAMS);
/* 0CD278 */ UNK_RET ftCo_800CD278(UNK_PARAMS);
/* 0CD2C4 */ UNK_RET ftCo_800CD2C4(UNK_PARAMS);
/* 0CD350 */ UNK_RET ftCo_800CD350(UNK_PARAMS);
/* 0CD418 */ UNK_RET ftCo_800CD418(UNK_PARAMS);
/* 0CD4E0 */ UNK_RET ftCo_800CD4E0(UNK_PARAMS);
/* 0CD5A8 */ UNK_RET ftCo_800CD5A8(UNK_PARAMS);
/* 0CD82C */ UNK_RET ftCo_800CD82C(UNK_PARAMS);
/* 0CDAB4 */ UNK_RET ftCo_800CDAB4(UNK_PARAMS);
/* 0CDE18 */ UNK_RET ftCo_800CDE18(UNK_PARAMS);
/* 0CDE54 */ UNK_RET ftCo_800CDE54(UNK_PARAMS);
/* 0CDE74 */ UNK_RET ftCo_800CDE74(UNK_PARAMS);
/* 0CDE94 */ UNK_RET ftCo_800CDE94(UNK_PARAMS);
/* 0CDF5C */ UNK_RET ftCo_800CDF5C(UNK_PARAMS);
/* 0CE010 */ UNK_RET ftCo_800CE010(UNK_PARAMS);
/* 0CE3E0 */ UNK_RET ftCo_800CE3E0(UNK_PARAMS);
/* 0CE480 */ UNK_RET ftCo_800CE480(UNK_PARAMS);
/* 0CECE8 */ bool ftCo_800CECE8(ftCo_GObj* gobj);
/* 0CED30 */ UNK_RET ftCo_800CED30(UNK_PARAMS);
/* 0CEE70 */ bool ftCo_800CEE70(ftCo_GObj* gobj);
/* 0CF138 */ float ftCo_CalcYScaledKnockback(float*, float, float, float);
/* 0CF3C8 */ UNK_RET ftCo_800CF3C8(UNK_PARAMS);
/* 0CF4DC */ void ftCo_800CF4DC(ftCo_GObj* gobj);
/* 0CF6E8 */ UNK_RET ftCo_800CF6E8(UNK_PARAMS);
/* 0D0CBC */ UNK_RET ftCo_800D0CBC(UNK_PARAMS);
/* 0D15D0 */ UNK_RET ftCo_800D15D0(UNK_PARAMS);
/* 0D170C */ UNK_RET ftCo_800D170C(UNK_PARAMS);
/* 0D18CC */ UNK_RET ftCo_800D18CC(UNK_PARAMS);
/* 0D1B04 */ UNK_RET ftCo_800D1B04(UNK_PARAMS);
/* 0D1BA0 */ UNK_RET ftCo_800D1BA0(UNK_PARAMS);
/* 0D1D10 */ UNK_RET ftCo_800D1D10(UNK_PARAMS);
/* 0D1F6C */ UNK_RET ftCo_800D1F6C(UNK_PARAMS);
/* 0D1FFC */ UNK_RET ftCo_800D1FFC(UNK_PARAMS);
/* 0D21BC */ UNK_RET ftCo_800D21BC(UNK_PARAMS);
/* 0D23F4 */ UNK_RET ftCo_800D23F4(UNK_PARAMS);
/* 0D2490 */ UNK_RET ftCo_800D2490(UNK_PARAMS);
/* 0D2600 */ UNK_RET ftCo_800D2600(UNK_PARAMS);
/* 0D2770 */ UNK_RET ftCo_800D2770(UNK_PARAMS);
/* 0D27C4 */ UNK_RET ftCo_800D27C4(UNK_PARAMS);
/* 0D2FA4 */ bool ftCo_800D2FA4(ftCo_GObj* gobj);
/* 0D3004 */ UNK_RET ftCo_800D3004(UNK_PARAMS);
/* 0D331C */ UNK_RET ftCo_800D331C(UNK_PARAMS);
/* 0D34E0 */ UNK_RET ftCo_800D34E0(UNK_PARAMS);
/* 0D35FC */ UNK_RET ftCo_800D35FC(UNK_PARAMS);
/* 0D3680 */ UNK_RET ftCo_800D3680(UNK_PARAMS);
/* 0D38B8 */ UNK_RET ftCo_800D38B8(UNK_PARAMS);
/* 0D3950 */ UNK_RET ftCo_800D3950(UNK_PARAMS);
/* 0D3E40 */ UNK_RET ftCo_800D3E40(UNK_PARAMS);
/* 0D40B8 */ UNK_RET ftCo_800D40B8(UNK_PARAMS);
/* 0D41C4 */ UNK_RET ftCo_800D41C4(UNK_PARAMS);
/* 0D4580 */ UNK_RET ftCo_800D4580(UNK_PARAMS);
/* 0D4780 */ UNK_RET ftCo_800D4780(UNK_PARAMS);
/* 0D47B8 */ UNK_RET ftCo_800D47B8(UNK_PARAMS);
/* 0D481C */ UNK_RET ftCo_800D481C(UNK_PARAMS);
/* 0D4E50 */ UNK_RET ftCo_800D4E50(UNK_PARAMS);
/* 0D5600 */ UNK_RET ftCo_800D5600(UNK_PARAMS);
/* 0D5B70 */ UNK_RET ftCo_800D5B70(UNK_PARAMS);
/* 0D5B80 */ UNK_RET ftCo_800D5B80(UNK_PARAMS);
/* 0D5B9C */ UNK_RET ftCo_800D5B9C(UNK_PARAMS);
/* 0D5FB0 */ bool ftCo_800D5FB0(ftCo_GObj* gobj);
/* 0D69C4 */ bool ftCo_800D69C4(ftCo_GObj* gobj);
/* 0D705C */ bool ftCo_800D705C(ftCo_GObj* gobj);
/* 0D7100 */ bool ftCo_800D7100(ftCo_GObj* gobj);
/* 0D8A38 */ UNK_RET ftCo_800D8A38(UNK_PARAMS);
/* 0D8AE0 */ bool ftCo_800D8AE0(void);
/* 0D8B9C */ bool ftCo_800D8B9C(ftCo_GObj* gobj);
/* 0D8C54 */ UNK_RET ftCo_800D8C54(UNK_PARAMS);
/* 0DC3A4 */ void ftCo_800DC3A4(ftCo_GObj* gobj);
/* 0DCE34 */ void ftCo_800DCE34(ftCo_GObj* gobj0, ftCo_GObj* gobj1);
/* 0DCFD4 */ void ftCo_800DCFD4(ftCo_GObj* gobj);
/* 0DD100 */ UNK_RET ftCo_800DD100(UNK_PARAMS);
/* 0DD1E4 */ UNK_RET ftCo_800DD1E4(UNK_PARAMS);
/* 0DD398 */ UNK_RET ftCo_800DD398(UNK_PARAMS);
/* 0DD4B0 */ UNK_RET ftCo_800DD4B0(UNK_PARAMS);
/* 0DD724 */ void ftCo_800DD724(ftCo_GObj* gobj);
/* 0DDDE4 */ UNK_RET ftCo_800DDDE4(UNK_PARAMS);
/* 0DE2F0 */ void ftCo_800DE2F0(ftCo_GObj* gobj);
/* 0DE3FC */ bool ftCo_800DE3FC(ftCo_GObj* gobj, FtMotionId msid, float arg2);
/* 0DE5A4 */ UNK_RET ftCo_800DE5A4(UNK_PARAMS);
/* 0DE854 */ void ftCo_800DE854(ftCo_GObj* gobj);
/* 0DE920 */ UNK_RET ftCo_800DE920(UNK_PARAMS);
/* 0DE974 */ UNK_RET ftCo_800DE974(UNK_PARAMS);
/* 0DE9B8 */ UNK_RET ftCo_800DE9B8(UNK_PARAMS);
/* 0DE9D8 */ bool ftCo_800DE9D8(ftCo_GObj* gobj);
/* 0DEA28 */ UNK_RET ftCo_800DEA28(UNK_PARAMS);
/* 0DEBD0 */ UNK_RET ftCo_800DEBD0(UNK_PARAMS);
/* 0DEE84 */ void ftCo_800DEE84(int, u8, char*, u32, float, float);
/* 0DF1C8 */ bool ftCo_800DF1C8(ftCo_Fighter* fp);
/* 0DF2D8 */ bool ftCo_800DF2D8(ftCo_Fighter* fp);
/* 0DF30C */ bool ftCo_800DF30C(ftCo_Fighter* fp);
/* 0DF3A8 */ bool ftCo_800DF3A8(ftCo_Fighter* fp);
/* 0DF3DC */ bool ftCo_800DF3DC(ftCo_Fighter* fp);
/* 0DF50C */ bool ftCo_800DF50C(ftCo_Fighter* fp);
/* 0DF608 */ bool ftCo_800DF608(ftCo_Fighter* fp);
/* 0DF644 */ bool ftCo_800DF644(ftCo_Fighter* fp);
/* 0DF678 */ bool ftCo_800DF678(Fighter* fp);
/* 0DF6F8 */ bool ftCo_800DF6F8(ftCo_Fighter* fp);
/* 0DF72C */ bool ftCo_800DF72C(ftCo_Fighter* fp);
/* 0DF79C */ bool ftCo_800DF79C(ftCo_Fighter* fp);
/* 0DF7F4 */ UNK_RET ftCo_800DF7F4(UNK_PARAMS);
/* 0DF844 */ UNK_RET ftCo_800DF844(UNK_PARAMS);
/* 0DF878 */ UNK_RET ftCo_800DF878(UNK_PARAMS);
/* 0DF8B0 */ bool ftCo_800DF8B0(ftCo_Fighter* fp);
/* 0DF8E8 */ bool ftCo_800DF8E8(ftCo_Fighter* fp);
/* 0DF910 */ UNK_RET ftCo_800DF910(UNK_PARAMS);
bool ftCo_8009EF68(Fighter_GObj* gobj);
bool ftCo_800BFFD0(Fighter*, int, int);
bool ftCo_800C0694(Fighter*);
bool ftCo_800C5240(Fighter_GObj* gobj);
bool ftCo_800C8B2C(Fighter*, bool, bool);
bool ftCo_800C97A8(Fighter_GObj* gobj);
bool ftCo_800CAE80(Fighter_GObj* gobj);
bool ftCo_800CB870(Fighter_GObj* gobj);
bool ftCo_800D6824(Fighter_GObj* gobj);
bool ftCo_800D68C0(Fighter_GObj* gobj);
bool ftCo_800DF478(Fighter*);
bool ftCo_Attack100_CheckInput(Fighter_GObj* gobj);
bool ftCo_AttackLw4_CheckInput(Fighter_GObj* gobj);
bool ftCo_Catch_CheckInput(Fighter_GObj* gobj);
bool ftCo_Dash_CheckInput(Fighter_GObj* gobj);
bool ftCo_Jump_CheckInput(Fighter_GObj* gobj);
bool ftCo_Squat_CheckInput(Fighter_GObj* gobj);
bool ftCo_Turn_CheckInput(Fighter_GObj* gobj);
bool ftCo_Walk_CheckInput(Fighter_GObj* gobj);
f32 ftCo_800A17E4(Fighter*);
f32 ftCo_800A1874(Fighter*);
f32 ftCo_800A1904(Fighter*);
f32 ftCo_800A1948(Fighter*);
f32 ftCo_800A1994(Fighter*);
f32 ftCo_800A1A24(Fighter*);
f32 ftCo_800DA824(Fighter*);
Fighter_GObj* ftCo_800BE7E0(unk_t);
float ftCo_800D0EC8(Fighter* fp);
s32 ftCo_800A198C(Fighter*);
s32 ftCo_800D67C4(Fighter*);
s32 ftCo_800D688C(Fighter*);
s32 ftCo_800D6928(Fighter*);
u32 ftCo_800DEEE8(Fighter*, Vec2*);
UNK_RET ftCo_800C8D00(Fighter_GObj* gobj);
UNK_RET ftCo_800CC6C8(UNK_PARAMS);
unk_t ftCo_8009EDA4(void);
unk_t ftCo_8009F39C(void);
unk_t ftCo_800C703C(void);
void ftCo_800928CC(Fighter_GObj* gobj);
void ftCo_80092BCC(Fighter_GObj* gobj);
void ftCo_80092BE8(Fighter_GObj* gobj);
void ftCo_80093BC0(Fighter_GObj* gobj);
void ftCo_8009750C(Fighter_GObj* gobj);
void ftCo_8009CF84(Fighter*);
void ftCo_8009DC54(Fighter*);
void ftCo_8009E0A8(Fighter_GObj* gobj);
void ftCo_8009E0D4(Fighter*);
void ftCo_8009E7B4(Fighter*, u8*);
void ftCo_8009F4A4(void);
void ftCo_8009F578(Fighter*);
void ftCo_800A0DA4(Fighter*);
void ftCo_800A101C(Fighter*, s8, s8, s32);
void ftCo_800B3900(Fighter_GObj* gobj);
void ftCo_800BC7E0(Fighter_GObj*, Fighter_GObj* gobj);
void ftCo_800BC8D4(Fighter_GObj*, Fighter_GObj* gobj);
void ftCo_800BC9C8(Fighter_GObj* gobj);
void ftCo_800BCE64(Fighter_GObj*, enum_t msid);
void ftCo_800BCF18(Fighter_GObj*, Fighter_GObj* gobj);
void ftCo_800BD000(Fighter_GObj*, Fighter_GObj* gobj);
void ftCo_800BEB60(int, int, int);
void ftCo_800BED84(Fighter_GObj* gobj);
void ftCo_800BEF00(Fighter_GObj* gobj);
void ftCo_800BEFD0(Fighter_GObj* gobj);
void ftCo_800BFB4C(Fighter_GObj*, s32*);
void ftCo_800BFD04(Fighter_GObj* gobj);
void ftCo_800BFFAC(Fighter*);
void ftCo_800C0074(Fighter*);
void ftCo_800C0134(Fighter*);
void ftCo_800C0200(Fighter*, int);
void ftCo_800C0358(Fighter*, Fighter*, s32);
void ftCo_800C0408(Fighter_GObj* gobj);
void ftCo_800C06C0(void);
void ftCo_800C09B4(Fighter_GObj* gobj);
void ftCo_800C0A98(Fighter_GObj* gobj);
void ftCo_800C1E64(Fighter_GObj* pPlayerEntityStruct, s32, s32, u8, f32);
void ftCo_800C2FD8(Fighter_GObj* gobj);
void ftCo_800C37A0(Fighter_GObj* gobj);
void ftCo_800C511C(Fighter_GObj* gobj);
void ftCo_800C5500(Fighter_GObj* gobj);
void ftCo_800C555C(Fighter_GObj* gobj);
void ftCo_800C61B0(Fighter_GObj* gobj);
void ftCo_800C7158(Fighter_GObj* gobj);
void ftCo_800C7200(Fighter_GObj* gobj);
void ftCo_800C737C(Fighter_GObj* gobj);
void ftCo_800C7414(Fighter_GObj* gobj);
void ftCo_800C74AC(Fighter_GObj* gobj);
void ftCo_800C8064(void);
void ftCo_800C8348(Fighter_GObj*, s32, s32);
void ftCo_800C8438(Fighter_GObj* gobj);
void ftCo_800C8540(Fighter_GObj* gobj);
void ftCo_800C884C(Fighter_GObj* gobj);
void ftCo_800C88A0(Fighter*);
void ftCo_800C89A0(Fighter_GObj* gobj);
void ftCo_800C8A64(Fighter_GObj* gobj);
void ftCo_800C8C84(Fighter_GObj* gobj);
void ftCo_800C8F6C(void);
void ftCo_800C8FC4(Fighter_GObj* gobj);
void ftCo_800C9034(Fighter_GObj* gobj);
void ftCo_800C9840(Fighter_GObj*, s32, s32, f32, f32, f32);
void ftCo_800C9924(Fighter_GObj* gobj);
void ftCo_800CB110(Fighter_GObj*, s32, f32);
void ftCo_800CB438(Fighter_GObj* gobj);
void ftCo_800CB59C(Fighter_GObj* gobj);
void ftCo_800CC730(Fighter_GObj* gobj);
void ftCo_800CCAAC(Fighter_GObj* gobj);
void ftCo_800CCDA8(Fighter_GObj* gobj);
void ftCo_800CDDA0(Fighter_GObj* gobj);
void ftCo_800CEFE0(Fighter_GObj* gobj, int);
void ftCo_800D0FA0(Fighter_GObj* gobj);
void ftCo_800D105C(Fighter_GObj* gobj);
void ftCo_800D14E4(Fighter_GObj* gobj);
void ftCo_800D1A8C(Fighter_GObj* gobj);
void ftCo_800D1E80(Fighter_GObj* gobj);
void ftCo_800D237C(Fighter_GObj* gobj);
void ftCo_800D3158(Fighter_GObj* gobj);
void ftCo_800D4F24(Fighter_GObj*, s32);
void ftCo_800D4FF4(Fighter_GObj* gobj);
void ftCo_800D5AEC(Fighter_GObj*, s32, s32, s32, f32, f32);
void ftCo_800D5BF8(Fighter_GObj* gobj);
void ftCo_800D5CB0(Fighter_GObj*, bool, float landing_lag);
void ftCo_800D638C(Fighter_GObj* gobj);
void ftCo_800D6B00(Fighter_GObj*, s32);
void ftCo_800D6C60(Fighter_GObj*, HSD_GObjEvent);
void ftCo_800D6C60(Fighter_GObj*, HSD_GObjEvent callback);
void ftCo_800D71D8(Fighter_GObj* gobj);
void ftCo_800D94D8(Fighter_GObj* gobj);
void ftCo_800D9C98(Fighter_GObj* gobj);
void ftCo_800DB368(Fighter*, Fighter*);
void ftCo_800DB464(Fighter_GObj* gobj);
void ftCo_800DC750(Fighter_GObj* gobj);
void ftCo_800DC920(Fighter_GObj*, Fighter_GObj* gobj);
void ftCo_800DD168(Fighter_GObj* gobj);
void ftCo_800DE2A8(Fighter_GObj*, Fighter_GObj* gobj);
void ftCo_800DE508(Fighter_GObj* gobj);
void ftCo_800DE7C0(Fighter_GObj*, s32, s32);
void ftCo_800DEAE8(Fighter_GObj* gobj, enum_t asid0, enum_t asid1);
void ftCo_800DEEA8(Fighter_GObj* gobj);
void ftCo_800DEEB8(void);
void ftCo_800DEF38(Fighter_GObj* gobj);
void ftCo_800DF0D0(Fighter_GObj* gobj);
void ftCo_AirCatch_Anim(Fighter_GObj* gobj);
void ftCo_AirCatch_Coll(Fighter_GObj* gobj);
void ftCo_AirCatchHit_Anim(Fighter_GObj* gobj);
void ftCo_AirCatchHit_IASA(Fighter_GObj* gobj);
void ftCo_AirCatchHit_Phys(Fighter_GObj* gobj);
void ftCo_AirCatch_IASA(Fighter_GObj* gobj);
void ftCo_AirCatch_Phys(Fighter_GObj* gobj);
void ftCo_AppealS_Anim(Fighter_GObj* gobj);
void ftCo_AppealS_Coll(Fighter_GObj* gobj);
void ftCo_AppealS_IASA(Fighter_GObj* gobj);
void ftCo_AppealS_Phys(Fighter_GObj* gobj);
void ftCo_Attack100End_Anim(Fighter_GObj* gobj);
void ftCo_Attack100End_Coll(Fighter_GObj* gobj);
void ftCo_Attack100End_Phys(Fighter_GObj* gobj);
void ftCo_Attack100Loop_Anim(Fighter_GObj* gobj);
void ftCo_Attack100Loop_Coll(Fighter_GObj* gobj);
void ftCo_Attack100Loop_IASA(Fighter_GObj* gobj);
void ftCo_Attack100Loop_Phys(Fighter_GObj* gobj);
void ftCo_Attack100Start_Anim(Fighter_GObj* gobj);
void ftCo_Attack100Start_Coll(Fighter_GObj* gobj);
void ftCo_Attack100Start_Phys(Fighter_GObj* gobj);
void ftCo_AttackS42_Anim(Fighter_GObj* gobj);
void ftCo_AttackS42_Coll(Fighter_GObj* gobj);
void ftCo_AttackS42_IASA(Fighter_GObj* gobj);
void ftCo_AttackS42_Phys(Fighter_GObj* gobj);
void ftCo_Barrel_Anim(Fighter_GObj* gobj);
void ftCo_Barrel_Coll(Fighter_GObj* gobj);
void ftCo_Barrel_IASA(Fighter_GObj* gobj);
void ftCo_Barrel_Phys(Fighter_GObj* gobj);
void ftCo_BarrelWait_Anim(Fighter_GObj* gobj);
void ftCo_BarrelWait_Coll(Fighter_GObj* gobj);
void ftCo_BarrelWait_IASA(Fighter_GObj* gobj);
void ftCo_BarrelWait_Phys(Fighter_GObj* gobj);
void ftCo_BatSwing_Anim(Fighter_GObj* gobj);
void ftCo_BatSwing_Coll(Fighter_GObj* gobj);
void ftCo_BatSwing_IASA(Fighter_GObj* gobj);
void ftCo_BatSwing_Phys(Fighter_GObj* gobj);
void ftCo_Bury_Anim(Fighter_GObj* gobj);
void ftCo_Bury_Coll(Fighter_GObj* gobj);
void ftCo_Bury_IASA(Fighter_GObj* gobj);
void ftCo_BuryJump_Anim(Fighter_GObj* gobj);
void ftCo_BuryJump_Coll(Fighter_GObj* gobj);
void ftCo_BuryJump_IASA(Fighter_GObj* gobj);
void ftCo_BuryJump_Phys(Fighter_GObj* gobj);
void ftCo_Bury_Phys(Fighter_GObj* gobj);
void ftCo_BuryWait_Anim(Fighter_GObj* gobj);
void ftCo_BuryWait_Coll(Fighter_GObj* gobj);
void ftCo_BuryWait_IASA(Fighter_GObj* gobj);
void ftCo_BuryWait_Phys(Fighter_GObj* gobj);
void ftCo_CaptureCaptain_Anim(Fighter_GObj* gobj);
void ftCo_CaptureCaptain_Coll(Fighter_GObj* gobj);
void ftCo_CaptureCaptain_IASA(Fighter_GObj* gobj);
void ftCo_CaptureCaptain_Phys(Fighter_GObj* gobj);
void ftCo_CaptureCut_Anim(Fighter_GObj* gobj);
void ftCo_CaptureCut_Coll(Fighter_GObj* gobj);
void ftCo_CaptureCut_IASA(Fighter_GObj* gobj);
void ftCo_CaptureCut_Phys(Fighter_GObj* gobj);
void ftCo_CaptureDamageHi_Anim(Fighter_GObj* gobj);
void ftCo_CaptureDamageHi_Coll(Fighter_GObj* gobj);
void ftCo_CaptureDamageHi_IASA(Fighter_GObj* gobj);
void ftCo_CaptureDamageHi_Phys(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_Anim(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_Coll(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_IASA(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopaAir_Phys(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopa_Anim(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopa_Coll(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopa_IASA(Fighter_GObj* gobj);
void ftCo_CaptureDamageKoopa_Phys(Fighter_GObj* gobj);
void ftCo_CaptureDamageLw_Anim(Fighter_GObj* gobj);
void ftCo_CaptureDamageLw_Coll(Fighter_GObj* gobj);
void ftCo_CaptureDamageLw_IASA(Fighter_GObj* gobj);
void ftCo_CaptureDamageLw_Phys(Fighter_GObj* gobj);
void ftCo_CaptureJump_Anim(Fighter_GObj* gobj);
void ftCo_CaptureJump_Coll(Fighter_GObj* gobj);
void ftCo_CaptureJump_IASA(Fighter_GObj* gobj);
void ftCo_CaptureJump_Phys(Fighter_GObj* gobj);
void ftCo_CaptureKirby_Anim(Fighter_GObj* gobj);
void ftCo_CaptureKirby_Coll(Fighter_GObj* gobj);
void ftCo_CaptureKirby_IASA(Fighter_GObj* gobj);
void ftCo_CaptureKirby_Phys(Fighter_GObj* gobj);
void ftCo_CaptureKoopaAir_Anim(Fighter_GObj* gobj);
void ftCo_CaptureKoopaAir_Coll(Fighter_GObj* gobj);
void ftCo_CaptureKoopaAir_IASA(Fighter_GObj* gobj);
void ftCo_CaptureKoopaAir_Phys(Fighter_GObj* gobj);
void ftCo_CaptureKoopa_Anim(Fighter_GObj* gobj);
void ftCo_CaptureKoopa_Coll(Fighter_GObj* gobj);
void ftCo_CaptureKoopa_IASA(Fighter_GObj* gobj);
void ftCo_CaptureKoopa_Phys(Fighter_GObj* gobj);
void ftCo_CaptureLeadead_Anim(Fighter_GObj* gobj);
void ftCo_CaptureLeadead_Coll(Fighter_GObj* gobj);
void ftCo_CaptureLeadead_IASA(Fighter_GObj* gobj);
void ftCo_CaptureLeadead_Phys(Fighter_GObj* gobj);
void ftCo_CaptureLikelike_Anim(Fighter_GObj* gobj);
void ftCo_CaptureLikelike_Coll(Fighter_GObj* gobj);
void ftCo_CaptureLikelike_IASA(Fighter_GObj* gobj);
void ftCo_CaptureLikelike_Phys(Fighter_GObj* gobj);
void ftCo_CapturePulledHi_Anim(Fighter_GObj* gobj);
void ftCo_CapturePulledHi_Coll(Fighter_GObj* gobj);
void ftCo_CapturePulledHi_IASA(Fighter_GObj* gobj);
void ftCo_CapturePulledHi_Phys(Fighter_GObj* gobj);
void ftCo_CapturePulledLw_Anim(Fighter_GObj* gobj);
void ftCo_CapturePulledLw_Coll(Fighter_GObj* gobj);
void ftCo_CapturePulledLw_IASA(Fighter_GObj* gobj);
void ftCo_CapturePulledLw_Phys(Fighter_GObj* gobj);
void ftCo_CaptureWaitHi_Anim(Fighter_GObj* gobj);
void ftCo_CaptureWaitHi_Coll(Fighter_GObj* gobj);
void ftCo_CaptureWaitHi_IASA(Fighter_GObj* gobj);
void ftCo_CaptureWaitHi_Phys(Fighter_GObj* gobj);
void ftCo_CaptureWaitKirby_Anim(Fighter_GObj* gobj);
void ftCo_CaptureWaitKirby_Coll(Fighter_GObj* gobj);
void ftCo_CaptureWaitKirby_IASA(Fighter_GObj* gobj);
void ftCo_CaptureWaitKirby_Phys(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_Anim(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_Coll(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_IASA(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopaAir_Phys(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopa_Anim(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopa_Coll(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopa_IASA(Fighter_GObj* gobj);
void ftCo_CaptureWaitKoopa_Phys(Fighter_GObj* gobj);
void ftCo_CaptureWaitLw_Anim(Fighter_GObj* gobj);
void ftCo_CaptureWaitLw_Coll(Fighter_GObj* gobj);
void ftCo_CaptureWaitLw_IASA(Fighter_GObj* gobj);
void ftCo_CaptureWaitLw_Phys(Fighter_GObj* gobj);
void ftCo_CaptureYoshi_Anim(Fighter_GObj* gobj);
void ftCo_CaptureYoshi_Coll(Fighter_GObj* gobj);
void ftCo_CaptureYoshi_IASA(Fighter_GObj* gobj);
void ftCo_CaptureYoshi_Phys(Fighter_GObj* gobj);
void ftCo_CargoFall_Anim(Fighter_GObj* gobj);
void ftCo_CargoFall_Coll(Fighter_GObj* gobj);
void ftCo_CargoFall_IASA(Fighter_GObj* gobj);
void ftCo_CargoFall_Phys(Fighter_GObj* gobj);
void ftCo_CargoKneebend_Anim(Fighter_GObj* gobj);
void ftCo_CargoKneebend_Coll(Fighter_GObj* gobj);
void ftCo_CargoKneebend_IASA(Fighter_GObj* gobj);
void ftCo_CargoKneebend_Phys(Fighter_GObj* gobj);
void ftCo_CargoLanding_Anim(Fighter_GObj* gobj);
void ftCo_CargoLanding_Coll(Fighter_GObj* gobj);
void ftCo_CargoLanding_Phys(Fighter_GObj* gobj);
void ftCo_CargoThrowAir_Anim(Fighter_GObj* gobj);
void ftCo_CargoThrowAir_Coll(Fighter_GObj* gobj);
void ftCo_CargoThrowAir_IASA(Fighter_GObj* gobj);
void ftCo_CargoThrowAir_Phys(Fighter_GObj* gobj);
void ftCo_CargoThrowB_Anim(Fighter_GObj* gobj);
void ftCo_CargoThrowB_Coll(Fighter_GObj* gobj);
void ftCo_CargoThrowB_IASA(Fighter_GObj* gobj);
void ftCo_CargoThrowB_Phys(Fighter_GObj* gobj);
void ftCo_CargoThrowF_Anim(Fighter_GObj* gobj);
void ftCo_CargoThrowF_Coll(Fighter_GObj* gobj);
void ftCo_CargoThrowF_IASA(Fighter_GObj* gobj);
void ftCo_CargoThrowF_Phys(Fighter_GObj* gobj);
void ftCo_CargoThrowHi_Anim(Fighter_GObj* gobj);
void ftCo_CargoThrowHi_Coll(Fighter_GObj* gobj);
void ftCo_CargoThrowHi_IASA(Fighter_GObj* gobj);
void ftCo_CargoThrowHi_Phys(Fighter_GObj* gobj);
void ftCo_CargoThrowLw_Anim(Fighter_GObj* gobj);
void ftCo_CargoThrowLw_Coll(Fighter_GObj* gobj);
void ftCo_CargoThrowLw_IASA(Fighter_GObj* gobj);
void ftCo_CargoThrowLw_Phys(Fighter_GObj* gobj);
void ftCo_CargoTurn_Anim(Fighter_GObj* gobj);
void ftCo_CargoTurn_Coll(Fighter_GObj* gobj);
void ftCo_CargoTurn_IASA(Fighter_GObj* gobj);
void ftCo_CargoTurn_Phys(Fighter_GObj* gobj);
void ftCo_CargoWait2_Anim(Fighter_GObj* gobj);
void ftCo_CargoWait2_Coll(Fighter_GObj* gobj);
void ftCo_CargoWait2_Phys(Fighter_GObj* gobj);
void ftCo_CargoWait_Anim(Fighter_GObj* gobj);
void ftCo_CargoWait_Coll(Fighter_GObj* gobj);
void ftCo_CargoWait_IASA(Fighter_GObj* gobj);
void ftCo_CargoWait_Phys(Fighter_GObj* gobj);
void ftCo_Catch_Anim(Fighter_GObj* gobj);
void ftCo_CatchAttack_Anim(Fighter_GObj* gobj);
void ftCo_CatchAttack_Coll(Fighter_GObj* gobj);
void ftCo_CatchAttack_IASA(Fighter_GObj* gobj);
void ftCo_CatchAttack_Phys(Fighter_GObj* gobj);
void ftCo_Catch_Coll(Fighter_GObj* gobj);
void ftCo_CatchCut_Anim(Fighter_GObj* gobj);
void ftCo_CatchCut_Coll(Fighter_GObj* gobj);
void ftCo_CatchCut_IASA(Fighter_GObj* gobj);
void ftCo_CatchCut_Phys(Fighter_GObj* gobj);
void ftCo_CatchDash_Anim(Fighter_GObj* gobj);
void ftCo_CatchDash_Coll(Fighter_GObj* gobj);
void ftCo_CatchDash_IASA(Fighter_GObj* gobj);
void ftCo_CatchDash_Phys(Fighter_GObj* gobj);
void ftCo_Catch_IASA(Fighter_GObj* gobj);
void ftCo_Catch_Phys(Fighter_GObj* gobj);
void ftCo_CatchPull_Anim(Fighter_GObj* gobj);
void ftCo_CatchPull_Coll(Fighter_GObj* gobj);
void ftCo_CatchPull_IASA(Fighter_GObj* gobj);
void ftCo_CatchPull_Phys(Fighter_GObj* gobj);
void ftCo_CatchWait_Anim(Fighter_GObj* gobj);
void ftCo_CatchWait_Coll(Fighter_GObj* gobj);
void ftCo_CatchWait_IASA(Fighter_GObj* gobj);
void ftCo_CatchWait_Phys(Fighter_GObj* gobj);
void ftCo_CliffAttack_Anim(Fighter_GObj* gobj);
void ftCo_CliffAttack_Coll(Fighter_GObj* gobj);
void ftCo_CliffAttack_IASA(Fighter_GObj* gobj);
void ftCo_CliffAttack_Phys(Fighter_GObj* gobj);
void ftCo_Cliff_Cam(ftCo_GObj* gobj);
void ftCo_CliffCatch_Anim(ftCo_GObj* gobj);
void ftCo_CliffCatch_Coll(ftCo_GObj* gobj);
void ftCo_CliffCatch_IASA(ftCo_GObj*);
void ftCo_CliffCatch_Phys(ftCo_GObj* gobj);
void ftCo_CliffClimb_Coll(Fighter_GObj* gobj);
void ftCo_CliffClimb_IASA(Fighter_GObj* gobj);
void ftCo_CliffClimb_Phys(Fighter_GObj* gobj);
void ftCo_CliffEscape_Anim(Fighter_GObj* gobj);
void ftCo_CliffEscape_Coll(Fighter_GObj* gobj);
void ftCo_CliffEscape_IASA(Fighter_GObj* gobj);
void ftCo_CliffEscape_Phys(Fighter_GObj* gobj);
void ftCo_CliffJump1_Anim(Fighter_GObj* gobj);
void ftCo_CliffJump1_Coll(Fighter_GObj* gobj);
void ftCo_CliffJump1_IASA(Fighter_GObj* gobj);
void ftCo_CliffJump1_Phys(Fighter_GObj* gobj);
void ftCo_CliffJump2_Anim(Fighter_GObj* gobj);
void ftCo_CliffJump2_Coll(Fighter_GObj* gobj);
void ftCo_CliffJump2_IASA(Fighter_GObj* gobj);
void ftCo_CliffJump2_Phys(Fighter_GObj* gobj);
void ftCo_CliffWait_Anim(Fighter_GObj* gobj);
void ftCo_CliffWait_Coll(Fighter_GObj* gobj);
void ftCo_CliffWait_IASA(Fighter_GObj* gobj);
void ftCo_CliffWait_Phys(Fighter_GObj* gobj);
void ftCo_Damage_Anim(Fighter_GObj* gobj);
void ftCo_DamageBind_Anim(Fighter_GObj* gobj);
void ftCo_DamageBind_Coll(Fighter_GObj* gobj);
void ftCo_DamageBind_IASA(Fighter_GObj* gobj);
void ftCo_DamageBind_Phys(Fighter_GObj* gobj);
void ftCo_Damage_Coll(Fighter_GObj* gobj);
void ftCo_DamageFall_Anim(Fighter_GObj* gobj);
void ftCo_DamageFall_Coll(Fighter_GObj* gobj);
void ftCo_DamageFall_IASA(Fighter_GObj* gobj);
void ftCo_DamageFall_Phys(Fighter_GObj* gobj);
void ftCo_DamageFly_Anim(Fighter_GObj* gobj);
void ftCo_DamageFly_Coll(Fighter_GObj* gobj);
void ftCo_DamageFly_IASA(Fighter_GObj* gobj);
void ftCo_DamageFly_Phys(Fighter_GObj* gobj);
void ftCo_DamageFlyRoll_Anim(Fighter_GObj* gobj);
void ftCo_DamageFlyRoll_Coll(Fighter_GObj* gobj);
void ftCo_DamageFlyRoll_IASA(Fighter_GObj* gobj);
void ftCo_DamageFlyRoll_Phys(Fighter_GObj* gobj);
void ftCo_Damage_IASA(Fighter_GObj* gobj);
void ftCo_DamageIce_Anim(Fighter_GObj* gobj);
void ftCo_DamageIce_Coll(Fighter_GObj* gobj);
void ftCo_DamageIce_IASA(Fighter_GObj* gobj);
void ftCo_DamageIceJump_Anim(Fighter_GObj* gobj);
void ftCo_DamageIceJump_Coll(Fighter_GObj* gobj);
void ftCo_DamageIceJump_IASA(Fighter_GObj* gobj);
void ftCo_DamageIceJump_Phys(Fighter_GObj* gobj);
void ftCo_DamageIce_Phys(Fighter_GObj* gobj);
void ftCo_Damage_Phys(Fighter_GObj* gobj);
void ftCo_DamageScrew_Anim(Fighter_GObj* gobj);
void ftCo_DamageScrew_Coll(Fighter_GObj* gobj);
void ftCo_DamageScrew_IASA(Fighter_GObj* gobj);
void ftCo_DamageScrew_Phys(Fighter_GObj* gobj);
void ftCo_DamageSong_Anim(Fighter_GObj* gobj);
void ftCo_DamageSong_Coll(Fighter_GObj* gobj);
void ftCo_DamageSong_IASA(Fighter_GObj* gobj);
void ftCo_DamageSong_Phys(Fighter_GObj* gobj);
void ftCo_DamageSongRv_Anim(Fighter_GObj* gobj);
void ftCo_DamageSongRv_Coll(Fighter_GObj* gobj);
void ftCo_DamageSongRv_IASA(Fighter_GObj* gobj);
void ftCo_DamageSongRv_Phys(Fighter_GObj* gobj);
void ftCo_DamageSongWait_Anim(Fighter_GObj* gobj);
void ftCo_DamageSongWait_Coll(Fighter_GObj* gobj);
void ftCo_DamageSongWait_IASA(Fighter_GObj* gobj);
void ftCo_DamageSongWait_Phys(Fighter_GObj* gobj);
void ftCo_Dash_Anim(Fighter_GObj* gobj);
void ftCo_Dash_Coll(Fighter_GObj* gobj);
void ftCo_Dash_IASA(Fighter_GObj* gobj);
void ftCo_Dash_Phys(Fighter_GObj* gobj);
void ftCo_DeadDown_Anim(Fighter_GObj* gobj);
void ftCo_DeadDown_Cam(Fighter_GObj* gobj);
void ftCo_DeadLeft_Anim(Fighter_GObj* gobj);
void ftCo_DeadLeft_Cam(Fighter_GObj* gobj);
void ftCo_DeadRight_Anim(Fighter_GObj* gobj);
void ftCo_DeadRight_Cam(Fighter_GObj* gobj);
void ftCo_DeadUp_Anim(Fighter_GObj* gobj);
void ftCo_DeadUp_Cam(Fighter_GObj* gobj);
void ftCo_DeadUpFall_Anim(Fighter_GObj* gobj);
void ftCo_DeadUpFall_Cam(Fighter_GObj* gobj);
void ftCo_DeadUpFall_Phys(Fighter_GObj* gobj);
void ftCo_DeadUpStar_Anim(Fighter_GObj* gobj);
void ftCo_DeadUpStar_Cam(Fighter_GObj* gobj);
void ftCo_Down_Anim(Fighter_GObj* gobj);
void ftCo_DownAttack_Anim(Fighter_GObj* gobj);
void ftCo_DownAttack_Coll(Fighter_GObj* gobj);
void ftCo_DownAttack_IASA(Fighter_GObj* gobj);
void ftCo_DownAttack_Phys(Fighter_GObj* gobj);
void ftCo_Down_Coll(Fighter_GObj* gobj);
void ftCo_DownDamage_Anim(Fighter_GObj* gobj);
void ftCo_DownDamage_Coll(Fighter_GObj* gobj);
void ftCo_DownDamage_IASA(Fighter_GObj* gobj);
void ftCo_DownDamage_Phys(Fighter_GObj* gobj);
void ftCo_Down_IASA(Fighter_GObj* gobj);
void ftCo_Down_Phys(Fighter_GObj* gobj);
void ftCo_DownReflect_Anim(Fighter_GObj* gobj);
void ftCo_DownReflect_Coll(Fighter_GObj* gobj);
void ftCo_DownReflect_IASA(Fighter_GObj* gobj);
void ftCo_DownReflect_Phys(Fighter_GObj* gobj);
void ftCo_DownSpot_Anim(Fighter_GObj* gobj);
void ftCo_DownSpot_Coll(Fighter_GObj* gobj);
void ftCo_DownSpot_IASA(Fighter_GObj* gobj);
void ftCo_DownSpot_Phys(Fighter_GObj* gobj);
void ftCo_DownStand_Anim(Fighter_GObj* gobj);
void ftCo_DownStand_Coll(Fighter_GObj* gobj);
void ftCo_DownStand_IASA(Fighter_GObj* gobj);
void ftCo_DownStand_Phys(Fighter_GObj* gobj);
void ftCo_Entry_Anim(Fighter_GObj* gobj);
void ftCo_Entry_Coll(Fighter_GObj* gobj);
void ftCo_EntryEnd_Anim(Fighter_GObj* gobj);
void ftCo_EntryEnd_Coll(Fighter_GObj* gobj);
void ftCo_EntryEnd_IASA(Fighter_GObj* gobj);
void ftCo_EntryEnd_Phys(Fighter_GObj* gobj);
void ftCo_Entry_IASA(Fighter_GObj* gobj);
void ftCo_Entry_Phys(Fighter_GObj* gobj);
void ftCo_EntryStart_Anim(Fighter_GObj* gobj);
void ftCo_EntryStart_Coll(Fighter_GObj* gobj);
void ftCo_EntryStart_IASA(Fighter_GObj* gobj);
void ftCo_EntryStart_Phys(Fighter_GObj* gobj);
void ftCo_EscapeAir_Anim(Fighter_GObj* gobj);
void ftCo_EscapeAir_Coll(Fighter_GObj* gobj);
void ftCo_EscapeAir_IASA(Fighter_GObj* gobj);
void ftCo_EscapeAir_Phys(Fighter_GObj* gobj);
void ftCo_Escape_Anim(Fighter_GObj* gobj);
void ftCo_Escape_Coll(Fighter_GObj* gobj);
void ftCo_Escape_IASA(Fighter_GObj* gobj);
void ftCo_EscapeN_Anim(Fighter_GObj* gobj);
void ftCo_EscapeN_Coll(Fighter_GObj* gobj);
void ftCo_EscapeN_IASA(Fighter_GObj* gobj);
void ftCo_EscapeN_Phys(Fighter_GObj* gobj);
void ftCo_Escape_Phys(Fighter_GObj* gobj);
void ftCo_FallAerial_Anim(Fighter_GObj* gobj);
void ftCo_FallAerial_Coll(Fighter_GObj* gobj);
void ftCo_FallAerial_IASA(Fighter_GObj* gobj);
void ftCo_FallAerial_Phys(Fighter_GObj* gobj);
void ftCo_Fall_Anim(Fighter_GObj* gobj);
void ftCo_Fall_Coll(Fighter_GObj* gobj);
void ftCo_Fall_IASA(Fighter_GObj* gobj);
void ftCo_Fall_Phys(Fighter_GObj* gobj);
void ftCo_FallSpecial_Anim(Fighter_GObj* gobj);
void ftCo_FallSpecial_Coll(Fighter_GObj* gobj);
void ftCo_FallSpecial_IASA(Fighter_GObj* gobj);
void ftCo_FallSpecial_Phys(Fighter_GObj* gobj);
void ftCo_FireFlowerShootAir_Anim(Fighter_GObj* gobj);
void ftCo_FireFlowerShootAir_Coll(Fighter_GObj* gobj);
void ftCo_FireFlowerShootAir_IASA(Fighter_GObj* gobj);
void ftCo_FireFlowerShootAir_Phys(Fighter_GObj* gobj);
void ftCo_FireFlowerShoot_Anim(Fighter_GObj* gobj);
void ftCo_FireFlowerShoot_Coll(Fighter_GObj* gobj);
void ftCo_FireFlowerShoot_IASA(Fighter_GObj* gobj);
void ftCo_FireFlowerShoot_Phys(Fighter_GObj* gobj);
void ftCo_FlyReflect_Anim(Fighter_GObj* gobj);
void ftCo_FlyReflect_Coll(Fighter_GObj* gobj);
void ftCo_FlyReflect_IASA(Fighter_GObj* gobj);
void ftCo_FlyReflect_Phys(Fighter_GObj* gobj);
void ftCo_Furafura_Anim(Fighter_GObj* gobj);
void ftCo_Furafura_Coll(Fighter_GObj* gobj);
void ftCo_Furafura_IASA(Fighter_GObj* gobj);
void ftCo_Furafura_Phys(Fighter_GObj* gobj);
void ftCo_Guard_Anim(Fighter_GObj* gobj);
void ftCo_Guard_Coll(Fighter_GObj* gobj);
void ftCo_Guard_IASA(Fighter_GObj* gobj);
void ftCo_GuardOff_Anim(Fighter_GObj* gobj);
void ftCo_GuardOff_Coll(Fighter_GObj* gobj);
void ftCo_GuardOff_IASA(Fighter_GObj* gobj);
void ftCo_GuardOff_Phys(Fighter_GObj* gobj);
void ftCo_GuardOn_Anim(Fighter_GObj* gobj);
void ftCo_GuardOn_Coll(Fighter_GObj* gobj);
void ftCo_GuardOn_IASA(Fighter_GObj* gobj);
void ftCo_GuardOn_Phys(Fighter_GObj* gobj);
void ftCo_Guard_Phys(Fighter_GObj* gobj);
void ftCo_GuardReflect_Anim(Fighter_GObj* gobj);
void ftCo_GuardReflect_Coll(Fighter_GObj* gobj);
void ftCo_GuardReflect_IASA(Fighter_GObj* gobj);
void ftCo_GuardReflect_Phys(Fighter_GObj* gobj);
void ftCo_GuardSetOff_Anim(Fighter_GObj* gobj);
void ftCo_GuardSetOff_Coll(Fighter_GObj* gobj);
void ftCo_GuardSetOff_IASA(Fighter_GObj* gobj);
void ftCo_GuardSetOff_Phys(Fighter_GObj* gobj);
void ftCo_HammerFall_Anim(Fighter_GObj* gobj);
void ftCo_HammerFall_Coll(Fighter_GObj* gobj);
void ftCo_HammerFall_IASA(Fighter_GObj* gobj);
void ftCo_HammerFall_Phys(Fighter_GObj* gobj);
void ftCo_HammerJump_Anim(Fighter_GObj* gobj);
void ftCo_HammerJump_Coll(Fighter_GObj* gobj);
void ftCo_HammerJump_IASA(Fighter_GObj* gobj);
void ftCo_HammerJump_Phys(Fighter_GObj* gobj);
void ftCo_HammerKneeBend_Anim(Fighter_GObj* gobj);
void ftCo_HammerKneeBend_Coll(Fighter_GObj* gobj);
void ftCo_HammerKneeBend_IASA(Fighter_GObj* gobj);
void ftCo_HammerKneeBend_Phys(Fighter_GObj* gobj);
void ftCo_HammerLanding_Anim(Fighter_GObj* gobj);
void ftCo_HammerLanding_Coll(Fighter_GObj* gobj);
void ftCo_HammerLanding_IASA(Fighter_GObj* gobj);
void ftCo_HammerLanding_Phys(Fighter_GObj* gobj);
void ftCo_HammerTurn_Anim(Fighter_GObj* gobj);
void ftCo_HammerTurn_Coll(Fighter_GObj* gobj);
void ftCo_HammerTurn_IASA(Fighter_GObj* gobj);
void ftCo_HammerTurn_Phys(Fighter_GObj* gobj);
void ftCo_HammerWait_Anim(Fighter_GObj* gobj);
void ftCo_HammerWait_Coll(Fighter_GObj* gobj);
void ftCo_HammerWait_IASA(Fighter_GObj* gobj);
void ftCo_HammerWait_Phys(Fighter_GObj* gobj);
void ftCo_HammerWalk_Anim(Fighter_GObj* gobj);
void ftCo_HammerWalk_Coll(Fighter_GObj* gobj);
void ftCo_HammerWalk_IASA(Fighter_GObj* gobj);
void ftCo_HammerWalk_Phys(Fighter_GObj* gobj);
void ftCo_HarisenSwing_Anim(Fighter_GObj* gobj);
void ftCo_HarisenSwing_Coll(Fighter_GObj* gobj);
void ftCo_HarisenSwing_IASA(Fighter_GObj* gobj);
void ftCo_HarisenSwing_Phys(Fighter_GObj* gobj);
void ftCo_HeavyThrow_Coll(Fighter_GObj* gobj);
void ftCo_ItemGet_Anim(Fighter_GObj* gobj);
void ftCo_ItemGet_Coll(Fighter_GObj* gobj);
void ftCo_ItemGet_IASA(Fighter_GObj* gobj);
void ftCo_ItemGet_Phys(Fighter_GObj* gobj);
void ftCo_ItemParasolDamageFall_Anim(Fighter_GObj* gobj);
void ftCo_ItemParasolDamageFall_Coll(Fighter_GObj* gobj);
void ftCo_ItemParasolDamageFall_IASA(Fighter_GObj* gobj);
void ftCo_ItemParasolDamageFall_Phys(Fighter_GObj* gobj);
void ftCo_ItemParasolFall_Anim(Fighter_GObj* gobj);
void ftCo_ItemParasolFall_Coll(Fighter_GObj* gobj);
void ftCo_ItemParasolFall_IASA(Fighter_GObj* gobj);
void ftCo_ItemParasolFall_Phys(Fighter_GObj* gobj);
void ftCo_ItemParasolFallSpecial_Anim(Fighter_GObj* gobj);
void ftCo_ItemParasolFallSpecial_Coll(Fighter_GObj* gobj);
void ftCo_ItemParasolFallSpecial_IASA(Fighter_GObj* gobj);
void ftCo_ItemParasolFallSpecial_Phys(Fighter_GObj* gobj);
void ftCo_ItemParasolOpen_Anim(Fighter_GObj* gobj);
void ftCo_ItemParasolOpen_Coll(Fighter_GObj* gobj);
void ftCo_ItemParasolOpen_IASA(Fighter_GObj* gobj);
void ftCo_ItemParasolOpen_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeAirEnd_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeAirEnd_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeAirEnd_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeAirEnd_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeAirFire_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeAirFire_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeAirFire_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeAirFire_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeAirRapid_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeAirRapid_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeAirRapid_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeAirRapid_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeAirStart_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeAirStart_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeAirStart_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeAirStart_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeEnd_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeEnd_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeEnd_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeEnd_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeFire_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeFire_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeFire_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeFire_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeRapid_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeRapid_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeRapid_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeRapid_Phys(Fighter_GObj* gobj);
void ftCo_ItemScopeStart_Anim(Fighter_GObj* gobj);
void ftCo_ItemScopeStart_Coll(Fighter_GObj* gobj);
void ftCo_ItemScopeStart_IASA(Fighter_GObj* gobj);
void ftCo_ItemScopeStart_Phys(Fighter_GObj* gobj);
void ftCo_ItemScrewAir_Anim(Fighter_GObj* gobj);
void ftCo_ItemScrewAir_Coll(Fighter_GObj* gobj);
void ftCo_ItemScrewAir_IASA(Fighter_GObj* gobj);
void ftCo_ItemScrewAir_Phys(Fighter_GObj* gobj);
void ftCo_ItemScrew_Anim(Fighter_GObj* gobj);
void ftCo_ItemScrew_Coll(Fighter_GObj* gobj);
void ftCo_ItemScrew_IASA(Fighter_GObj* gobj);
void ftCo_ItemScrew_Phys(Fighter_GObj* gobj);
void ftCo_ItemThrow_Anim(Fighter_GObj* gobj);
void ftCo_ItemThrow_IASA(Fighter_GObj* gobj);
void ftCo_ItemThrow_Phys(Fighter_GObj* gobj);
void ftCo_JumpAerial_Anim(Fighter_GObj* gobj);
void ftCo_JumpAerial_Coll(Fighter_GObj* gobj);
void ftCo_JumpAerialF1_Anim(Fighter_GObj* gobj);
void ftCo_JumpAerialF1_Coll(Fighter_GObj* gobj);
void ftCo_JumpAerialF1_IASA(Fighter_GObj* gobj);
void ftCo_JumpAerialF1_Phys(Fighter_GObj* gobj);
void ftCo_JumpAerial_IASA(Fighter_GObj* gobj);
void ftCo_JumpAerial_Phys(Fighter_GObj* gobj);
void ftCo_Jump_Anim(Fighter_GObj* gobj);
void ftCo_Jump_Coll(Fighter_GObj* gobj);
void ftCo_Jump_IASA(Fighter_GObj* gobj);
void ftCo_Jump_Phys(Fighter_GObj* gobj);
void ftCo_KinokoGiantEndAir_Anim(Fighter_GObj* gobj);
void ftCo_KinokoGiantEndAir_Coll(Fighter_GObj* gobj);
void ftCo_KinokoGiantEnd_Anim(Fighter_GObj* gobj);
void ftCo_KinokoGiantEnd_Coll(Fighter_GObj* gobj);
void ftCo_KinokoGiantStartAir_Anim(Fighter_GObj* gobj);
void ftCo_KinokoGiantStartAir_Coll(Fighter_GObj* gobj);
void ftCo_KinokoGiantStart_Anim(Fighter_GObj* gobj);
void ftCo_KinokoGiantStart_Coll(Fighter_GObj* gobj);
void ftCo_KinokoSmallEndAir_Anim(Fighter_GObj* gobj);
void ftCo_KinokoSmallEndAir_Coll(Fighter_GObj* gobj);
void ftCo_KinokoSmallEnd_Anim(Fighter_GObj* gobj);
void ftCo_KinokoSmallEnd_Coll(Fighter_GObj* gobj);
void ftCo_KinokoSmallStartAir_Anim(Fighter_GObj* gobj);
void ftCo_KinokoSmallStartAir_Coll(Fighter_GObj* gobj);
void ftCo_KinokoSmallStart_Anim(Fighter_GObj* gobj);
void ftCo_KinokoSmallStart_Coll(Fighter_GObj* gobj);
void ftCo_KneeBend_Anim(Fighter_GObj* gobj);
void ftCo_KneeBend_Coll(Fighter_GObj* gobj);
void ftCo_KneeBend_IASA(Fighter_GObj* gobj);
void ftCo_KneeBend_Phys(Fighter_GObj* gobj);
void ftCo_Landing_Anim(Fighter_GObj* gobj);
void ftCo_Landing_Coll(Fighter_GObj* gobj);
void ftCo_Landing_IASA(Fighter_GObj* gobj);
void ftCo_Landing_Phys(Fighter_GObj* gobj);
void ftCo_LGunShootAir_Anim(Fighter_GObj* gobj);
void ftCo_LGunShootAir_Coll(Fighter_GObj* gobj);
void ftCo_LGunShootAir_IASA(Fighter_GObj* gobj);
void ftCo_LGunShootAir_Phys(Fighter_GObj* gobj);
void ftCo_LGunShoot_Anim(Fighter_GObj* gobj);
void ftCo_LGunShoot_Coll(Fighter_GObj* gobj);
void ftCo_LGunShoot_IASA(Fighter_GObj* gobj);
void ftCo_LGunShoot_Phys(Fighter_GObj* gobj);
void ftCo_LiftTurn_Anim(Fighter_GObj* gobj);
void ftCo_LiftTurn_Coll(Fighter_GObj* gobj);
void ftCo_LiftTurn_IASA(Fighter_GObj* gobj);
void ftCo_LiftTurn_Phys(Fighter_GObj* gobj);
void ftCo_LiftWait_Anim(Fighter_GObj* gobj);
void ftCo_LiftWait_Coll(Fighter_GObj* gobj);
void ftCo_LiftWait_IASA(Fighter_GObj* gobj);
void ftCo_LiftWait_Phys(Fighter_GObj* gobj);
void ftCo_LiftWalk_Anim(Fighter_GObj* gobj);
void ftCo_LiftWalk_Coll(Fighter_GObj* gobj);
void ftCo_LiftWalk_IASA(Fighter_GObj* gobj);
void ftCo_LiftWalk_Phys(Fighter_GObj* gobj);
void ftCo_LightThrowAir_Coll(Fighter_GObj* gobj);
void ftCo_LightThrowAir_Phys(Fighter_GObj* gobj);
void ftCo_LightThrow_Coll(Fighter_GObj* gobj);
void ftCo_LipstickSwing_Anim(Fighter_GObj* gobj);
void ftCo_LipstickSwing_Coll(Fighter_GObj* gobj);
void ftCo_LipstickSwing_IASA(Fighter_GObj* gobj);
void ftCo_LipstickSwing_Phys(Fighter_GObj* gobj);
void ftCo_MissFoot_Anim(Fighter_GObj* gobj);
void ftCo_MissFoot_Coll(Fighter_GObj* gobj);
void ftCo_MissFoot_IASA(Fighter_GObj* gobj);
void ftCo_MissFoot_Phys(Fighter_GObj* gobj);
void ftCo_Ottotto_Anim(Fighter_GObj* gobj);
void ftCo_Ottotto_Coll(Fighter_GObj* gobj);
void ftCo_Ottotto_IASA(Fighter_GObj* gobj);
void ftCo_Ottotto_Phys(Fighter_GObj* gobj);
void ftCo_OttottoWait_Anim(Fighter_GObj* gobj);
void ftCo_OttottoWait_Coll(Fighter_GObj* gobj);
void ftCo_OttottoWait_IASA(Fighter_GObj* gobj);
void ftCo_OttottoWait_Phys(Fighter_GObj* gobj);
void ftCo_ParasolSwing_Anim(Fighter_GObj* gobj);
void ftCo_ParasolSwing_Coll(Fighter_GObj* gobj);
void ftCo_ParasolSwing_IASA(Fighter_GObj* gobj);
void ftCo_ParasolSwing_Phys(Fighter_GObj* gobj);
void ftCo_Pass_Anim(Fighter_GObj* gobj);
void ftCo_Pass_Coll(Fighter_GObj* gobj);
void ftCo_Pass_IASA(Fighter_GObj* gobj);
void ftCo_PassiveCeil_Anim(Fighter_GObj* gobj);
void ftCo_PassiveCeil_Coll(Fighter_GObj* gobj);
void ftCo_PassiveCeil_IASA(Fighter_GObj* gobj);
void ftCo_PassiveCeil_Phys(Fighter_GObj* gobj);
void ftCo_PassiveStand_Anim(Fighter_GObj* gobj);
void ftCo_PassiveStand_Coll(Fighter_GObj* gobj);
void ftCo_PassiveStand_IASA(Fighter_GObj* gobj);
void ftCo_PassiveStand_Phys(Fighter_GObj* gobj);
void ftCo_PassiveWall_Anim(Fighter_GObj* gobj);
void ftCo_PassiveWall_Coll(Fighter_GObj* gobj);
void ftCo_PassiveWall_IASA(Fighter_GObj* gobj);
void ftCo_PassiveWall_Phys(Fighter_GObj* gobj);
void ftCo_Pass_Phys(Fighter_GObj* gobj);
void ftCo_Rebirth_Anim(Fighter_GObj* gobj);
void ftCo_Rebirth_Cam(Fighter_GObj* gobj);
void ftCo_Rebirth_Coll(Fighter_GObj* gobj);
void ftCo_Rebirth_IASA(Fighter_GObj* gobj);
void ftCo_Rebirth_Phys(Fighter_GObj* gobj);
void ftCo_RebirthWait_Anim(Fighter_GObj* gobj);
void ftCo_RebirthWait_Coll(Fighter_GObj* gobj);
void ftCo_RebirthWait_IASA(Fighter_GObj* gobj);
void ftCo_RebirthWait_Phys(Fighter_GObj* gobj);
void ftCo_Rebound_Anim(Fighter_GObj* gobj);
void ftCo_Rebound_Coll(Fighter_GObj* gobj);
void ftCo_Rebound_IASA(Fighter_GObj* gobj);
void ftCo_Rebound_Phys(Fighter_GObj* gobj);
void ftCo_ReboundStop_Anim(Fighter_GObj* gobj);
void ftCo_Run_Anim(Fighter_GObj* gobj);
void ftCo_RunBrake_Anim(Fighter_GObj* gobj);
void ftCo_RunBrake_Coll(Fighter_GObj* gobj);
void ftCo_RunBrake_IASA(Fighter_GObj* gobj);
void ftCo_RunBrake_Phys(Fighter_GObj* gobj);
void ftCo_Run_Coll(Fighter_GObj* gobj);
void ftCo_RunDirect_Anim(Fighter_GObj* gobj);
void ftCo_RunDirect_Coll(Fighter_GObj* gobj);
void ftCo_RunDirect_IASA(Fighter_GObj* gobj);
void ftCo_RunDirect_Phys(Fighter_GObj* gobj);
void ftCo_Run_IASA(Fighter_GObj* gobj);
void ftCo_Run_Phys(Fighter_GObj* gobj);
void ftCo_SetFacingDirection(Fighter_GObj*, f32 facing_dir);
void ftCo_ShieldBreakDown_Anim(Fighter_GObj* gobj);
void ftCo_ShieldBreakDown_Coll(Fighter_GObj* gobj);
void ftCo_ShieldBreakDown_IASA(Fighter_GObj* gobj);
void ftCo_ShieldBreakDown_Phys(Fighter_GObj* gobj);
void ftCo_ShieldBreakFall_Anim(Fighter_GObj* gobj);
void ftCo_ShieldBreakFall_Coll(Fighter_GObj* gobj);
void ftCo_ShieldBreakFall_IASA(Fighter_GObj* gobj);
void ftCo_ShieldBreakFall_Phys(Fighter_GObj* gobj);
void ftCo_ShieldBreakFly_Anim(Fighter_GObj* gobj);
void ftCo_ShieldBreakFly_Coll(Fighter_GObj* gobj);
void ftCo_ShieldBreakFly_IASA(Fighter_GObj* gobj);
void ftCo_ShieldBreakFly_Phys(Fighter_GObj* gobj);
void ftCo_ShieldBreakStand_Anim(Fighter_GObj* gobj);
void ftCo_ShieldBreakStand_Coll(Fighter_GObj* gobj);
void ftCo_ShieldBreakStand_IASA(Fighter_GObj* gobj);
void ftCo_ShieldBreakStand_Phys(Fighter_GObj* gobj);
void ftCo_Shouldered_Anim(Fighter_GObj* gobj);
void ftCo_Shouldered_Coll(Fighter_GObj* gobj);
void ftCo_Shouldered_IASA(Fighter_GObj* gobj);
void ftCo_Shouldered_Phys(Fighter_GObj* gobj);
void ftCo_Sleep_Anim(Fighter_GObj* gobj);
void ftCo_Sleep_IASA(Fighter_GObj* gobj);
void ftCo_Squat_Anim(Fighter_GObj* gobj);
void ftCo_Squat_Coll(Fighter_GObj* gobj);
void ftCo_Squat_IASA(Fighter_GObj* gobj);
void ftCo_Squat_Phys(Fighter_GObj* gobj);
void ftCo_SquatRv_Anim(Fighter_GObj* gobj);
void ftCo_SquatRv_Coll(Fighter_GObj* gobj);
void ftCo_SquatRv_IASA(Fighter_GObj* gobj);
void ftCo_SquatRv_Phys(Fighter_GObj* gobj);
void ftCo_SquatWait_Anim(Fighter_GObj* gobj);
void ftCo_SquatWait_Coll(Fighter_GObj* gobj);
void ftCo_SquatWait_IASA(Fighter_GObj* gobj);
void ftCo_SquatWait_Phys(Fighter_GObj* gobj);
void ftCo_StarRodSwing_Anim(Fighter_GObj* gobj);
void ftCo_StarRodSwing_Coll(Fighter_GObj* gobj);
void ftCo_StarRodSwing_IASA(Fighter_GObj* gobj);
void ftCo_StarRodSwing_Phys(Fighter_GObj* gobj);
void ftCo_StopCeil_Anim(Fighter_GObj* gobj);
void ftCo_StopCeil_Coll(Fighter_GObj* gobj);
void ftCo_StopCeil_IASA(Fighter_GObj* gobj);
void ftCo_StopCeil_Phys(Fighter_GObj* gobj);
void ftCo_StopWall_Anim(Fighter_GObj* gobj);
void ftCo_StopWall_Coll(Fighter_GObj* gobj);
void ftCo_StopWall_IASA(Fighter_GObj* gobj);
void ftCo_StopWall_Phys(Fighter_GObj* gobj);
void ftCo_SwordSwing_Anim(Fighter_GObj* gobj);
void ftCo_SwordSwing_Coll(Fighter_GObj* gobj);
void ftCo_SwordSwing_IASA(Fighter_GObj* gobj);
void ftCo_SwordSwing_Phys(Fighter_GObj* gobj);
void ftCo_ThrowB_Anim(Fighter_GObj* gobj);
void ftCo_ThrowB_Coll(Fighter_GObj* gobj);
void ftCo_ThrowB_IASA(Fighter_GObj* gobj);
void ftCo_ThrowB_Phys(Fighter_GObj* gobj);
void ftCo_ThrowF_Anim(Fighter_GObj* gobj);
void ftCo_ThrowF_Coll(Fighter_GObj* gobj);
void ftCo_ThrowF_IASA(Fighter_GObj* gobj);
void ftCo_ThrowF_Phys(Fighter_GObj* gobj);
void ftCo_ThrowHi_Anim(Fighter_GObj* gobj);
void ftCo_ThrowHi_Cam(Fighter_GObj* gobj);
void ftCo_ThrowHi_Coll(Fighter_GObj* gobj);
void ftCo_ThrowHi_IASA(Fighter_GObj* gobj);
void ftCo_ThrowHi_Phys(Fighter_GObj* gobj);
void ftCo_ThrowLw_Anim(Fighter_GObj* gobj);
void ftCo_ThrowLw_Coll(Fighter_GObj* gobj);
void ftCo_ThrowLw_IASA(Fighter_GObj* gobj);
void ftCo_ThrowLw_Phys(Fighter_GObj* gobj);
void ftCo_ThrownB_Anim(Fighter_GObj* gobj);
void ftCo_ThrownB_Coll(Fighter_GObj* gobj);
void ftCo_ThrownB_IASA(Fighter_GObj* gobj);
void ftCo_ThrownB_Phys(Fighter_GObj* gobj);
void ftCo_ThrownCopyStar_Anim(Fighter_GObj* gobj);
void ftCo_ThrownCopyStar_Coll(Fighter_GObj* gobj);
void ftCo_ThrownCopyStar_IASA(Fighter_GObj* gobj);
void ftCo_ThrownCopyStar_Phys(Fighter_GObj* gobj);
void ftCo_ThrownF_Anim(Fighter_GObj* gobj);
void ftCo_ThrownF_Coll(Fighter_GObj* gobj);
void ftCo_ThrownF_IASA(Fighter_GObj* gobj);
void ftCo_ThrownF_Phys(Fighter_GObj* gobj);
void ftCo_ThrownHi_Anim(Fighter_GObj* gobj);
void ftCo_ThrownHi_Cam(Fighter_GObj* gobj);
void ftCo_ThrownHi_Coll(Fighter_GObj* gobj);
void ftCo_ThrownHi_IASA(Fighter_GObj* gobj);
void ftCo_ThrownHi_Phys(Fighter_GObj* gobj);
void ftCo_ThrownKirby_Anim(Fighter_GObj* gobj);
void ftCo_ThrownKirby_Coll(Fighter_GObj* gobj);
void ftCo_ThrownKirby_IASA(Fighter_GObj* gobj);
void ftCo_ThrownKirby_Phys(Fighter_GObj* gobj);
void ftCo_ThrownKirbyStar_Anim(Fighter_GObj* gobj);
void ftCo_ThrownKirbyStar_Coll(Fighter_GObj* gobj);
void ftCo_ThrownKirbyStar_IASA(Fighter_GObj* gobj);
void ftCo_ThrownKirbyStar_Phys(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirB_Anim(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirB_Coll(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirB_IASA(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirB_Phys(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirF_Anim(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirF_Coll(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirF_IASA(Fighter_GObj* gobj);
void ftCo_ThrownKoopaAirF_Phys(Fighter_GObj* gobj);
void ftCo_ThrownKoopaB_Anim(Fighter_GObj* gobj);
void ftCo_ThrownKoopaB_Coll(Fighter_GObj* gobj);
void ftCo_ThrownKoopaB_IASA(Fighter_GObj* gobj);
void ftCo_ThrownKoopaB_Phys(Fighter_GObj* gobj);
void ftCo_ThrownKoopaF_Anim(Fighter_GObj* gobj);
void ftCo_ThrownKoopaF_Coll(Fighter_GObj* gobj);
void ftCo_ThrownKoopaF_IASA(Fighter_GObj* gobj);
void ftCo_ThrownKoopaF_Phys(Fighter_GObj* gobj);
void ftCo_ThrownLw_Anim(Fighter_GObj* gobj);
void ftCo_ThrownLw_Coll(Fighter_GObj* gobj);
void ftCo_ThrownLw_IASA(Fighter_GObj* gobj);
void ftCo_ThrownLw_Phys(Fighter_GObj* gobj);
void ftCo_ThrownMewtwoAir_Anim(Fighter_GObj* gobj);
void ftCo_ThrownMewtwoAir_Coll(Fighter_GObj* gobj);
void ftCo_ThrownMewtwoAir_IASA(Fighter_GObj* gobj);
void ftCo_ThrownMewtwoAir_Phys(Fighter_GObj* gobj);
void ftCo_ThrownMewtwo_Anim(Fighter_GObj* gobj);
void ftCo_ThrownMewtwo_Coll(Fighter_GObj* gobj);
void ftCo_ThrownMewtwo_IASA(Fighter_GObj* gobj);
void ftCo_ThrownMewtwo_Phys(Fighter_GObj* gobj);
void ftCo_Turn_Anim(Fighter_GObj* gobj);
void ftCo_Turn_Coll(Fighter_GObj* gobj);
void ftCo_Turn_IASA(Fighter_GObj* gobj);
void ftCo_Turn_Phys(Fighter_GObj* gobj);
void ftCo_TurnRun_Anim(Fighter_GObj* gobj);
void ftCo_TurnRun_Coll(Fighter_GObj* gobj);
void ftCo_TurnRun_IASA(Fighter_GObj* gobj);
void ftCo_TurnRun_Phys(Fighter_GObj* gobj);
void ftCo_Wait_IASA(Fighter_GObj* gobj);
void ftCo_Walk_Anim(Fighter_GObj* gobj);
void ftCo_Walk_Coll(Fighter_GObj* gobj);
void ftCo_Walk_IASA(Fighter_GObj* gobj);
void ftCo_Walk_Phys(Fighter_GObj* gobj);
void ftCo_WarpStarFall_Anim(Fighter_GObj* gobj);
void ftCo_WarpStarFall_Cam(Fighter_GObj* gobj);
void ftCo_WarpStarFall_Coll(Fighter_GObj* gobj);
void ftCo_WarpStarFall_IASA(Fighter_GObj* gobj);
void ftCo_WarpStarFall_Phys(Fighter_GObj* gobj);
void ftCo_WarpStarJump_Anim(Fighter_GObj* gobj);
void ftCo_WarpStarJump_Cam(Fighter_GObj* gobj);
void ftCo_WarpStarJump_Coll(Fighter_GObj* gobj);
void ftCo_WarpStarJump_IASA(Fighter_GObj* gobj);
void ftCo_WarpStarJump_Phys(Fighter_GObj* gobj);
void ftCo_YoshiEgg_Anim(Fighter_GObj* gobj);
void ftCo_YoshiEgg_Coll(Fighter_GObj* gobj);
void ftCo_YoshiEgg_IASA(Fighter_GObj* gobj);
void ftCo_YoshiEgg_Phys(Fighter_GObj* gobj);

#endif
