#include "forward.h"
#include <baselib/forward.h>

#include "ftdata.h"

#include "ft_0877.h"
#include "types.h"

#include "ftCaptain/ftCaptain_Init.h"
#include "ftCaptain/ftCaptain_SpecialHi.h"
#include "ftCaptain/ftCaptain_SpecialLw.h"
#include "ftCaptain/ftCaptain_SpecialN.h"
#include "ftCaptain/ftCaptain_SpecialS.h"
#include "ftCLink/ftCLink_Init.h"
#include "ftCrazyHand/ftcrazyhand.h"
#include "ftDonkey/ftdonkey_callbacks.h"
#include "ftDonkey/ftdonkey_SpecialHi.h"
#include "ftDonkey/ftdonkey_SpecialLw.h"
#include "ftDonkey/ftdonkey_SpecialN.h"
#include "ftDonkey/ftdonkey_SpecialS.h"
#include "ftDrMario/ftdrmario.h"
#include "ftEmblem/ftemblem.h"
#include "ftFalco/ftfalco.h"
#include "ftFox/ftfox.h"
#include "ftGameWatch/ftgamewatch.h"
#include "ftGanon/ftganon.h"
#include "ftGigaKoopa/ftgigakoopa.h"
#include "ftKirby/ftkirby.h"
#include "ftKoopa/ftkoopa.h"
#include "ftLink/ftlink.h"
#include "ftLuigi/ftluigi.h"
#include "ftMario/ftMario_Init.h"
#include "ftMario/ftMario_SpecialHi.h"
#include "ftMario/ftMario_SpecialLw.h"
#include "ftMario/ftMario_SpecialN.h"
#include "ftMario/ftMario_SpecialS.h"
#include "ftMario/ftMario_Strings.h"
#include "ftMars/ftMars.h"
#include "ftMasterHand/ftMasterHand_01.h"
#include "ftMasterHand/ftMasterHand_02.h"
#include "ftMewtwo/ftmewtwo.h"
#include "ftNana/ftnana.h"
#include "ftNess/ftNess.h"
#include "ftPeach/ftpeach.h"
#include "ftPichu/ftpichu.h"
#include "ftPikachu/ftpikachu.h"
#include "ftPikachu/ftpikachu1.h"
#include "ftPopo/fticeclimber.h"
#include "ftPopo/ftpopo_init.h"
#include "ftPurin/ftpurin.h"
#include "ftSamus/ftsamus1.h"
#include "ftSamus/ftsamus3.h"
#include "ftSamus/ftsamus4.h"
#include "ftSamus/ftsamus5.h"
#include "ftSamus/ftsamus6.h"
#include "ftSandbag/ftsandbag.h"
#include "ftSeak/ftSeak_Init.h"
#include "ftSeak/ftSeak_SpecialHi.h"
#include "ftSeak/ftSeak_SpecialLw.h"
#include "ftSeak/ftSeak_SpecialN.h"
#include "ftSeak/ftSeak_SpecialS.h"
#include "ftYoshi/ftyoshi1.h"
#include "ftYoshi/ftyoshi2.h"
#include "ftYoshi/ftyoshi4.h"
#include "ftZakoBoy/ftzakoboy.h"
#include "ftZakoGirl/ftzakogirl.h"
#include "ftZelda/ftZelda_Init.h"
#include "ftZelda/ftZelda_SpecialHi.h"
#include "ftZelda/ftZelda_SpecialLw.h"
#include "ftZelda/ftZelda_SpecialN.h"
#include "ftZelda/ftZelda_SpecialS.h"

#include <dolphin/mtx/types.h>

typedef struct ftData_UnkCountStruct {
    /// Always zero; could be #NULL or the high part of a 64-bit integer.
    int zero;

    /// A count or msid.
    int count;
} ftData_UnkCountStruct;

ftData_UnkCountStruct ftData_Table_Unk0[FTKIND_MAX] = {
    { 0, 303 }, { 0, 327 }, { 0, 318 }, { 0, 337 }, { 0, 479 }, { 0, 316 },
    { 0, 314 }, { 0, 317 }, { 0, 326 }, { 0, 318 }, { 0, 321 }, { 0, 321 },
    { 0, 320 }, { 0, 313 }, { 0, 314 }, { 0, 327 }, { 0, 314 }, { 0, 312 },
    { 0, 327 }, { 0, 311 }, { 0, 314 }, { 0, 303 }, { 0, 327 }, { 0, 320 },
    { 0, 323 }, { 0, 318 }, { 0, 327 }, { 0, 345 }, { 0, 344 }, { 0, 295 },
    { 0, 295 }, { 0, 316 }, { 0, 296 },
};

Event ftData_Table_Unk1[FTKIND_MAX] = {
    NULL, NULL, NULL, NULL, ftKb_800EE528, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, ftPr_8013C2F8, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,          NULL, NULL, NULL, NULL, NULL, NULL,
};

HSD_GObjEvent ftData_OnLoad[FTKIND_MAX] = {
    ftMr_Init_OnLoad, ftFx_Init_OnLoad, ftCa_Init_OnLoad, ftDk_Init_OnLoad,
    ftKb_Init_OnLoad, ftKp_Init_OnLoad, ftLk_Init_OnLoad, ftSk_Init_OnLoad,
    ftNs_Init_OnLoad, ftPe_Init_OnLoad, ftPp_Init_OnLoad, ftNn_Init_OnLoad,
    ftPk_Init_OnLoad, ftSs_Init_OnLoad, ftYs_Init_OnLoad, ftPr_Init_OnLoad,
    ftMt_Init_OnLoad, ftLg_Init_OnLoad, ftMs_Init_OnLoad, ftZd_Init_OnLoad,
    ftCl_Init_OnLoad, ftDr_Init_OnLoad, ftFc_Init_OnLoad, ftPc_Init_OnLoad,
    ftGw_Init_OnLoad, ftGn_Init_OnLoad, ftFe_Init_OnLoad, ftMh_Init_OnLoad,
    ftCh_Init_OnLoad, ftBo_Init_OnLoad, ftGl_Init_OnLoad, ftGk_Init_OnLoad,
    ftSb_Init_OnLoad,
};

HSD_GObjEvent ftData_OnDeath[FTKIND_MAX] = {
    ftMr_Init_OnDeath, ftFx_Init_OnDeath, ftCa_Init_OnDeath, ftDk_Init_OnDeath,
    ftKb_Init_OnDeath, ftKp_Init_OnDeath, ftLk_Init_OnDeath, ftSk_Init_OnDeath,
    ftNs_Init_OnDeath, ftPe_Init_OnDeath, ftPp_Init_OnDeath, ftNn_Init_OnDeath,
    ftPk_Init_OnDeath, ftSs_Init_OnDeath, ftYs_Init_OnDeath, ftPr_Init_OnDeath,
    ftMt_Init_OnDeath, ftLg_Init_OnDeath, ftMs_Init_OnDeath, ftZd_Init_OnDeath,
    ftCl_Init_OnDeath, ftDr_Init_OnDeath, ftFc_Init_OnDeath, ftPc_Init_OnDeath,
    ftGw_Init_OnDeath, ftGn_Init_OnDeath, ftFe_Init_OnDeath, ftMh_Init_OnDeath,
    ftCh_Init_OnDeath, ftBo_Init_OnDeath, ftGl_Init_OnDeath, ftGk_Init_OnDeath,
    ftSb_Init_OnDeath,
};

HSD_GObjEvent ftData_OnUserDataRemove[FTKIND_MAX] = {
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, ftPr_Init_OnUserDataRemove,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL,
};

MotionState* ftData_CharacterStateTables[FTKIND_MAX] = {
    ftMr_Init_MotionStateTable,
    ftFx_Init_MotionStateTable,
    ftCa_Init_MotionStateTable,
    ftDk_Init_MotionStateTable,
    ftKb_Init_MotionStateTable,
    ftKp_Init_MotionStateTable,
    ftLk_Init_MotionStateTable,
    ftSk_Init_MotionStateTable,
    ftNs_Init_MotionStateTable,
    ftPe_Init_MotionStateTable,
    ftPp_Init_MotionStateTable,
    ftNn_Init_MotionStateTable,
    ftPk_Init_MotionStateTable,
    ftSs_Init_MotionStateTable,
    ftYs_Init_MotionStateTable,
    ftPr_Init_MotionStateTable,
    ftMt_Init_MotionStateTable,
    ftLg_Init_MotionStateTable,
    ftMs_Init_MotionStateTable,
    ftZd_Init_MotionStateTable,
    ftCl_Init_MotionStateTable,
    ftDr_Init_MotionStateTable,
    ftFc_Init_MotionStateTable,
    ftPc_Init_MotionStateTable,
    ftGw_Init_MotionStateTable,
    ftGn_Init_MotionStateTable,
    ftFe_Init_MotionStateTable,
    ftMh_Init_MotionStateTable,
    ftCh_Init_MotionStateTable,
    NULL,
    NULL,
    ftGk_Init_MotionStateTable,
    ftSb_Init_MotionStateTable,
};

MotionState* ftData_UnkMotionStates0[FTKIND_MAX] = {
    ftMr_Init_UnkMotionStates0,
    NULL,
    NULL,
    NULL,
    ftKb_Init_UnkMotionStates0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftLg_Init_UnkMotionStates0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGk_Init_UnkMotionStates0,
    NULL,
};

HSD_GObjEvent ftData_SpecialS[FTKIND_MAX] = {
    ftMr_SpecialS_StartMotion,
    ftFx_SpecialS_StartMotion,
    ftCa_SpecialS_StartMotion,
    ftDk_SpecialS_StartMotion,
    ftKb_SpecialS_StartMotion,
    ftKp_SpecialS_StartMotion,
    ftLk_SpecialS_StartMotion,
    ftSk_SpecialS_StartMotion,
    ftNs_SpecialS_StartMotion,
    ftPe_SpecialS_StartMotion,
    ftPp_SpecialS_StartMotion,
    NULL,
    ftPk_SpecialS_StartMotion,
    ftSs_SpecialS_StartMotion,
    ftYs_SpecialS_StartMotion,
    ftPr_SpecialS_StartMotion,
    ftMt_SpecialS_StartMotion,
    ftLg_SpecialS_StartMotion,
    ftMs_SpecialS_StartMotion,
    ftZd_SpecialS_StartMotion,
    ftLk_SpecialS_StartMotion,
    ftMr_SpecialS_StartMotion,
    ftFx_SpecialS_StartMotion,
    ftPk_SpecialS_StartMotion,
    ftGw_SpecialS_StartMotion,
    ftCa_SpecialS_StartMotion,
    ftMs_SpecialS_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialS_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialAirHi[FTKIND_MAX] = {
    ftMr_SpecialAirHi_StartMotion,
    ftFx_SpecialAirHi_StartMotion,
    ftCa_SpecialAirHi_StartMotion,
    ftDk_SpecialAirHi_StartMotion,
    ftKb_SpecialAirHi_StartMotion,
    ftKp_SpecialAirHi_StartMotion,
    ftLk_SpecialAirHi_StartMotion,
    ftSk_SpecialAirHi_StartMotion,
    ftNs_SpecialAirHiStart_Action,
    ftPe_SpecialAirHi_StartMotion,
    ftPp_SpecialAirHi_StartMotion,
    NULL,
    ftPk_SpecialAirHi_StartMotion,
    ftSs_SpecialAirHi_StartMotion,
    ftYs_SpecialAirHi_StartMotion,
    ftPr_SpecialAirHi_StartMotion,
    ftMt_SpecialAirHi_StartMotion,
    ftLg_SpecialAirHi_StartMotion,
    ftMs_SpecialAirHi_StartMotion,
    ftZd_SpecialAirHi_StartMotion,
    ftLk_SpecialAirHi_StartMotion,
    ftMr_SpecialAirHi_StartMotion,
    ftFx_SpecialAirHi_StartMotion,
    ftPk_SpecialAirHi_StartMotion,
    ftGw_SpecialAirHi_StartMotion,
    ftCa_SpecialAirHi_StartMotion,
    ftMs_SpecialAirHi_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialAirHi_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialAirLw[FTKIND_MAX] = {
    ftMr_SpecialAirLw_StartMotion,
    ftFx_SpecialAirLw_StartMotion,
    ftCa_SpecialAirLw_StartMotion,
    NULL,
    ftKb_SpecialAirLw_StartMotion,
    ftKp_SpecialAirLw_StartMotion,
    ftLk_SpecialAirLw_StartMotion,
    ftSk_SpecialAirLw_StartMotion,
    ftNs_SpecialAirLwStart_Action,
    ftPe_SpecialAirLw_StartMotion,
    ftPp_SpecialAirLw_StartMotion,
    ftPp_SpecialAirLw_StartMotion,
    ftPk_SpecialAirLw_StartMotion,
    ftSs_SpecialAirLw_StartMotion,
    ftYs_SpecialAirLw_StartMotion,
    ftPr_SpecialAirLw_StartMotion,
    ftMt_SpecialAirLw_StartMotion,
    ftLg_SpecialAirLw_StartMotion,
    ftMs_SpecialAirLw_StartMotion,
    ftZd_SpecialAirLw_StartMotion,
    ftLk_SpecialAirLw_StartMotion,
    ftMr_SpecialAirLw_StartMotion,
    ftFx_SpecialAirLw_StartMotion,
    ftPk_SpecialAirLw_StartMotion,
    ftGw_SpecialAirLw_StartMotion,
    ftCa_SpecialAirLw_StartMotion,
    ftMs_SpecialAirLw_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialAirLw_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialAirS[FTKIND_MAX] = {
    ftMr_SpecialAirS_StartMotion,
    ftFx_SpecialAirS_StartMotion,
    ftCa_SpecialAirS_StartMotion,
    ftDk_SpecialAirS_StartMotion,
    ftKb_SpecialAirS_StartMotion,
    ftKp_SpecialAirS_StartMotion,
    ftLk_SpecialAirS_StartMotion,
    ftSk_SpecialAirS_StartMotion,
    ftNs_SpecialAirS_Action,
    ftPe_SpecialAirS_StartMotion,
    ftPp_SpecialAirS_StartMotion,
    NULL,
    ftPk_SpecialAirS_StartMotion,
    ftSs_SpecialAirS_StartMotion,
    ftYs_SpecialAirS_StartMotion,
    ftPr_SpecialAirS_StartMotion,
    ftMt_SpecialAirS_StartMotion,
    ftLg_SpecialAirS_StartMotion,
    ftMs_SpecialAirS_StartMotion,
    ftZd_SpecialAirS_StartMotion,
    ftLk_SpecialAirS_StartMotion,
    ftMr_SpecialAirS_StartMotion,
    ftFx_SpecialAirS_StartMotion,
    ftPk_SpecialAirS_StartMotion,
    ftGw_SpecialAirS_StartMotion,
    ftCa_SpecialAirS_StartMotion,
    ftMs_SpecialAirS_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialAirS_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialAirN[FTKIND_MAX] = {
    ftMr_SpecialAirN_StartMotion,
    ftFx_SpecialAirN_StartMotion,
    ftCa_SpecialAirN_StartMotion,
    ftDk_SpecialAirN_StartMotion,
    ftKb_SpecialAirN_StartMotion,
    ftKp_SpecialAirN_StartMotion,
    ftLk_SpecialAirN_StartMotion,
    ftSk_SpecialAirN_StartMotion,
    ftNs_SpecialAirNStart_Action,
    ftPe_SpecialAirN_StartMotion,
    ftPp_SpecialAirN_StartMotion,
    ftPp_SpecialAirN_StartMotion,
    ftPk_SpecialAirN_StartMotion,
    ftSs_SpecialAirN_StartMotion,
    ftYs_SpecialAirN_StartMotion,
    ftPr_SpecialAirN_StartMotion,
    ftMt_SpecialAirN_StartMotion,
    ftLg_SpecialAirN_StartMotion,
    ftMs_SpecialAirN_StartMotion,
    ftZd_SpecialAirN_StartMotion,
    ftLk_SpecialAirN_StartMotion,
    ftMr_SpecialAirN_StartMotion,
    ftFx_SpecialAirN_StartMotion,
    ftPk_SpecialAirN_StartMotion,
    ftGw_SpecialAirN_StartMotion,
    ftCa_SpecialAirN_StartMotion,
    ftMs_SpecialAirN_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialAirN_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialN[FTKIND_MAX] = {
    ftMr_SpecialN_StartMotion,
    ftFx_SpecialN_StartMotion,
    ftCa_SpecialN_StartMotion,
    ftDk_SpecialN_StartMotion,
    ftKb_SpecialN_StartMotion,
    ftKp_SpecialN_StartMotion,
    ftLk_SpecialN_StartMotion,
    ftSk_SpecialN_StartMotion,
    ftNs_SpecialNStart_Action,
    ftPe_SpecialN_StartMotion,
    ftPp_SpecialN_StartMotion,
    ftPp_SpecialN_StartMotion,
    ftPk_SpecialN_StartMotion,
    ftSs_SpecialN_StartMotion,
    ftYs_SpecialN_StartMotion,
    ftPr_SpecialN_StartMotion,
    ftMt_SpecialN_StartMotion,
    ftLg_SpecialN_StartMotion,
    ftMs_SpecialN_StartMotion,
    ftZd_SpecialN_StartMotion,
    ftLk_SpecialN_StartMotion,
    ftMr_SpecialN_StartMotion,
    ftFx_SpecialN_StartMotion,
    ftPk_SpecialN_StartMotion,
    ftGw_SpecialN_StartMotion,
    ftCa_SpecialN_StartMotion,
    ftMs_SpecialN_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialN_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialLw[FTKIND_MAX] = {
    ftMr_SpecialLw_StartMotion,
    ftFx_SpecialLw_StartMotion,
    ftCa_SpecialLw_StartMotion,
    ftDk_SpecialLw_StartMotion,
    ftKb_SpecialLw_StartMotion,
    ftKp_SpecialLw_StartMotion,
    ftLk_SpecialLw_StartMotion,
    ftSk_SpecialLw_StartMotion,
    ftNs_SpecialLwStart_Action,
    ftPe_SpecialLw_StartMotion,
    ftPp_SpecialLw_StartMotion,
    ftPp_SpecialLw_StartMotion,
    ftPk_SpecialLw_StartMotion,
    ftSs_SpecialLw_StartMotion,
    ftYs_SpecialLw_StartMotion,
    ftPr_SpecialLw_StartMotion,
    ftMt_SpecialLw_StartMotion,
    ftLg_SpecialLw_StartMotion,
    ftMs_SpecialLw_StartMotion,
    ftZd_SpecialLw_StartMotion,
    ftLk_SpecialLw_StartMotion,
    ftMr_SpecialLw_StartMotion,
    ftFx_SpecialLw_StartMotion,
    ftPk_SpecialLw_StartMotion,
    ftGw_SpecialLw_StartMotion,
    ftCa_SpecialLw_StartMotion,
    ftMs_SpecialLw_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialLw_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_SpecialHi[FTKIND_MAX] = {
    ftMr_SpecialHi_StartMotion,
    ftFx_SpecialHi_StartMotion,
    ftCa_SpecialHi_StartMotion,
    ftDk_SpecialHi_StartMotion,
    ftKb_SpecialHi_StartMotion,
    ftKp_SpecialHi_StartMotion,
    ftLk_SpecialHi_StartMotion,
    ftSk_SpecialHi_StartMotion,
    ftNs_SpecialHi_StartMotion,
    ftPe_SpecialHi_StartMotion,
    ftPp_SpecialHi_StartMotion,
    NULL,
    ftPk_SpecialHi_StartMotion,
    ftSs_SpecialHi_StartMotion,
    ftYs_SpecialHi_StartMotion,
    ftPr_SpecialHi_StartMotion,
    ftMt_SpecialHi_StartMotion,
    ftLg_SpecialHi_StartMotion,
    ftMs_SpecialHi_StartMotion,
    ftZd_SpecialHi_StartMotion,
    ftLk_SpecialHi_StartMotion,
    ftMr_SpecialHi_StartMotion,
    ftFx_SpecialHi_StartMotion,
    ftPk_SpecialHi_StartMotion,
    ftGw_SpecialHi_StartMotion,
    ftCa_SpecialHi_StartMotion,
    ftMs_SpecialHi_StartMotion,
    NULL,
    NULL,
    NULL,
    NULL,
    ftKp_SpecialHi_StartMotion,
    NULL,
};

HSD_GObjEvent ftData_OnAbsorb[FTKIND_MAX] = {
    NULL,          NULL, NULL,
    NULL,          NULL, NULL,
    NULL,          NULL, ftNs_Init_OnAbsorb,
    NULL,          NULL, NULL,
    NULL,          NULL, NULL,
    NULL,          NULL, NULL,
    NULL,          NULL, NULL,
    NULL,          NULL, NULL,
    ftGw_OnAbsorb, NULL, NULL,
    NULL,          NULL, NULL,
    NULL,          NULL, NULL,
};

Fighter_ItemEvent ftData_OnItemPickupExt[FTKIND_MAX] = {
    ftMr_Init_OnItemPickup,
    ftFx_Init_OnItemPickup,
    ftCa_Init_OnItemPickup,
    ftDk_Init_OnItemPickup,
    ftKb_Init_OnItemPickup,
    ftKp_Init_OnItemPickup,
    ftLk_Init_OnItemPickupExt,
    ftSk_Init_OnItemPickup,
    ftNs_Init_OnItemPickup,
    ftPe_Init_OnItemPickup,
    ftPp_Init_OnItemPickup,
    ftPp_Init_OnItemPickup,
    ftPk_Init_OnItemPickup,
    ftSs_Init_OnItemPickup,
    ftYs_Init_OnItemPickup,
    ftPr_Init_OnItemPickup,
    ftMt_Init_OnItemPickup,
    ftLg_Init_OnItemPickup,
    ftMs_Init_OnItemPickup,
    ftZd_Init_OnItemPickup,
    ftCl_Init_OnItemPickupExt,
    ftDr_Init_OnItemPickup,
    ftFc_Init_OnItemPickup,
    ftPc_Init_OnItemPickup,
    ftGw_Init_OnItemPickup,
    ftGn_Init_OnItemPickup,
    ftFe_Init_OnItemPickup,
    NULL,
    NULL,
    ftBo_Init_OnItemPickup,
    ftGl_Init_OnItemPickup,
    ftGk_Init_OnItemPickup,
    NULL,
};

HSD_GObjEvent ftData_OnItemInvisible[FTKIND_MAX] = {
    ftMr_Init_OnItemInvisible,
    ftFx_Init_OnItemInvisible,
    ftCa_Init_OnItemInvisible,
    ftDk_Init_OnItemInvisible,
    ftKb_Init_OnItemInvisible,
    ftKp_Init_OnItemInvisible,
    ftLk_Init_OnItemInvisible,
    ftSk_Init_OnItemInvisible,
    ftNs_Init_OnItemInvisible,
    ftPe_Init_OnItemInvisible,
    ftPp_Init_OnItemInvisible,
    ftPp_Init_OnItemInvisible,
    ftPk_Init_OnItemInvisible,
    ftSs_Init_OnItemInvisible,
    ftYs_Init_OnItemInvisible,
    ftPr_Init_OnItemInvisible,
    ftMt_Init_OnItemInvisible,
    ftLg_Init_OnItemInvisible,
    ftMs_Init_OnItemInvisible,
    ftZd_Init_OnItemInvisible,
    ftCl_Init_OnItemInvisible,
    ftDr_Init_OnItemInvisible,
    ftFc_Init_OnItemInvisible,
    ftPc_Init_OnItemInvisible,
    ftGw_Init_OnItemInvisible,
    ftGn_Init_OnItemInvisible,
    ftFe_Init_OnItemInvisible,
    NULL,
    NULL,
    ftBo_Init_OnItemInvisible,
    ftGl_Init_OnItemInvisible,
    ftGk_Init_OnItemInvisible,
    NULL,
};

HSD_GObjEvent ftData_OnItemVisible[FTKIND_MAX] = {
    ftMr_Init_OnItemVisible,
    ftFx_Init_OnItemVisible,
    ftCa_Init_OnItemVisible,
    ftDk_Init_OnItemVisible,
    ftKb_Init_OnItemVisible,
    ftKp_Init_OnItemVisible,
    ftLk_Init_OnItemVisible,
    ftSk_Init_OnItemVisible,
    ftNs_Init_OnItemVisible,
    ftPe_Init_OnItemVisible,
    ftPp_Init_OnItemVisible,
    ftPp_Init_OnItemVisible,
    ftPk_Init_OnItemVisible,
    ftSs_Init_OnItemVisible,
    ftYs_Init_OnItemVisible,
    ftPr_Init_OnItemVisible,
    ftMt_Init_OnItemVisible,
    ftLg_Init_OnItemVisible,
    ftMs_Init_OnItemVisible,
    ftZd_Init_OnItemVisible,
    ftCl_Init_OnItemVisible,
    ftDr_Init_OnItemVisible,
    ftFc_Init_OnItemVisible,
    ftPc_Init_OnItemVisible,
    ftGw_Init_OnItemVisible,
    ftGn_Init_OnItemVisible,
    ftFe_Init_OnItemVisible,
    NULL,
    NULL,
    ftBo_Init_OnItemVisible,
    ftGl_Init_OnItemVisible,
    ftGk_Init_OnItemVisible,
    NULL,
};

Fighter_ItemEvent ftData_OnItemDropExt[FTKIND_MAX] = {
    ftMr_Init_OnItemDrop,
    ftFx_Init_OnItemDrop,
    ftCa_Init_OnItemDrop,
    ftDk_Init_OnItemDrop,
    ftKb_Init_OnItemDrop,
    ftKp_Init_OnItemDrop,
    ftLk_Init_OnItemDropExt,
    ftSk_Init_OnItemDrop,
    ftNs_Init_OnItemDrop,
    ftPe_Init_OnItemDrop,
    ftPp_Init_OnItemDrop,
    ftPp_Init_OnItemDrop,
    ftPk_Init_OnItemDrop,
    ftSs_Init_OnItemDrop,
    ftYs_Init_OnItemDrop,
    ftPr_Init_OnItemDrop,
    ftMt_Init_OnItemDrop,
    ftLg_Init_OnItemDrop,
    ftMs_Init_OnItemDrop,
    ftZd_Init_OnItemDrop,
    ftCl_Init_OnItemDropExt,
    ftDr_Init_OnItemDrop,
    ftFc_Init_OnItemDrop,
    ftPc_Init_OnItemDrop,
    ftGw_Init_OnItemDrop,
    ftGn_Init_OnItemDrop,
    ftFe_Init_OnItemDrop,
    NULL,
    NULL,
    ftBo_Init_OnItemDrop,
    ftGl_Init_OnItemDrop,
    ftGk_Init_OnItemDrop,
    NULL,
};

Fighter_ItemEvent ftData_OnItemPickup[FTKIND_MAX] = {
    ftMr_Init_OnItemPickup,
    ftFx_Init_OnItemPickup,
    ftCa_Init_OnItemPickup,
    ftDk_Init_OnItemPickup,
    ftKb_Init_OnItemPickup,
    ftKp_Init_OnItemPickup,
    ftLk_Init_OnItemPickup,
    ftSk_Init_OnItemPickup,
    ftNs_Init_OnItemPickup,
    ftPe_Init_OnItemPickup,
    ftPp_Init_OnItemPickup,
    ftPp_Init_OnItemPickup,
    ftPk_Init_OnItemPickup,
    ftSs_Init_OnItemPickup,
    ftYs_Init_OnItemPickup,
    ftPr_Init_OnItemPickup,
    ftMt_Init_OnItemPickup,
    ftLg_Init_OnItemPickup,
    ftMs_Init_OnItemPickup,
    ftZd_Init_OnItemPickup,
    ftCl_Init_OnItemPickup,
    ftDr_Init_OnItemPickup,
    ftFc_Init_OnItemPickup,
    ftPc_Init_OnItemPickup,
    ftGw_Init_OnItemPickup,
    ftGn_Init_OnItemPickup,
    ftFe_Init_OnItemPickup,
    NULL,
    NULL,
    ftBo_Init_OnItemPickup,
    ftGl_Init_OnItemPickup,
    ftGk_Init_OnItemPickup,
    NULL,
};

Fighter_ItemEvent ftData_OnItemDrop[FTKIND_MAX] = {
    ftMr_Init_OnItemDrop,
    ftFx_Init_OnItemDrop,
    ftCa_Init_OnItemDrop,
    ftDk_Init_OnItemDrop,
    ftKb_Init_OnItemDrop,
    ftKp_Init_OnItemDrop,
    ftLk_Init_OnItemDrop,
    ftSk_Init_OnItemDrop,
    ftNs_Init_OnItemDrop,
    ftPe_Init_OnItemDrop,
    ftPp_Init_OnItemDrop,
    ftPp_Init_OnItemDrop,
    ftPk_Init_OnItemDrop,
    ftSs_Init_OnItemDrop,
    ftYs_Init_OnItemDrop,
    ftPr_Init_OnItemDrop,
    ftMt_Init_OnItemDrop,
    ftLg_Init_OnItemDrop,
    ftMs_Init_OnItemDrop,
    ftZd_Init_OnItemDrop,
    ftCl_Init_OnItemDrop,
    ftDr_Init_OnItemDrop,
    ftFc_Init_OnItemDrop,
    ftPc_Init_OnItemDrop,
    ftGw_Init_OnItemDrop,
    ftGn_Init_OnItemDrop,
    ftFe_Init_OnItemDrop,
    NULL,
    NULL,
    ftBo_Init_OnItemDrop,
    ftGl_Init_OnItemDrop,
    ftGk_Init_OnItemDrop,
    NULL,
};

HSD_GObjEvent ftData_UnkMotionStates1[FTKIND_MAX] = {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftPk_Init_UnkMotionStates1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

HSD_GObjEvent ftData_UnkMotionStates2[FTKIND_MAX] = {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftPk_Init_UnkMotionStates2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

HSD_GObjEvent ftData_OnKnockbackEnter[FTKIND_MAX] = {
    ftMr_Init_OnKnockbackEnter,
    ftFx_Init_OnKnockbackEnter,
    NULL,
    ftDk_Init_OnKnockbackEnter,
    ftKb_Init_OnKnockbackEnter,
    ftKp_Init_OnKnockbackEnter,
    ftLk_Init_OnKnockbackEnter,
    ftSk_Init_OnKnockbackEnter,
    ftNs_Init_OnKnockbackEnter,
    ftPe_Init_OnKnockbackEnter,
    ftPp_Init_OnKnockbackEnter,
    ftPp_Init_OnKnockbackEnter,
    ftPk_Init_OnKnockbackEnter,
    NULL,
    ftYs_Init_OnKnockbackEnter,
    ftPr_Init_OnKnockbackEnter,
    ftMt_Init_OnKnockbackEnter,
    ftLg_Init_OnKnockbackEnter,
    ftMs_Init_OnKnockbackEnter,
    ftZd_Init_OnKnockbackEnter,
    ftCl_Init_OnKnockbackEnter,
    ftDr_Init_OnKnockbackEnter,
    ftFc_Init_OnKnockbackEnter,
    ftPc_Init_OnKnockbackEnter,
    NULL,
    ftGn_Init_OnKnockbackEnter,
    ftFe_Init_OnKnockbackEnter,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGk_Init_OnKnockbackEnter,
    ftSb_Init_OnKnockbackEnter,
};

HSD_GObjEvent ftData_OnKnockbackExit[FTKIND_MAX] = {
    ftMr_Init_OnKnockbackExit,
    ftFx_Init_OnKnockbackExit,
    NULL,
    ftDk_Init_OnKnockbackExit,
    ftKb_Init_OnKnockbackExit,
    ftKp_Init_OnKnockbackExit,
    ftLk_Init_OnKnockbackExit,
    ftSk_Init_OnKnockbackExit,
    ftNs_Init_OnKnockbackExit,
    ftPe_Init_OnKnockbackExit,
    ftPp_Init_OnKnockbackExit,
    ftPp_Init_OnKnockbackExit,
    ftPk_Init_OnKnockbackExit,
    NULL,
    ftYs_Init_OnKnockbackExit,
    ftPr_Init_OnKnockbackExit,
    ftMt_Init_OnKnockbackExit,
    ftLg_Init_OnKnockbackExit,
    ftMs_Init_OnKnockbackExit,
    ftZd_Init_OnKnockbackExit,
    ftCl_Init_OnKnockbackExit,
    ftDr_Init_OnKnockbackExit,
    ftFc_Init_OnKnockbackExit,
    ftPc_Init_OnKnockbackExit,
    NULL,
    ftGn_Init_OnKnockbackExit,
    ftFe_Init_OnKnockbackExit,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGk_Init_OnKnockbackExit,
    ftSb_Init_OnKnockbackExit,
};

HSD_GObjEvent ftData_UnkMotionStates3[FTKIND_MAX] = {
    NULL,
    NULL,
    NULL,
    NULL,
    ftKb_Init_UnkMotionStates3,
    ftKp_Init_UnkMotionStates3,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGk_Init_UnkMotionStates3,
    NULL,
};

HSD_GObjEvent ftData_UnkMotionStates4[FTKIND_MAX] = {
    NULL,
    NULL,
    NULL,
    ftDk_Init_UnkMotionStates4,
    ftKb_Init_UnkMotionStates4,
    NULL,
    NULL,
    ftSk_Init_UnkMotionStates4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftSs_Init_UnkMotionStates4,
    NULL,
    NULL,
    ftMt_Init_UnkMotionStates4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGw_Init_UnkMotionStates4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

HSD_GObjEvent ftData_LoadSpecialAttrs[FTKIND_MAX] = {
    ftMr_Init_LoadSpecialAttrs, ftFx_Init_LoadSpecialAttrs,
    ftCa_Init_LoadSpecialAttrs, ftDk_Init_LoadSpecialAttrs,
    ftKb_Init_LoadSpecialAttrs, ftKp_Init_LoadSpecialAttrs,
    ftLk_Init_LoadSpecialAttrs, ftSk_Init_LoadSpecialAttrs,
    ftNs_Init_LoadSpecialAttrs, ftPe_Init_LoadSpecialAttrs,
    ftPp_Init_LoadSpecialAttrs, ftNn_Init_LoadSpecialAttrs,
    ftPk_Init_LoadSpecialAttrs, ftSs_Init_LoadSpecialAttrs,
    ftYs_Init_LoadSpecialAttrs, ftPr_Init_LoadSpecialAttrs,
    ftMt_Init_LoadSpecialAttrs, ftLg_Init_LoadSpecialAttrs,
    ftMs_Init_LoadSpecialAttrs, ftZd_Init_LoadSpecialAttrs,
    ftCl_Init_LoadSpecialAttrs, ftDr_Init_LoadSpecialAttrs,
    ftFc_Init_LoadSpecialAttrs, ftPc_Init_LoadSpecialAttrs,
    ftGw_Init_LoadSpecialAttrs, ftGn_Init_LoadSpecialAttrs,
    ftFe_Init_LoadSpecialAttrs, ftMh_Init_LoadSpecialAttrs,
    ftCh_Init_LoadSpecialAttrs, ftBo_Init_LoadSpecialAttrs,
    ftGl_Init_LoadSpecialAttrs, ftGk_Init_LoadSpecialAttrs,
    ftSb_Init_LoadSpecialAttrs,
};

/// Standard Character .dat File Names
char* ftData_803C1F40[FTKIND_MAX * 2] = {
    ftMr_Init_DatFilename, ftMr_Init_DataName,    ftFx_Init_DatFilename,
    ftFx_Init_DataName,    ftCa_Init_DatFilename, ftCa_Init_DataName,
    ftDk_Init_DatFilename, ftDk_Init_DataName,    ftKb_Init_DatFilename,
    ftKb_Init_DataName,    ftKp_Init_DatFilename, ftKp_Init_DataName,
    ftLk_Init_DatFilename, ftLk_Init_DataName,    ftSk_Init_DatFilename,
    ftSk_Init_DataName,    ftNs_Init_DatFilename, ftNs_Init_DataName,
    ftPe_Init_DatFilename, ftPe_Init_DataName,    ftPp_Init_DatFilename,
    ftPp_Init_DataName,    ftNn_Init_DatFilename, ftNn_Init_DataName,
    ftPk_Init_DatFilename, ftPk_Init_DataName,    ftSs_Init_DatFilename,
    ftSs_Init_DataName,    ftYs_Init_DatFilename, ftYs_Init_DataName,
    ftPr_Init_DatFilename, ftPr_Init_DataName,    ftMt_Init_DatFilename,
    ftMt_Init_DataName,    ftLg_Init_DatFilename, ftLg_Init_DataName,
    ftMs_Init_DatFilename, ftMs_Init_DataName,    ftZd_Init_DatFilename,
    ftZd_Init_DataName,    ftCl_Init_DatFilename, ftCl_Init_DataName,
    ftDr_Init_DatFilename, ftDr_Init_DataName,    ftFc_Init_DatFilename,
    ftFc_Init_DataName,    ftPc_Init_DatFilename, ftPc_Init_DataName,
    ftGw_Init_DatFilename, ftGw_Init_DataName,    ftGn_Init_DatFilename,
    ftGn_Init_DataName,    ftFe_Init_DatFilename, ftFe_Init_DataName,
    ftMh_Init_DatFilename, ftMh_Init_DataName,    ftCh_Init_DatFilename,
    ftCh_Init_DataName,    ftBo_Init_DatFilename, ftBo_Init_DataName,
    ftGl_Init_DatFilename, ftGl_Init_DataName,    ftGk_Init_DatFilename,
    ftGk_Init_DataName,    ftSb_Init_DatFilename, ftSb_Init_DataName,
};

HSD_GObjEvent ftData_UnkMotionStates5[FTKIND_MAX] = {
    NULL, NULL, NULL, NULL, ftKb_Init_UnkMotionStates5,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
};

Fighter_UnkMtxEvent ftData_UnkMtxFunc0[FTKIND_MAX] = {
    NULL,
    NULL,
    NULL,
    NULL,
    ftKb_UnkMtxFunc0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftPr_UnkMtxFunc0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

/// Character model group (e.g. high poly, low poly, metal) visibility change
/// callbacks
ftData_UnkModelStruct ftData_UnkIntBoolFunc0 = {
    {
        NULL,
        NULL,
        NULL,
        NULL,
        ftKb_UnkIntBoolFunc0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        ftPr_UnkIntBoolFunc0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
    },
    {
        NULL,
        NULL,
        NULL,
        NULL,
        ftKb_Init_UnkMotionStates6,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        ftPr_Init_UnkMotionStates6,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
    },
};

HSD_GObjEvent ftData_UnkCallbackPairs0[][FTKIND_MAX] = {
    {
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        ftKb_Init_UnkCallbackPairs0_0,
        ftKb_Init_UnkCallbackPairs0_1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
    },
    {
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    }

};

struct {
    /// Costume and Joint Strings
    Fighter_CostumeStrings* costume_strings[FTKIND_MAX];
    /// Animation .dat Filenames
    char* anim_dat_filenames[FTKIND_MAX];
} ftData_803C2360 = { {
                          ftMr_Init_CostumeStrings, ftFx_Init_CostumeStrings,
                          ftCa_Init_CostumeStrings, ftDk_Init_CostumeStrings,
                          ftKb_Init_CostumeStrings, ftKp_Init_CostumeStrings,
                          ftLk_Init_CostumeStrings, ftSk_Init_CostumeStrings,
                          ftNs_Init_CostumeStrings, ftPe_Init_CostumeStrings,
                          ftPp_Init_CostumeStrings, ftNn_Init_CostumeStrings,
                          ftPk_Init_CostumeStrings, ftSs_Init_CostumeStrings,
                          ftYs_Init_CostumeStrings, ftPr_Init_CostumeStrings,
                          ftMt_Init_CostumeStrings, ftLg_Init_CostumeStrings,
                          ftMs_Init_CostumeStrings, ftZd_Init_CostumeStrings,
                          ftCl_Init_CostumeStrings, ftDr_Init_CostumeStrings,
                          ftFc_Init_CostumeStrings, ftPc_Init_CostumeStrings,
                          ftGw_Init_CostumeStrings, ftGn_Init_CostumeStrings,
                          ftFe_Init_CostumeStrings, ftMh_Init_CostumeStrings,
                          ftCh_Init_CostumeStrings, ftBo_Init_CostumeStrings,
                          ftGl_Init_CostumeStrings, ftGk_Init_CostumeStrings,
                          ftSb_Init_CostumeStrings,
                      },
                      {
                          ftMr_Init_AnimDatFilename, ftFx_Init_AnimDatFilename,
                          ftCa_Init_AnimDatFilename, ftDk_Init_AnimDatFilename,
                          ftKb_Init_AnimDatFilename, ftKp_Init_AnimDatFilename,
                          ftLk_Init_AnimDatFilename, ftSk_Init_AnimDatFilename,
                          ftNs_Init_AnimDatFilename, ftPe_Init_AnimDatFilename,
                          ftPp_Init_AnimDatFilename, ftNn_Init_AnimDatFilename,
                          ftPk_Init_AnimDatFilename, ftSs_Init_AnimDatFilename,
                          ftYs_Init_AnimDatFilename, ftPr_Init_AnimDatFilename,
                          ftMt_Init_AnimDatFilename, ftLg_Init_AnimDatFilename,
                          ftMs_Init_AnimDatFilename, ftZd_Init_AnimDatFilename,
                          ftCl_Init_AnimDatFilename, ftDr_Init_AnimDatFilename,
                          ftFc_Init_AnimDatFilename, ftPc_Init_AnimDatFilename,
                          ftGw_Init_AnimDatFilename, ftGn_Init_AnimDatFilename,
                          ftFe_Init_AnimDatFilename, ftMh_Init_AnimDatFilename,
                          ftCh_Init_AnimDatFilename, ftBo_Init_AnimDatFilename,
                          ftGl_Init_AnimDatFilename, ftGk_Init_AnimDatFilename,
                          ftSb_Init_AnimDatFilename,
                      }

};

/// Demo Lookup Strings
Fighter_DemoStrings* ftData_803C2468[FTKIND_MAX] = {
    &ftMr_Init_DemoMotionFilenames,
    &ftFx_Init_DemoMotionFilenames,
    &ftCa_Init_DemoMotionFilenames,
    &ftDk_Init_DemoMotionFilenames,
    &ftKb_Init_DemoMotionFilenames,
    &ftKp_Init_DemoMotionFilenames,
    &ftLk_Init_DemoMotionFilenames,
    &ftSk_Init_DemoMotionFilenames,
    &ftNs_Init_DemoMotionFilenames,
    &ftPe_Init_DemoMotionFilenames,
    &ftPp_Init_DemoMotionFilenames,
    &ftNn_Init_DemoMotionFilenames,
    &ftPk_Init_DemoMotionFilenames,
    &ftSs_Init_DemoMotionFilenames,
    &ftYs_Init_DemoMotionFilenames,
    &ftPr_Init_DemoMotionFilenames,
    &ftMt_Init_DemoMotionFilenames,
    &ftLg_Init_DemoMotionFilenames,
    &ftMs_Init_DemoMotionFilenames,
    &ftZd_Init_DemoMotionFilenames,
    &ftCl_Init_DemoMotionFilenames,
    &ftDr_Init_DemoMotionFilenames,
    &ftFc_Init_DemoMotionFilenames,
    &ftPc_Init_DemoMotionFilenames,
    &ftGw_Init_DemoMotionFilenames,
    &ftGn_Init_DemoMotionFilenames,
    &ftFe_Init_DemoMotionFilenames,
    NULL,
    NULL,
    NULL,
    NULL,
    &ftGk_Init_DemoMotionFilenames,
    NULL,
};

Fighter_MotionFileStringGetter ftData_803C24EC[FTKIND_MAX] = {
    ftMr_Init_GetMotionFileString,
    NULL,
    NULL,
    NULL,
    ftKb_Init_GetMotionFileString,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftLg_Init_GetMotionFileString,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGk_Init_GetMotionFileString,
    NULL,
};

Fighter_UnkPtrEvent ftData_UnkDemoCallbacks0[FTKIND_MAX] = {
    ftMr_Init_UnkDemoCallbacks0,
    NULL,
    NULL,
    NULL,
    ftKb_Init_UnkDemoCallbacks0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftLg_Init_UnkDemoCallbacks0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ftGk_Init_UnkDemoCallbacks0,
    NULL,
};

ftData_UnkCountStruct ftData_UnkIntPairs[FTKIND_MAX] = {
    { 0, 16 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 18 }, { 0, 14 },
    { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 },
    { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 16 },
    { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 },
    { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 }, { 0, 14 },
    { 0, 14 }, { 0, 15 }, { 0, 14 },
};

s8 ftData_UnkBytePerCharacter[FTKIND_MAX] = {
    1,  3,  4,  8, 5, 12, 6, 17, 10, 15, 14, 14, 7,  2,  9,  11, 13,
    18, 16, 17, 6, 1, 3,  7, -1, 19, 49, -1, -1, -1, -1, 12, -1,
};
