#include <melee/ft/chara/ftCrazyHand/ftcrazyhand.h>
#include <melee/ft/chara/ftKirby/ftkirby.h>
#include <melee/ft/chara/ftMasterHand/ftMasterHand_32.h>
#include <melee/ft/chara/ftMasterHand/ftMasterHand_33.h>
#include <melee/ft/chara/ftMasterHand/ftMasterHand_34.h>
#include <melee/ft/ft_unknown_006.h>
#include <melee/ft/ftcliffcommon.h>
#include <melee/ft/types.h>
#include <Runtime/platform.h>
