#ifndef GALE01_32AC28
#define GALE01_32AC28

#include <placeholder.h>

/* 32AC28 */ UNK_RET TRKLoadContext(UNK_PARAMS);
/* 32ACB0 */ UNK_RET TRKEXICallBack(UNK_PARAMS);
/* 32ACE8 */ UNK_RET InitMetroTRKCommTable(UNK_PARAMS);
/* 32ADD0 */ UNK_RET TRKUARTInterruptHandler(UNK_PARAMS);
/* 32ADD4 */ UNK_RET TRKInitializeIntDrivenUART(UNK_PARAMS);
/* 32AE14 */ UNK_RET EnableEXI2Interrupts(UNK_PARAMS);
/* 32AE44 */ UNK_RET TRKPollUART(UNK_PARAMS);
/* 32AE74 */ UNK_RET TRK_ReadUARTN(UNK_PARAMS);
/* 32AEB8 */ UNK_RET TRK_WriteUARTN(UNK_PARAMS);
/* 32AEFC */ UNK_RET ReserveEXI2Port(UNK_PARAMS);
/* 32AF2C */ UNK_RET UnreserveEXI2Port(UNK_PARAMS);
/* 32AF5C */ UNK_RET TRK_board_display(UNK_PARAMS);

#endif
