#include "it_266F.h"
#include "types.h"

#include "items/itcerebi.h"
#include "items/itchicorita.h"
#include "items/itchicoritaleaf.h"
#include "items/itentei.h"
#include "items/itfire.h"
#include "items/itfreezer.h"
#include "items/itfushigibana.h"
#include "items/ithassam.h"
#include "items/ithinoarashi.h"
#include "items/ithitodeman.h"
#include "items/ithouou.h"
#include "items/itkabigon.h"
#include "items/itkamex.h"
#include "items/itkireihana.h"
#include "items/itlizardon.h"
#include "items/itlucky.h"
#include "items/itlugia.h"
#include "items/itmaril.h"
#include "items/itmarumine.h"
#include "items/itmatadogas.h"
#include "items/itmetamon.h"
#include "items/itmew.h"
#include "items/itoldkuri.h"
#include "items/itpippi.h"
#include "items/itporygon2.h"
#include "items/itraikou.h"
#include "items/itsonans.h"
#include "items/itsuikun.h"
#include "items/itthunder.h"
#include "items/ittogepy.h"
#include "items/ittosakinto.h"
#include "items/itunknown.h"

#include <stddef.h>

static int const count = 47;

struct sdata_ItemGXLink it_803F2310[count] = {
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
    it_8026EECC, it_8026EECC,
};

ItemLogicTable it_803F23CC[count] = {
    {
        // Tosakinto (Goldeen)
        it_803F7A48,
        it_802C8F4C,
        it_802C9504,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802C8FC4,
    },
    {
        // Chicorita
        it_803F7A98,
        it_802C9588,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802C961C,
    },
    {
        // Kabigon (Snorlax)
        it_803F7AD8,
        it_802C9D40,
        it_802C9E00,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802C9E24,
    },
    {
        // Kamex (Blastoise)
        it_803F7B08,
        it_802CA49C,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CA538,
    },
    {
        // Matadogas (Weezing)
        it_803F7B58,
        it_802CAFD4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CB0F8,
    },
    {
        // Lizardon (Charizard)
        it_803F7BC0,
        it_802CB8AC,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CB940,
    },
    {
        // Fire (Moltres)
        it_803F7C10,
        it_802CC6E4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CC744,
    },
    {
        // Thunder (Zapdos)
        it_803F7C40,
        it_802CCAB4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CCB14,
    },
    {
        // Freezer (Articuno)
        it_803F7C70,
        it_802CCF9C,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CD000,
    },
    {
        // Sonans (Wobbuffet)
        it_803F7CA0,
        it_802CD44C,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CD7B8,
        it_802CD7D4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CD4DC,
    },
    {
        // Hassam (Scizor)
        it_803F7CF8,
        it_802CDBE0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CDC60,
    },
    {
        // Unknown (Unown)
        it_803F7D60,
        it_802CE710,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CE7D0,
    },
    {
        // Entei
        it_803F7DC8,
        it_802CF3E0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CF450,
    },
    {
        // Raikou
        it_803F7DE8,
        it_802CF814,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CF884,
    },
    {
        // Suikun (Suicune)
        it_803F7E08,
        it_802CFC48,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CFCB8,
    },
    {
        // Kireihana (Bellossom)
        it_803F7E28,
        it_802D007C,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D0118,
    },
    {
        // Marumine (Electrode)
        it_803F7E78,
        it_802D0A0C,
        NULL,
        it_802D0D18,
        it_802D0E30,
        it_802D0E90,
        it_802D0AD0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D0AB0,
    },
    {
        // Lugia
        it_803F7EE8,
        it_802D1438,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D14D4,
    },
    {
        // Houou (Ho-oh)
        it_803F7F58,
        it_802D251C,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D25BC,
    },
    {
        // Metamon (Ditto)
        it_803F7FC8,
        it_802D3008,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D3070,
    },
    {
        // Pippi (Clefairy)
        it_803F7FF8,
        it_802D3260,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D32DC,
    },
    {
        // Togepy
        it_803F8058,
        it_802D36B0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D372C,
    },
    {
        // Mew
        it_803F80C8,
        it_802D3B18,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D3B6C,
    },
    {
        // Cerebi
        it_803F80F8,
        it_802D3EF8,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D3F4C,
    },
    {
        // Hitodeman (Staryu)
        it_803F8128,
        it_802D42C4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D43B0,
    },
    {
        // Lucky (Chansey)
        it_803F8190,
        it_802D5050,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D5648,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D56F0,
    },
    {
        // Porygon2
        it_803F8250,
        it_802D5ABC,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D5CD8,
    },
    {
        // Hinoarashi (Cyndaquil)
        it_803F8270,
        it_802D5CF8,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D6100,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D61A8,
    },
    {
        // Maril
        it_803F82B0,
        it_802D6870,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D6F00,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D6FB0,
    },
    {
        // Fushigibana (Venusaur)
        it_803F82F0,
        it_802D6FD0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D73D0,
    },
    {
        // Chicorita leaf
        it_803F7AC8,
        it_802C9C20,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802C9C78,
        NULL,
        NULL,
        it_802C9CA0,
        it_802C9C78,
        it_802C9C78,
        NULL,
        it_802C9C78,
        it_802C9C80,
    },
    {
        // Kamex hydro pump
        it_803F7B48,
        it_802CACD0,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CADC8,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CADC0,
        it_802CADD0,
    },
    {
        // Matadogas gas 1
        it_803F7BB0,
        it_802CB690,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CB778,
    },
    {
        // Matadogas gas 2
        it_803F7BB0,
        it_802CB704,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CB778,
    },
    {
        // Lizardon flame 1
        it_803F7C00,
        it_802CC3D4,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CC5A4,
        NULL,
        it_802CC5CC,
        NULL,
        it_802CC5C4,
        it_802CC584,
    },
    {
        // Lizardon flame 2
        it_803F7C00,
        it_802CC440,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CC5A4,
        NULL,
        it_802CC5CC,
        NULL,
        it_802CC5C4,
        it_802CC584,
    },
    {
        // Lizardon flame 3
        it_803F7C00,
        it_802CC4AC,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CC5A4,
        NULL,
        it_802CC5CC,
        NULL,
        it_802CC5C4,
        it_802CC584,
    },
    {
        // Lizardon flame 4
        it_803F7C00,
        it_802CC518,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CC5A4,
        NULL,
        it_802CC5CC,
        NULL,
        it_802CC5C4,
        it_802CC584,
    },
    {
        // Unknown swarm (mini-unowns)
        it_803F7D90,
        it_802CEEC8,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802CF0B4,
    },
    {
        // Lugia aeroblast 1
        it_803F7F48,
        it_802D2308,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D23D4,
    },
    {
        // Lugia aeroblast 2
        it_803F7F48,
        it_802D234C,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D23D4,
    },
    {
        // Lugia aeroblast 3
        it_803F7F48,
        it_802D2390,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D23D4,
    },
    {
        // Houou sacred fire
        it_803F7FB8,
        it_802D2E80,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D2ED0,
    },
    {
        // Hitodeman star
        it_803F8180,
        it_802D4DE0,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D4EF4,
        NULL,
        NULL,
        it_802D4F28,
        NULL,
        it_802D4F48,
        it_802D4F08,
        it_802D4F50,
        it_802D4F58,
    },
    {
        // Lucky egg
        it_803F8200,
        it_802D57D0,
        NULL,
        it_802D59A8,
        it_802D59DC,
        NULL,
        NULL,
        NULL,
        it_802D5A04,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D5A9C,
    },
    {
        // Hinoarashi flame
        it_803F82A0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        it_802D6808,
        NULL,
        NULL,
        it_802D6810,
        it_802D6830,
        it_802D6838,
        it_802D6840,
        it_802D6848,
        it_802D6850,
    },
    {
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
    },
};
