// #include <platform.h>

// #include "it_266F.h"

// #include "it/types.h"
// #include "items/itbat.h"
// #include "items/itbombhei.h"
// #include "items/itbox.h"
// #include "items/itcapsule.h"
// #include "items/itdkinoko.h"
// #include "items/itdosei.h"
// #include "items/itegg.h"
// #include "items/itevyoshiegg.h"
// #include "items/itfflower.h"
// #include "items/itfflowerflame.h"
// #include "items/itflipper.h"
// #include "items/itfoods.h"
// #include "items/itfreeze.h"
// #include "items/itgshell.h"
// #include "items/ithammer.h"
// #include "items/ithammerhead.h"
// #include "items/itharisen.h"
// #include "items/itheart.h"
// #include "items/itkinoko.h"
// #include "items/itkusudama.h"
// #include "items/itlgun.h"
// #include "items/itlgunbeam.h"
// #include "items/itlgunray.h"
// #include "items/itlipstick.h"
// #include "items/itlipstickspore.h"
// #include "items/itmball.h"
// #include "items/itmetalb.h"
// #include "items/itmsbomb.h"
// #include "items/itparasol.h"
// #include "items/itrabbitc.h"
// #include "items/itrshell.h"
// #include "items/itscball.h"
// #include "items/itspycloak.h"
// #include "items/itsscope.h"
// #include "items/itsscopebeam.h"
// #include "items/itstar.h"
// #include "items/itstarrod.h"
// #include "items/itstarrodstar.h"
// #include "items/itsword.h"
// #include "items/ittaru.h"
// #include "items/ittarucann.h"
// #include "items/ittomato.h"
// #include "items/itwstar.h"

// struct sdata_ItemGXLink it_803F1418[] = {
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_80284E10, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC, it_8026EECC,
//     it_8026EECC, it_8026EECC, it_8026EECC,
// };

// // Common items
// struct ItemLogicTable it_803F14C4[ARRAY_SIZE(it_803F1418)] = {
//     {
//         // Capsule
//         it_803F5468,
//         it_3F14_Logic0_Spawned,
//         NULL,
//         it_3F14_Logic0_PickedUp,
//         it_3F14_Logic0_Dropped,
//         it_3F14_Logic0_Thrown,
//         it_3F14_Logic0_DmgDealt,
//         it_3F14_Logic0_DmgReceived,
//         it_3F14_Logic0_EnteredAir,
//         it_3F14_Logic0_Reflected,
//         it_3F14_Logic0_Clanked,
//         NULL,
//         it_3F14_Logic0_ShieldBounced,
//         it_3F14_Logic0_HitShield,
//         it_3F14_Logic0_EvtUnk,
//     },
//     {
//         // Box
//         it_803F5850,
//         it_3F14_Logic1_Spawned,
//         it_3F14_Logic1_Destroyed,
//         it_3F14_Logic1_PickedUp,
//         it_3F14_Logic1_Dropped,
//         it_3F14_Logic1_Thrown,
//         it_3F14_Logic1_DmgDealt,
//         it_3F14_Logic1_DmgReceived,
//         it_3F14_Logic1_EnteredAir,
//         it_3F14_Logic1_Reflected,
//         it_3F14_Logic1_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic1_HitShield,
//         it_3F14_Logic1_EvtUnk,
//     },
//     {
//         // Taru
//         it_803F58E0,
//         it_3F14_Logic2_Spawned,
//         NULL,
//         it_3F14_Logic2_PickedUp,
//         it_3F14_Logic2_Dropped,
//         it_3F14_Logic2_Thrown,
//         it_3F14_Logic2_DmgDealt,
//         it_3F14_Logic2_DmgReceived,
//         NULL,
//         it_3F14_Logic2_Reflected,
//         it_3F14_Logic2_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic2_HitShield,
//         it_3F14_Logic2_EvtUnk,
//     },
//     {
//         // Egg
//         it_803F5988,
//         it_3F14_Logic3_Spawned,
//         NULL,
//         it_3F14_Logic3_PickedUp,
//         it_3F14_Logic3_Dropped,
//         it_3F14_Logic3_Thrown,
//         it_3F14_Logic3_DmgDealt,
//         it_3F14_Logic3_DmgReceived,
//         it_3F14_Logic3_EnteredAir,
//         it_3F14_Logic3_Reflected,
//         it_3F14_Logic3_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic3_HitShield,
//         it_3F14_Logic3_EvtUnk,
//     },
//     {
//         // Kusudama
//         it_803F59F8,
//         it_3F14_Logic4_Spawned,
//         NULL,
//         it_3F14_Logic4_PickedUp,
//         it_3F14_Logic4_Dropped,
//         it_3F14_Logic4_Thrown,
//         it_3F14_Logic4_DmgDealt,
//         it_3F14_Logic4_DmgReceived,
//         NULL,
//         it_3F14_Logic4_Reflected,
//         it_3F14_Logic4_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic4_HitShield,
//         it_3F14_Logic4_EvtUnk,
//     },
//     {
//         // TaruCann
//         it_803F63C0,
//         it_3F14_Logic5_Spawned,
//         it_3F14_Logic5_Destroyed,
//         it_3F14_Logic5_PickedUp,
//         it_3F14_Logic5_Dropped,
//         it_3F14_Logic5_Thrown,
//         it_3F14_Logic5_DmgDealt,
//         NULL,
//         NULL,
//         it_3F14_Logic5_Reflected,
//         it_3F14_Logic5_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic5_HitShield,
//         it_3F14_Logic5_EvtUnk,
//     },
//     {
//         // BombHei
//         it_803F54D8,
//         it_3F14_Logic6_Spawned,
//         NULL,
//         it_3F14_Logic6_PickedUp,
//         it_3F14_Logic6_Dropped,
//         it_3F14_Logic6_Thrown,
//         it_3F14_Logic6_DmgDealt,
//         it_3F14_Logic6_DmgReceived,
//         it_3F14_Logic6_EnteredAir,
//         it_3F14_Logic6_Reflected,
//         it_3F14_Logic6_Clanked,
//         NULL,
//         it_3F14_Logic6_ShieldBounced,
//         it_3F14_Logic6_HitShield,
//         it_3F14_Logic6_EvtUnk,
//     },
//     {
//         // Dosei
//         it_803F55D0,
//         it_3F14_Logic7_Spawned,
//         NULL,
//         it_3F14_Logic7_PickedUp,
//         it_3F14_Logic7_Dropped,
//         it_3F14_Logic7_Thrown,
//         it_3F14_Logic7_DmgDealt,
//         it_3F14_Logic7_DmgReceived,
//         it_3F14_Logic7_EnteredAir,
//         it_3F14_Logic7_Reflected,
//         it_3F14_Logic7_Clanked,
//         NULL,
//         it_3F14_Logic7_ShieldBounced,
//         it_3F14_Logic7_HitShield,
//         it_3F14_Logic7_EvtUnk,
//     },
//     {
//         // Heart
//         it_803F56C8,
//         it_3F14_Logic8_Spawned,
//         it_3F14_Logic8_Destroyed,
//         it_3F14_Logic8_PickedUp,
//         it_3F14_Logic8_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic8_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic8_EvtUnk,
//     },
//     {
//         // Tomato
//         it_803F5740,
//         it_3F14_Logic9_Spawned,
//         it_3F14_Logic9_Destroyed,
//         it_3F14_Logic9_PickedUp,
//         it_3F14_Logic9_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic9_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic9_EvtUnk,
//     },
//     {
//         // Star
//         it_803F57A0,
//         it_3F14_Logic10_Spawned,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic10_DmgDealt,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic10_EvtUnk,
//     },
//     {
//         // Bat
//         it_803F57B0,
//         it_3F14_Logic11_Spawned,
//         NULL,
//         it_3F14_Logic11_PickedUp,
//         it_3F14_Logic11_Dropped,
//         it_3F14_Logic11_Thrown,
//         it_3F14_Logic11_DmgDealt,
//         NULL,
//         it_3F14_Logic11_EnteredAir,
//         it_3F14_Logic11_Reflected,
//         it_3F14_Logic11_Clanked,
//         NULL,
//         it_3F14_Logic11_ShieldBounced,
//         it_3F14_Logic11_HitShield,
//         it_3F14_Logic11_EvtUnk,
//     },
//     {
//         // Sword
//         it_803F5800,
//         it_3F14_Logic12_Spawned,
//         NULL,
//         it_3F14_Logic12_PickedUp,
//         it_3F14_Logic12_Dropped,
//         it_3F14_Logic12_Thrown,
//         it_3F14_Logic12_DmgDealt,
//         NULL,
//         it_3F14_Logic12_EnteredAir,
//         it_3F14_Logic12_Reflected,
//         it_3F14_Logic12_Clanked,
//         NULL,
//         it_3F14_Logic12_ShieldBounced,
//         it_3F14_Logic12_HitShield,
//         it_3F14_Logic12_EvtUnk,
//     },
//     {
//         // Parasol
//         it_803F5AB0,
//         it_3F14_Logic13_Spawned,
//         NULL,
//         it_3F14_Logic13_PickedUp,
//         it_3F14_Logic13_Dropped,
//         it_3F14_Logic13_Thrown,
//         it_3F14_Logic13_DmgDealt,
//         NULL,
//         it_3F14_Logic13_EnteredAir,
//         it_3F14_Logic13_Reflected,
//         it_3F14_Logic13_Clanked,
//         NULL,
//         it_3F14_Logic13_ShieldBounced,
//         it_3F14_Logic13_HitShield,
//         it_3F14_Logic13_EvtUnk,
//     },
//     {
//         // G Shell
//         it_803F5BA8,
//         it_3F14_Logic14_Spawned,
//         NULL,
//         it_3F14_Logic14_PickedUp,
//         it_3F14_Logic14_Dropped,
//         it_3F14_Logic14_Thrown,
//         it_3F14_Logic14_DmgDealt,
//         it_3F14_Logic14_DmgReceived,
//         it_3F14_Logic14_EnteredAir,
//         it_3F14_Logic14_Reflected,
//         it_3F14_Logic14_Clanked,
//         NULL,
//         it_3F14_Logic14_ShieldBounced,
//         it_3F14_Logic14_HitShield,
//         it_3F14_Logic14_EvtUnk,
//     },
//     {
//         // R Shell
//         it_803F5C48,
//         it_3F14_Logic15_Spawned,
//         NULL,
//         it_3F14_Logic15_PickedUp,
//         it_3F14_Logic15_Dropped,
//         it_3F14_Logic15_Thrown,
//         it_3F14_Logic15_DmgDealt,
//         it_3F14_Logic15_DmgReceived,
//         it_3F14_Logic15_EnteredAir,
//         it_3F14_Logic15_Reflected,
//         it_3F14_Logic15_Clanked,
//         NULL,
//         it_3F14_Logic15_ShieldBounced,
//         it_3F14_Logic15_HitShield,
//         it_3F14_Logic15_EvtUnk,
//     },
//     {
//         // L Gun
//         it_803F5CC8,
//         it_3F14_Logic16_Spawned,
//         NULL,
//         it_3F14_Logic16_PickedUp,
//         it_3F14_Logic16_Dropped,
//         it_3F14_Logic16_Thrown,
//         it_3F14_Logic16_DmgDealt,
//         NULL,
//         it_3F14_Logic16_EnteredAir,
//         it_3F14_Logic16_Reflected,
//         it_3F14_Logic16_Clanked,
//         NULL,
//         it_3F14_Logic16_ShieldBounced,
//         it_3F14_Logic16_HitShield,
//         it_3F14_Logic16_EvtUnk,
//     },
//     {
//         // Freeze
//         it_803F5D28,
//         it_3F14_Logic17_Spawned,
//         it_3F14_Logic17_Destroyed,
//         it_3F14_Logic17_PickedUp,
//         it_3F14_Logic17_Dropped,
//         it_3F14_Logic17_Thrown,
//         it_3F14_Logic17_DmgDealt,
//         it_3F14_Logic17_DmgReceived,
//         NULL,
//         it_3F14_Logic17_Reflected,
//         it_3F14_Logic17_Clanked,
//         it_3F14_Logic17_Absorbed,
//         it_3F14_Logic17_ShieldBounced,
//         it_3F14_Logic17_HitShield,
//         it_3F14_Logic17_EvtUnk,
//     },
//     {
//         // Foods
//         it_803F5DB0,
//         it_3F14_Logic18_Spawned,
//         NULL,
//         it_3F14_Logic18_PickedUp,
//         it_3F14_Logic18_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic18_EvtUnk,
//     },
//     {
//         // MSBomb
//         ItemStateTable_MsBomb,
//         it_3F14_Logic19_Spawned,
//         NULL,
//         it_3F14_Logic19_PickedUp,
//         it_3F14_Logic19_Dropped,
//         it_3F14_Logic19_Thrown,
//         it_3F14_Logic19_DmgDealt,
//         it_3F14_Logic19_DmgReceived,
//         it_3F14_Logic19_EnteredAir,
//         it_3F14_Logic19_Reflected,
//         it_3F14_Logic19_Clanked,
//         NULL,
//         it_3F14_Logic19_ShieldBounced,
//         it_3F14_Logic19_HitShield,
//         it_3F14_Logic19_EvtUnk,
//     },
//     {
//         // Flipper
//         it_803F5EA8,
//         it_3F14_Logic20_Spawned,
//         NULL,
//         it_3F14_Logic20_PickedUp,
//         it_3F14_Logic20_Dropped,
//         it_3F14_Logic20_Thrown,
//         it_3F14_Logic20_DmgDealt,
//         it_3F14_Logic20_DmgReceived,
//         it_3F14_Logic20_EnteredAir,
//         it_3F14_Logic20_Reflected,
//         it_3F14_Logic20_Clanked,
//         NULL,
//         it_3F14_Logic20_ShieldBounced,
//         it_3F14_Logic20_HitShield,
//         it_3F14_Logic20_EvtUnk,
//     },
//     {
//         // S_Scope
//         it_803F5F40,
//         it_3F14_Logic21_Spawned,
//         NULL,
//         it_3F14_Logic21_PickedUp,
//         it_3F14_Logic21_Dropped,
//         it_3F14_Logic21_Thrown,
//         it_3F14_Logic21_DmgDealt,
//         NULL,
//         it_3F14_Logic21_EnteredAir,
//         it_3F14_Logic21_Reflected,
//         it_3F14_Logic21_Clanked,
//         NULL,
//         it_3F14_Logic21_ShieldBounced,
//         it_3F14_Logic21_HitShield,
//         it_3F14_Logic21_EvtUnk,
//     },
//     {
//         // StarRod
//         it_803F5F90,
//         it_3F14_Logic22_Spawned,
//         NULL,
//         it_3F14_Logic22_PickedUp,
//         it_3F14_Logic22_Dropped,
//         it_3F14_Logic22_Thrown,
//         it_3F14_Logic22_DmgDealt,
//         NULL,
//         it_3F14_Logic22_EnteredAir,
//         it_3F14_Logic22_Reflected,
//         it_3F14_Logic22_Clanked,
//         NULL,
//         it_3F14_Logic22_ShieldBounced,
//         it_3F14_Logic22_HitShield,
//         it_3F14_Logic22_EvtUnk,
//     },
//     {
//         // LipStick
//         it_803F6310,
//         it_3F14_Logic23_Spawned,
//         NULL,
//         it_3F14_Logic23_PickedUp,
//         it_3F14_Logic23_Dropped,
//         it_3F14_Logic23_Thrown,
//         it_3F14_Logic23_DmgDealt,
//         NULL,
//         it_3F14_Logic23_EnteredAir,
//         it_3F14_Logic23_Reflected,
//         it_3F14_Logic23_Clanked,
//         NULL,
//         it_3F14_Logic23_ShieldBounced,
//         it_3F14_Logic23_HitShield,
//         it_3F14_Logic23_EvtUnk,
//     },
//     {
//         // Harisen
//         it_803F5FF0,
//         it_3F14_Logic24_Spawned,
//         NULL,
//         it_3F14_Logic24_PickedUp,
//         it_3F14_Logic24_Dropped,
//         it_3F14_Logic24_Thrown,
//         it_3F14_Logic24_DmgDealt,
//         NULL,
//         it_3F14_Logic24_EnteredAir,
//         it_3F14_Logic24_Reflected,
//         it_3F14_Logic24_Clanked,
//         NULL,
//         it_3F14_Logic24_ShieldBounced,
//         it_3F14_Logic24_HitShield,
//         it_3F14_Logic24_EvtUnk,
//     },
//     {
//         // F Flower
//         it_803F6090,
//         it_3F14_Logic25_Spawned,
//         NULL,
//         it_3F14_Logic25_PickedUp,
//         it_3F14_Logic25_Dropped,
//         it_3F14_Logic25_Thrown,
//         it_3F14_Logic25_DmgDealt,
//         NULL,
//         it_3F14_Logic25_EnteredAir,
//         it_3F14_Logic25_Reflected,
//         it_3F14_Logic25_Clanked,
//         NULL,
//         it_3F14_Logic25_ShieldBounced,
//         it_3F14_Logic25_HitShield,
//         it_3F14_Logic25_EvtUnk,
//     },
//     {
//         // Kinoko
//         it_803F6110,
//         it_3F14_Logic26_Spawned,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic26_DmgDealt,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic26_EvtUnk,
//     },
//     {
//         // DKinoko
//         it_803F6130,
//         it_3F14_Logic27_Spawned,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic27_DmgDealt,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic27_EvtUnk,
//     },
//     {
//         // Hammer
//         it_803F6150,
//         it_3F14_Logic28_Spawned,
//         NULL,
//         it_3F14_Logic28_PickedUp,
//         it_3F14_Logic28_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic28_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic28_EvtUnk,
//     },
//     {
//         // WStar
//         it_803F61B0,
//         it_3F14_Logic29_Spawned,
//         NULL,
//         it_3F14_Logic29_PickedUp,
//         it_3F14_Logic29_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic29_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic30_EvtUnk,
//     },
//     {
//         // ScBall
//         it_803F6220,
//         it_3F14_Logic30_Spawned,
//         NULL,
//         it_3F14_Logic30_PickedUp,
//         it_3F14_Logic30_Dropped,
//         it_3F14_Logic30_Thrown,
//         it_3F14_Logic30_DmgDealt,
//         NULL,
//         it_3F14_Logic30_EnteredAir,
//         it_3F14_Logic30_Reflected,
//         it_3F14_Logic30_Clanked,
//         NULL,
//         it_3F14_Logic30_ShieldBounced,
//         it_3F14_Logic30_HitShield,
//         it_3F14_Logic30_EvtUnk,
//     },
//     {
//         // RabbitC
//         it_803F6270,
//         it_3F14_Logic31_Spawned,
//         NULL,
//         it_3F14_Logic31_PickedUp,
//         it_3F14_Logic31_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic31_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic31_EvtUnk,
//     },
//     {
//         // MetalB
//         it_803F62C0,
//         it_3F14_Logic32_Spawned,
//         NULL,
//         it_3F14_Logic32_PickedUp,
//         it_3F14_Logic32_Dropped,
//         NULL,
//         NULL,
//         it_3F14_Logic32_DmgReceived,
//         it_3F14_Logic32_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic32_EvtUnk,
//     },
//     {
//         // Spycloak
//         it_803F6370,
//         it_3F14_Logic33_Spawned,
//         NULL,
//         it_3F14_Logic33_PickedUp,
//         it_3F14_Logic33_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic33_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic33_EvtUnk,
//     },
//     {
//         // M Ball
//         it_803F6488,
//         it_3F14_Logic34_Spawned,
//         it_3F14_Logic34_Destroyed,
//         it_3F14_Logic34_PickedUp,
//         it_3F14_Logic34_Dropped,
//         it_3F14_Logic34_Thrown,
//         it_3F14_Logic34_DmgDealt,
//         NULL,
//         it_3F14_Logic34_EnteredAir,
//         it_3F14_Logic34_Reflected,
//         it_3F14_Logic34_Clanked,
//         NULL,
//         it_3F14_Logic34_ShieldBounced,
//         it_3F14_Logic34_HitShield,
//         it_3F14_Logic34_EvtUnk,
//     },
//     {
//         // L Gun Ray
//         it_803F64F8,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic35_DmgDealt,
//         NULL,
//         NULL,
//         it_3F14_Logic35_Reflected,
//         it_3F14_Logic35_Clanked,
//         it_3F14_Logic35_Absorbed,
//         it_3F14_Logic35_ShieldBounced,
//         it_3F14_Logic35_HitShield,
//         it_3F14_Logic35_EvtUnk,
//     },
//     {
//         // Star Rod Star
//         it_803F6530,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic36_DmgDealt,
//         NULL,
//         NULL,
//         it_3F14_Logic36_Reflected,
//         it_3F14_Logic36_Clanked,
//         it_3F14_Logic36_Absorbed,
//         it_3F14_Logic36_ShieldBounced,
//         it_3F14_Logic36_HitShield,
//         it_3F14_Logic36_EvtUnk,
//     },
//     {
//         // LipStick Spore
//         it_803F6680,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic37_DmgDealt,
//         NULL,
//         NULL,
//         it_3F14_Logic37_Reflected,
//         it_3F14_Logic37_Clanked,
//         it_3F14_Logic37_Absorbed,
//         it_3F14_Logic37_ShieldBounced,
//         it_3F14_Logic37_HitShield,
//         it_3F14_Logic37_EvtUnk,
//     },
//     {
//         // S Scope Beam
//         it_803F6568,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic38_DmgDealt,
//         NULL,
//         NULL,
//         it_3F14_Logic38_Reflected,
//         it_3F14_Logic38_Clanked,
//         it_3F14_Logic38_Absorbed,
//         it_3F14_Logic38_ShieldBounced,
//         it_3F14_Logic38_HitShield,
//         it_3F14_Logic38_EvtUnk,
//     },
//     {
//         // L Gun Beam
//         it_803F6630,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic39_DmgDealt,
//         NULL,
//         NULL,
//         it_3F14_Logic39_Reflected,
//         it_3F14_Logic39_Clanked,
//         it_3F14_Logic39_Absorbed,
//         it_3F14_Logic39_ShieldBounced,
//         it_3F14_Logic39_HitShield,
//         it_3F14_Logic39_EvtUnk,
//     },
//     {
//         // Hammer Head
//         it_803F6640,
//         it_3F14_Logic40_Spawned,
//         NULL,
//         it_3F14_Logic40_PickedUp,
//         it_3F14_Logic40_Dropped,
//         it_3F14_Logic40_Thrown,
//         it_3F14_Logic40_DmgDealt,
//         it_3F14_Logic40_DmgReceived,
//         NULL,
//         it_3F14_Logic40_Reflected,
//         it_3F14_Logic40_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic40_HitShield,
//         it_3F14_Logic40_EvtUnk,
//     },
//     {
//         // F Flower Flame
//         it_803F66C8,
//         it_3F14_Logic41_Spawned,
//         NULL,
//         it_3F14_Logic41_PickedUp,
//         it_3F14_Logic41_Dropped,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic41_EnteredAir,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         NULL,
//         it_3F14_Logic41_EvtUnk,
//     },
//     {
//         // EvYoshiEgg
//         it_803F6728,
//         it_3F14_Logic42_Spawned,
//         it_3F14_Logic42_Destroyed,
//         it_3F14_Logic42_PickedUp,
//         it_3F14_Logic42_Dropped,
//         it_3F14_Logic42_Thrown,
//         it_3F14_Logic42_DmgDealt,
//         it_3F14_Logic42_DmgReceived,
//         it_3F14_Logic42_EnteredAir,
//         it_3F14_Logic42_Reflected,
//         it_3F14_Logic42_Clanked,
//         NULL,
//         NULL,
//         it_3F14_Logic42_HitShield,
//         it_3F14_Logic42_EvtUnk,
//     },
// };
