#ifndef _ftmars_h_
#define _ftmars_h_

#include <platform.h>

#include "ft/fighter.h"

#include <baselib/gobj.h>

extern MotionState ftMs_Init_MotionStateTable[];
extern char ftMs_Init_DatFilename[];
extern char ftMs_Init_DataName[];
extern Fighter_CostumeStrings ftMs_Init_CostumeStrings[];
extern char ftMs_Init_AnimDatFilename[];
extern Fighter_DemoStrings ftMs_Init_DemoMotionFilenames;

void ftMs_Init_OnDeath(HSD_GObj* gobj);
void ftMs_Init_OnItemPickup(HSD_GObj* gobj, bool arg1);
void ftMs_Init_OnItemInvisible(HSD_GObj* gobj);
void ftMs_Init_OnItemVisible(HSD_GObj* gobj);
void ftMs_Init_OnItemDrop(HSD_GObj* gobj, bool arg1);
void ftMs_Init_OnLoadForRoy(Fighter* fp);
void ftMs_Init_OnLoad(HSD_GObj* gobj);
void ftMs_Init_LoadSpecialAttrs(HSD_GObj* gobj);
void ftMs_Init_OnKnockbackEnter(HSD_GObj* gobj);
void ftMs_Init_OnKnockbackExit(HSD_GObj* gobj);
void ftMs_SpecialN_801365A8(HSD_GObj* gobj);
void ftMs_SpecialN_8013666C(HSD_GObj* gobj);
void ftMs_SpecialN_80136730(HSD_GObj* gobj);

void ftMs_SpecialN_Enter(HSD_GObj* gobj);
void ftMs_SpecialAirN_Enter(HSD_GObj* gobj);
void ftMs_SpecialNChargeStart_Anim(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeStart_Anim(HSD_GObj* gobj);
void ftMs_SpecialNChargeStart_IASA(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeStart_IASA(HSD_GObj* gobj);
void ftMs_SpecialNChargeStart_Phys(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeStart_Phys(HSD_GObj* gobj);
void ftMs_SpecialNChargeStart_Coll(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeStart_Coll(HSD_GObj* gobj);
void ftMs_SpecialN_80136A1C(HSD_GObj* gobj);
void ftMs_SpecialN_80136A7C(HSD_GObj* gobj);
void ftMs_SpecialNChargeLoop_Anim(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeLoop_Anim(HSD_GObj* gobj);
void ftMs_SpecialNChargeLoop_IASA(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeLoop_IASA(HSD_GObj* gobj);
void ftMs_SpecialNChargeLoop_Phys(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeLoop_Phys(HSD_GObj* gobj);
void ftMs_SpecialNChargeLoop_Coll(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeLoop_Coll(HSD_GObj* gobj);
void ftMs_SpecialN_80136DB4(HSD_GObj* gobj);
void ftMs_SpecialN_80136E14(HSD_GObj* gobj);
void ftMs_SpecialN_80136E74(HSD_GObj* gobj);
void ftMs_SpecialN_80136EAC(HSD_GObj* gobj);
void ftMs_SpecialNChargeEnd_Anim(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeEnd_Anim(HSD_GObj* gobj);
void ftMs_SpecialNChargeEnd_IASA(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeEnd_IASA(HSD_GObj* gobj);
void ftMs_SpecialNChargeEnd_Phys(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeEnd_Phys(HSD_GObj* gobj);
void ftMs_SpecialNChargeEnd_Coll(HSD_GObj* gobj);
void ftMs_SpecialAirNChargeEnd_Coll(HSD_GObj* arg0);
void ftMs_SpecialN_801371FC(HSD_GObj* gobj);
void ftMs_SpecialN_801372A8(HSD_GObj* gobj);
void ftMs_SpecialN_80137354(HSD_GObj* gobj);
void ftMs_SpecialN_801373B8(HSD_GObj* gobj);

void ftMs_SpecialS_Enter(HSD_GObj* gobj);
void ftMs_SpecialAirS_Enter(HSD_GObj* gobj);
void ftMs_SpecialS1_Anim(HSD_GObj* gobj);
void ftMs_SpecialS1_IASA(HSD_GObj* gobj);
void ftMs_SpecialS1_Phys(HSD_GObj* gobj);
void ftMs_SpecialS1_Coll(HSD_GObj* gobj);
void ftMs_SpecialS_801376E8(HSD_GObj* gobj);
void ftMs_SpecialS_80137748(HSD_GObj* gobj);
void ftMs_SpecialS2_Anim(HSD_GObj* gobj);
void ftMs_SpecialS2_IASA(HSD_GObj* gobj);
void ftMs_SpecialS2_Phys(HSD_GObj* gobj);
void ftMs_SpecialS2_Coll(HSD_GObj* gobj);
void ftMs_SpecialS_80137940(HSD_GObj* gobj);
void ftMs_SpecialS_801379D0(HSD_GObj* gobj);
void ftMs_SpecialS_80137A68(HSD_GObj* gobj);
void ftMs_SpecialS_80137A9C(HSD_GObj* gobj);
void ftMs_SpecialS3_Anim(HSD_GObj* gobj);
void ftMs_SpecialS3_IASA(HSD_GObj* gobj);
void ftMs_SpecialS3_Phys(HSD_GObj* gobj);
void ftMs_SpecialS3_Coll(HSD_GObj* gobj);
void ftMs_SpecialS_80137CBC(HSD_GObj* gobj);
void ftMs_SpecialS_80137D60(HSD_GObj* gobj);
void ftMs_SpecialS_80137E0C(HSD_GObj* gobj);
void ftMs_SpecialS4_Anim(HSD_GObj* gobj);
void ftMs_SpecialS4_IASA(HSD_GObj* gobj);
void ftMs_SpecialS4_Phys(HSD_GObj* gobj);
void ftMs_SpecialS4_Coll(HSD_GObj* gobj);
void ftMs_SpecialS_80137FF8(HSD_GObj* gobj);
void ftMs_SpecialS_8013809C(HSD_GObj* gobj);
void ftMs_SpecialS_80138148(HSD_GObj* gobj);

void ftMs_SpecialHi_Enter(HSD_GObj* gobj);
void ftMs_SpecialAirHi_Enter(HSD_GObj* gobj);
void ftMs_SpecialHi_Anim(HSD_GObj* gobj);
void ftMs_SpecialAirHi_Anim(HSD_GObj* gobj);
void ftMs_SpecialHi_IASA(HSD_GObj* gobj);
void ftMs_SpecialAirHi_IASA(HSD_GObj* gobj);
void ftMs_SpecialHi_Phys(HSD_GObj* gobj);
void ftMs_SpecialAirHi_Phys(HSD_GObj* gobj);
void ftMs_SpecialHi_80138884(HSD_GObj* gobj);
void ftMs_SpecialHi_Coll(HSD_GObj* gobj);
void ftMs_SpecialAirHi_Coll(HSD_GObj* gobj);

void ftMs_SpecialLw_Enter(HSD_GObj* gobj);
void ftMs_SpecialAirLw_Enter(HSD_GObj* gobj);
void ftMs_SpecialLw_Anim(HSD_GObj* gobj);
void ftMs_SpecialAirLw_Anim(HSD_GObj* gobj);
void ftMs_SpecialLw_IASA(HSD_GObj* gobj);
void ftMs_SpecialAirLw_IASA(HSD_GObj* gobj);
void ftMs_SpecialLw_Phys(HSD_GObj* gobj);
void ftMs_SpecialAirLw_Phys(HSD_GObj* gobj);
void ftMs_SpecialLw_Coll(HSD_GObj* gobj);
void ftMs_SpecialAirLw_Coll(HSD_GObj* gobj);
void ftMs_SpecialLw_80138D38(HSD_GObj* gobj);
void ftMs_SpecialLw_80138DD0(HSD_GObj* gobj);
void ftMs_SpecialLwHit_Anim(HSD_GObj* gobj);
void ftMs_SpecialAirLwHit_Anim(HSD_GObj* gobj);
void ftMs_SpecialLwHit_IASA(HSD_GObj* gobj);
void ftMs_SpecialAirLwHit_IASA(HSD_GObj* gobj);
void ftMs_SpecialLwHit_Phys(HSD_GObj* gobj);
void ftMs_SpecialAirLwHit_Phys(HSD_GObj* gobj);
void ftMs_SpecialLwHit_Coll(HSD_GObj* gobj);
void ftMs_SpecialAirLwHit_Coll(HSD_GObj* gobj);
void ftMs_SpecialLw_80139080(HSD_GObj* gobj);
void ftMs_SpecialLw_801390E0(HSD_GObj* gobj);
void ftMs_SpecialLw_80139140(HSD_GObj* gobj);
void ftMs_Init_OnLoadForRoy(Fighter*);
void ftMs_Init_LoadSpecialAttrs(HSD_GObj*);

void ftMs_SpecialNChargeStart_Anim(HSD_GObj*);
void ftMs_SpecialNChargeStart_IASA(HSD_GObj*);
void ftMs_SpecialNChargeStart_Phys(HSD_GObj*);
void ftMs_SpecialNChargeStart_Coll(HSD_GObj*);
void ftMs_SpecialNChargeLoop_Anim(HSD_GObj*);
void ftMs_SpecialNChargeLoop_IASA(HSD_GObj*);
void ftMs_SpecialNChargeLoop_Phys(HSD_GObj*);
void ftMs_SpecialNChargeLoop_Coll(HSD_GObj*);
void ftMs_SpecialNChargeEnd_Anim(HSD_GObj*);
void ftMs_SpecialNChargeEnd_IASA(HSD_GObj*);
void ftMs_SpecialNChargeEnd_Phys(HSD_GObj*);
void ftMs_SpecialNChargeEnd_Coll(HSD_GObj*);
void ftMs_SpecialNChargeEnd_Anim(HSD_GObj*);
void ftMs_SpecialNChargeEnd_IASA(HSD_GObj*);
void ftMs_SpecialNChargeEnd_Phys(HSD_GObj*);
void ftMs_SpecialNChargeEnd_Coll(HSD_GObj*);
void ftMs_SpecialAirNChargeStart_Anim(HSD_GObj*);
void ftMs_SpecialAirNChargeStart_IASA(HSD_GObj*);
void ftMs_SpecialAirNChargeStart_Phys(HSD_GObj*);
void ftMs_SpecialAirNChargeStart_Coll(HSD_GObj*);
void ftMs_SpecialAirNChargeLoop_Anim(HSD_GObj*);
void ftMs_SpecialAirNChargeLoop_IASA(HSD_GObj*);
void ftMs_SpecialAirNChargeLoop_Phys(HSD_GObj*);
void ftMs_SpecialAirNChargeLoop_Coll(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_Anim(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_IASA(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_Phys(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_Coll(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_Anim(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_IASA(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_Phys(HSD_GObj*);
void ftMs_SpecialAirNChargeEnd_Coll(HSD_GObj*);
void ftMs_SpecialS1_Anim(HSD_GObj*);
void ftMs_SpecialS1_IASA(HSD_GObj*);
void ftMs_SpecialS1_Phys(HSD_GObj*);
void ftMs_SpecialS1_Coll(HSD_GObj*);
void ftMs_SpecialS2_Anim(HSD_GObj*);
void ftMs_SpecialS2_IASA(HSD_GObj*);
void ftMs_SpecialS2_Phys(HSD_GObj*);
void ftMs_SpecialS2_Coll(HSD_GObj*);
void ftMs_SpecialS2_Anim(HSD_GObj*);
void ftMs_SpecialS2_IASA(HSD_GObj*);
void ftMs_SpecialS2_Phys(HSD_GObj*);
void ftMs_SpecialS2_Coll(HSD_GObj*);
void ftMs_SpecialS3_Anim(HSD_GObj*);
void ftMs_SpecialS3_IASA(HSD_GObj*);
void ftMs_SpecialS3_Phys(HSD_GObj*);
void ftMs_SpecialS3_Coll(HSD_GObj*);
void ftMs_SpecialS3_Anim(HSD_GObj*);
void ftMs_SpecialS3_IASA(HSD_GObj*);
void ftMs_SpecialS3_Phys(HSD_GObj*);
void ftMs_SpecialS3_Coll(HSD_GObj*);
void ftMs_SpecialS3_Anim(HSD_GObj*);
void ftMs_SpecialS3_IASA(HSD_GObj*);
void ftMs_SpecialS3_Phys(HSD_GObj*);
void ftMs_SpecialS3_Coll(HSD_GObj*);
void ftMs_SpecialS4_Anim(HSD_GObj*);
void ftMs_SpecialS4_IASA(HSD_GObj*);
void ftMs_SpecialS4_Phys(HSD_GObj*);
void ftMs_SpecialS4_Coll(HSD_GObj*);
void ftMs_SpecialS4_Anim(HSD_GObj*);
void ftMs_SpecialS4_IASA(HSD_GObj*);
void ftMs_SpecialS4_Phys(HSD_GObj*);
void ftMs_SpecialS4_Coll(HSD_GObj*);
void ftMs_SpecialS4_Anim(HSD_GObj*);
void ftMs_SpecialS4_IASA(HSD_GObj*);
void ftMs_SpecialS4_Phys(HSD_GObj*);
void ftMs_SpecialS4_Coll(HSD_GObj*);
void ftMs_SpecialS1_Anim(HSD_GObj*);
void ftMs_SpecialS1_IASA(HSD_GObj*);
void ftMs_SpecialS1_Phys(HSD_GObj*);
void ftMs_SpecialS1_Coll(HSD_GObj*);
void ftMs_SpecialS2_Anim(HSD_GObj*);
void ftMs_SpecialS2_IASA(HSD_GObj*);
void ftMs_SpecialS2_Phys(HSD_GObj*);
void ftMs_SpecialS2_Coll(HSD_GObj*);
void ftMs_SpecialS2_Anim(HSD_GObj*);
void ftMs_SpecialS2_IASA(HSD_GObj*);
void ftMs_SpecialS2_Phys(HSD_GObj*);
void ftMs_SpecialS2_Coll(HSD_GObj*);
void ftMs_SpecialS3_Anim(HSD_GObj*);
void ftMs_SpecialS3_IASA(HSD_GObj*);
void ftMs_SpecialS3_Phys(HSD_GObj*);
void ftMs_SpecialS3_Coll(HSD_GObj*);
void ftMs_SpecialS3_Anim(HSD_GObj*);
void ftMs_SpecialS3_IASA(HSD_GObj*);
void ftMs_SpecialS3_Phys(HSD_GObj*);
void ftMs_SpecialS3_Coll(HSD_GObj*);
void ftMs_SpecialS3_Anim(HSD_GObj*);
void ftMs_SpecialS3_IASA(HSD_GObj*);
void ftMs_SpecialS3_Phys(HSD_GObj*);
void ftMs_SpecialS3_Coll(HSD_GObj*);
void ftMs_SpecialS4_Anim(HSD_GObj*);
void ftMs_SpecialS4_IASA(HSD_GObj*);
void ftMs_SpecialS4_Phys(HSD_GObj*);
void ftMs_SpecialS4_Coll(HSD_GObj*);
void ftMs_SpecialS4_Anim(HSD_GObj*);
void ftMs_SpecialS4_IASA(HSD_GObj*);
void ftMs_SpecialS4_Phys(HSD_GObj*);
void ftMs_SpecialS4_Coll(HSD_GObj*);
void ftMs_SpecialS4_Anim(HSD_GObj*);
void ftMs_SpecialS4_IASA(HSD_GObj*);
void ftMs_SpecialS4_Phys(HSD_GObj*);
void ftMs_SpecialS4_Coll(HSD_GObj*);
void ftMs_SpecialHi_Anim(HSD_GObj*);
void ftMs_SpecialHi_IASA(HSD_GObj*);
void ftMs_SpecialHi_Phys(HSD_GObj*);
void ftMs_SpecialHi_Coll(HSD_GObj*);
void ftMs_SpecialAirHi_Anim(HSD_GObj*);
void ftMs_SpecialAirHi_IASA(HSD_GObj*);
void ftMs_SpecialAirHi_Phys(HSD_GObj*);
void ftMs_SpecialAirHi_Coll(HSD_GObj*);
void ftMs_SpecialLw_Anim(HSD_GObj*);
void ftMs_SpecialLw_IASA(HSD_GObj*);
void ftMs_SpecialLw_Phys(HSD_GObj*);
void ftMs_SpecialLw_Coll(HSD_GObj*);
void ftMs_SpecialLwHit_Anim(HSD_GObj*);
void ftMs_SpecialLwHit_IASA(HSD_GObj*);
void ftMs_SpecialLwHit_Phys(HSD_GObj*);
void ftMs_SpecialLwHit_Coll(HSD_GObj*);
void ftMs_SpecialAirLw_Anim(HSD_GObj*);
void ftMs_SpecialAirLw_IASA(HSD_GObj*);
void ftMs_SpecialAirLw_Phys(HSD_GObj*);
void ftMs_SpecialAirLw_Coll(HSD_GObj*);
void ftMs_SpecialAirLwHit_Anim(HSD_GObj*);
void ftMs_SpecialAirLwHit_IASA(HSD_GObj*);
void ftMs_SpecialAirLwHit_Phys(HSD_GObj*);
void ftMs_SpecialAirLwHit_Coll(HSD_GObj*);

#endif
