#ifndef MELEE_FT_CHARA_FTCRAZYHAND_FORWARD_H
#define MELEE_FT_CHARA_FTCRAZYHAND_FORWARD_H

#include <melee/ft/kinds/ftMasterHand/forward.h>

typedef enum ftCrazyhand_MotionState {
    ftCh_MS_Count = ftMh_MS_Count - 1,
    ftCh_MS_SelfCount = ftMh_MS_SelfCount - 1,
} ftCrazyhand_MotionState;

typedef enum ftCh_Submotion {
    ftCh_SM_Wait1_0 = ftCo_SM_Count,
    ftCh_SM_Wait2_0,
    ftCh_SM_Slap,
    ftCh_SM_WaitSweep,
    ftCh_SM_SweepLoop,
    ftCh_SM_SweepWait,
    ftCh_SM_Writhe,
    ftCh_SM_SpiderWalkStart,
    ftCh_SM_SpiderWalkLoop,
    ftCh_SM_SpiderWalkEnd,
    ftCh_SM_RockCrushUp,
    ftCh_SM_RockCrushWait,
    ftCh_SM_RockCrushDown,
    ftCh_SM_PaperCrush,
    ftCh_SM_Poke1,
    ftCh_SM_Poke2,
    ftCh_SM_Drill,
    ftCh_SM_FingerBeamStart,
    ftCh_SM_FingerBeamLoop,
    ftCh_SM_FingerBeamEnd,
    ftCh_SM_FingerBomb,
    ftCh_SM_Wait1_1,
    ftCh_SM_Grab,
    ftCh_SM_Cancel,
    ftCh_SM_Squeezing0,
    ftCh_SM_Squeezing1,
    ftCh_SM_Squeeze,
    ftCh_SM_Throw,
    ftCh_SM_Slam,
    ftCh_SM_Fail,
    ftCh_SM_BackDisappear,
    ftCh_SM_BackPunch,
    ftCh_SM_BackCrush,
    ftCh_SM_BackAirplane1,
    ftCh_SM_BackAirplane2,
    ftCh_SM_BackAirplane3,
    ftCh_SM_TagCrush,
    ftCh_SM_TagApplaud,
    ftCh_SM_TagRockPaper,
    ftCh_SM_TagGrab,
    ftCh_SM_TagSqueeze,
    ftCh_SM_TagFail,
    ftCh_SM_TagCancel,
    ftCh_SM_Wait1_2,
    ftCh_SM_Damage,
    ftCh_SM_Damage2,
    ftCh_SM_Entry,
    ftCh_SM_Wait1_3,
    ftCh_SM_Wait2_1,
    ftCh_SM_Count,
    ftCh_SM_SelfCount = ftCh_SM_Count - ftCo_SM_Count,
} ftCh_Submotion;

#endif
