#ifndef GALE01_32AFE4
#define GALE01_32AFE4

#include <placeholder.h>

/* 32AFE4 */ UNK_RET DBGEXIImm(UNK_PARAMS);
/* 32B27C */ UNK_RET DBGReadMailbox(UNK_PARAMS);
/* 32B328 */ UNK_RET DBGRead(UNK_PARAMS);
/* 32B404 */ UNK_RET DBGWrite(UNK_PARAMS);
/* 32B4E0 */ UNK_RET DBGReadStatus(UNK_PARAMS);
/* 32B58C */ UNK_RET MWCallback(UNK_PARAMS);
/* 32B5C8 */ UNK_RET DBGHandler(UNK_PARAMS);
/* 32B608 */ UNK_RET DBInitComm(UNK_PARAMS);
/* 32B680 */ UNK_RET DBInitInterrupts(UNK_PARAMS);
/* 32B6D4 */ UNK_RET DBQueryData(UNK_PARAMS);
/* 32B770 */ UNK_RET DBRead(UNK_PARAMS);
/* 32B7FC */ UNK_RET DBWrite(UNK_PARAMS);
/* 32BA5C */ UNK_RET DBOpen(UNK_PARAMS);
/* 32BA60 */ UNK_RET DBClose(UNK_PARAMS);
/* 32BA64 */ bool Hu_IsStub(void);

#endif
