name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade mypy dataclasses types-dataclasses pycparser coverage black==22.3.0
    - name: Run tests
      run: |
        ./run_tests.py
    - name: Type-check
      run: |
        mypy
    - name: Formatting check
      run: |
        black --check .
