object: orig/GALE01/sys/main.dol
hash: 08e0bf20134dfcb260699671004527b2d6bb1a45
symbols: config/GALE01/symbols.txt
splits: config/GALE01/splits.txt
mw_comment_version: 8
quick_analysis: true

add_relocations:
- source: .text:0x803ab538
  type: rel24
  target: hsd_803B2FA0
- source: .text:0x803ab674
  type: rel24
  target: hsd_803B2FA0
- source: .text:0x803abb98
  type: rel24
  target: hsd_803B2B20
- source: .text:0x803abbd0
  type: rel24
  target: hsd_803B2B20
- source: .text:0x803abc44
  type: rel24
  target: hsd_803B2B20
- source: .text:0x803abc7c
  type: rel24
  target: hsd_803B2B20
- source: .text:0x803aaed0
  type: rel24
  target: memset
- source: .text:0x803aaed4
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803aaf0c
  type: rel24
  target: CARDReadAsync
- source: .text:0x803aaf34
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803aaf58
  type: rel24
  target: CARDClose
- source: .text:0x803aafcc
  type: rel24
  target: CARDFastOpen
- source: .text:0x803aaffc
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803ab020
  type: rel24
  target: memset
- source: .text:0x803ab024
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803ab05c
  type: rel24
  target: CARDReadAsync
- source: .text:0x803ab084
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ab0a8
  type: rel24
  target: CARDClose
- source: .text:0x803ab15c
  type: rel24
  target: CARDFastOpen
- source: .text:0x803ab18c
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803ab194
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803ab1c8
  type: rel24
  target: CARDReadAsync
- source: .text:0x803ab1f0
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ab214
  type: rel24
  target: CARDClose
- source: .text:0x803ab288
  type: rel24
  target: CARDFastOpen
- source: .text:0x803ab2b8
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803ab2c0
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803ab2f4
  type: rel24
  target: CARDReadAsync
- source: .text:0x803ab31c
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ab340
  type: rel24
  target: CARDClose
- source: .text:0x803ab3a0
  type: rel24
  target: memset
- source: .text:0x803ab3f8
  type: rel24
  target: CARDFastOpen
- source: .text:0x803ab480
  type: rel24
  target: memcpy
- source: .text:0x803ab4b0
  type: rel24
  target: memset
- source: .text:0x803ab4c8
  type: rel24
  target: memset
- source: .text:0x803ab544
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803ab54c
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803ab580
  type: rel24
  target: CARDWriteAsync
- source: .text:0x803ab5a8
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ab5cc
  type: rel24
  target: CARDClose
- source: .text:0x803ab640
  type: rel24
  target: CARDFastOpen
- source: .text:0x803ab680
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803ab688
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803ab6bc
  type: rel24
  target: CARDWriteAsync
- source: .text:0x803ab6e4
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ab708
  type: rel24
  target: CARDClose
- source: .text:0x803ab750
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803ab784
  type: rel24
  target: CARDCreateAsync
- source: .text:0x803ab7ac
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ab7f8
  type: rel24
  target: CARDGetStatus
- source: .text:0x803ab9d8
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803aba04
  type: rel24
  target: CARDSetStatusAsync
- source: .text:0x803aba2c
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803abaa0
  type: rel24
  target: CARDFastOpen
- source: .text:0x803abb14
  type: rel24
  target: memcpy
- source: .text:0x803abb38
  type: rel24
  target: memcpy
- source: .text:0x803abb50
  type: rel24
  target: memset
- source: .text:0x803abb78
  type: rel24
  target: memcpy
- source: .text:0x803abbb0
  type: rel24
  target: memcpy
- source: .text:0x803abbec
  type: rel24
  target: memcpy
- source: .text:0x803abc24
  type: rel24
  target: memcpy
- source: .text:0x803abc5c
  type: rel24
  target: memcpy
- source: .text:0x803abc94
  type: rel24
  target: memcpy
- source: .text:0x803abc98
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803abcd0
  type: rel24
  target: CARDWriteAsync
- source: .text:0x803abcf8
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803abd18
  type: rel24
  target: CARDClose
- source: .text:0x803abd8c
  type: rel24
  target: CARDGetStatus
- source: .text:0x803abf70
  type: rel24
  target: CARDFastOpen
- source: .text:0x803abf98
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803abfcc
  type: rel24
  target: CARDReadAsync
- source: .text:0x803abff4
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803ac018
  type: rel24
  target: CARDClose
- source: .text:0x803aad84
  type: rel24
  target: CARDFastOpen
- source: .text:0x803aadb4
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803aadbc
  type: rel24
  target: OSDisableInterrupts
- source: .text:0x803aadf0
  type: rel24
  target: CARDReadAsync
- source: .text:0x803aae18
  type: rel24
  target: OSRestoreInterrupts
- source: .text:0x803aae3c
  type: rel24
  target: CARDClose
- source: .text:0x803aae7c
  type: rel24
  target: CARDFastOpen
- source: .text:0x803aaeac
  type: rel24
  target: CARDGetXferredBytes
- source: .text:0x803aacf4
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aacfc
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aad28
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aad5c
  type: sda21
  target: hsd_804D7980
- source: .text:0x803aada4
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aae14
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aae28
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aae2c
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aae9c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aaf30
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aaf44
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aaf48
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aafa4
  type: sda21
  target: hsd_804D7980
- source: .text:0x803aafec
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab080
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab094
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab098
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab0d8
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab0f8
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab104
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab128
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab17c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab1ec
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab200
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab204
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab254
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab2a8
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab318
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab32c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab330
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab380
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab3c4
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab418
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab5a4
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab5b8
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab5bc
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab60c
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab660
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab6e0
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab6f4
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab6f8
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab748
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab7a8
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab7bc
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab7c0
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ab818
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aba24
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aba3c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aba40
  type: sda21
  target: hsd_804D799C
- source: .text:0x803aba6c
  type: sda21
  target: hsd_804D7980
- source: .text:0x803abac0
  type: sda21
  target: hsd_804D7988
- source: .text:0x803abcf4
  type: sda21
  target: hsd_804D799C
- source: .text:0x803abd08
  type: sda21
  target: hsd_804D799C
- source: .text:0x803abd30
  type: sda21
  target: hsd_804D7988
- source: .text:0x803abd5c
  type: sda21
  target: hsd_804D7980
- source: .text:0x803abdb0
  type: sda21
  target: hsd_804D7988
- source: .text:0x803abdb4
  type: sda21
  target: hsd_804D799C
- source: .text:0x803abf1c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803abf20
  type: sda21
  target: hsd_804D799C
- source: .text:0x803abf48
  type: sda21
  target: hsd_804D7980
- source: .text:0x803abf90
  type: sda21
  target: hsd_804D7988
- source: .text:0x803abff0
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ac004
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ac008
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ac04c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ac050
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ac078
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ac0a8
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ac0ac
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ac0d4
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ac0d8
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ac108
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ac10c
  type: sda21
  target: hsd_804D799C
- source: .text:0x803ac138
  type: sda21
  target: hsd_804D7980
- source: .text:0x803aacd4
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aace4
  type: sda21
  target: hsd_804D7990
- source: .text:0x803aacec
  type: sda21
  target: hsd_804D7994
- source: .text:0x803aad30
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aad44
  type: sda21
  target: hsd_804D7980
- source: .text:0x803aaf78
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aaf8c
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab0c8
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab0e0
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab110
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab130
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab23c
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab25c
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab368
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab388
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab3ac
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab3cc
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab5f4
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab614
  type: sda21
  target: hsd_804D7988
- source: .text:0x803ab730
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ab7cc
  type: sda21
  target: hsd_804D7988
- source: .text:0x803aba54
  type: sda21
  target: hsd_804D7980
- source: .text:0x803aba74
  type: sda21
  target: hsd_804D7988
- source: .text:0x803abd44
  type: sda21
  target: hsd_804D7980
- source: .text:0x803abf30
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ac060
  type: sda21
  target: hsd_804D7980
- source: .text:0x803ac120
  type: sda21
  target: hsd_804D7980
- source: .text:0x803aadb8
  type: sda21
  target: hsd_804D7988
  addend: 4
- source: .text:0x803AAEB0
  type: sda21
  target: hsd_804D7988
  addend: 4
- source: .text:0x803AB000
  type: sda21
  target: hsd_804D7988
  addend: 4
- source: .text:0x803AB190
  type: sda21
  target: hsd_804D7988
  addend: 4
- source: .text:0x803AB2BC
  type: sda21
  target: hsd_804D7988
  addend: 4
- source: .text:0x803AB548
  type: sda21
  target: hsd_804D7988
  addend: 4
- source: .text:0x803AB684
  type: sda21
  target: hsd_804D7988
  addend: 4
