set colorcolumn=80
highlight colorcolumn ctermbg=darkgray

augroup Melee
  au! BufRead,BufNewFile *.h,*.c setfiletype c
  au! BufRead,BufNewFile *.dox setfiletype doxygen
  au! FileType c set syntax=c.doxygen
augroup END

command! -nargs=1 FpGrep vimgrep /\<fp+\<0*<args>\>\>/ src/melee/ft/**/*.h
command! -nargs=1 OffsetGrep vimgrep /+\<0*<args>\>/ src/**/*.h
command! -nargs=1 LblGrep vimgrep /^<args>:$/ expected/dump/**/*.s

let &path.="src,src/melee,src/melee/ft/chara,src/MSL,src/sysdolphin,src/dolphin,"
let g:c_syntax_for_h = 1
