#ifndef MELEE_FT_CHARA_FTKIRBY_FORWARD_H
#define MELEE_FT_CHARA_FTKIRBY_FORWARD_H

#include <platform.h>
#include "ftCommon/forward.h"

typedef enum ftKirby_MotionState {
    ftKb_MS_Jump2 = ftCo_MS_Count,
    ftKb_MS_Jump3,
    ftKb_MS_Jump4,
    ftKb_MS_Jump5,
    ftKb_MS_Jump6,

    ftKb_MS_Jump2_WithHat,
    ftKb_MS_Jump3_WithHat,
    ftKb_MS_Jump4_WithHat,
    ftKb_MS_Jump5_WithHat,
    ftKb_MS_Jump6_WithHat,

    ftKb_MS_AttackDash,
    ftKb_MS_AttackDash_Air,

    ftKb_MS_SpecialN_Start,
    ftKb_MS_SpecialN_Loop,
    ftKb_MS_SpecialN_End,
    ftKb_MS_SpecialN_Capture,
    ftKb_MS_Unk_357,
    ftKb_MS_SpecialN_Captured,
    ftKb_MS_SpecialN_CaptureWait,
    ftKb_MS_SpecialN_CaptureWalkSlow,
    ftKb_MS_SpecialN_CaptureWalkMiddle,
    ftKb_MS_SpecialN_CaptureWalkFast,
    ftKb_MS_SpecialN_CaptureTurn,
    ftKb_MS_SpecialN_CaptureJumpSquat,
    ftKb_MS_SpecialN_CaptureJump,
    ftKb_MS_SpecialN_CaptureLanding,
    ftKb_MS_SpecialN_Digest,
    ftKb_MS_Unk_368,
    ftKb_MS_SpecialN_Spit,
    ftKb_MS_Unk_370,
    ftKb_MS_SpecialAirN_Start,
    ftKb_MS_SpecialAirN_Loop,
    ftKb_MS_SpecialAirN_End,
    ftKb_MS_SpecialAirN_Capture,
    ftKb_MS_Unk_375,
    ftKb_MS_SpecialAirN_Captured,
    ftKb_MS_SpecialAirN_CaptureWait,
    ftKb_MS_SpecialAirN_Digest,
    ftKb_MS_Unk_379,
    ftKb_MS_SpecialAirN_Spit,
    ftKb_MS_Unk_381,
    ftKb_MS_SpecialAirN_CaptureTurn,

    ftKb_MS_SpecialS,
    ftKb_MS_SpecialAirS,

    ftKb_MS_SpecialHi_Start,
    ftKb_MS_Unk_386,
    ftKb_MS_Unk_387,
    ftKb_MS_SpecialHi_End,

    /// @todo Names.
    ftKb_MS_SpecialAirHi_Start,
    ftKb_MS_SpecialAirHi_Apex,
    ftKb_MS_SpecialHi_SwordDescent,
    ftKb_MS_SpecialAirHi_End,

    ftKb_MS_SpecialLw_Start,
    ftKb_MS_SpecialLw,
    ftKb_MS_SpecialLw_End,
    ftKb_MS_SpecialAirLw_Start,
    ftKb_MS_SpecialAirLw,
    ftKb_MS_SpecialAirLw_End,

    ftKb_MS_SpecialN_Mr,
    ftKb_MS_SpecialAirN_Mr,

    ftKb_MS_SpecialN_Lk_Charge,
    ftKb_MS_SpecialN_Lk_FullyCharged,
    ftKb_MS_SpecialN_Lk_Fire,
    ftKb_MS_SpecialAirN_Lk_Charge,
    ftKb_MS_SpecialAirN_Lk_FullyCharged,
    ftKb_MS_SpecialAirN_Lk_Fire,

    ftKb_MS_SpecialN_Ss_Start,
    ftKb_MS_SpecialN_Ss_Loop,
    ftKb_MS_SpecialN_Ss_End,
    ftKb_MS_SpecialN_Ss_Fire,
    ftKb_MS_SpecialAirN_Ss_Start,
    ftKb_MS_SpecialAirN_Ss_Fire,

    ftKb_MS_SpecialN_Ys,
    ftKb_MS_SpecialN_Ys_CaptureStart,
    ftKb_MS_Unk_415,
    ftKb_MS_SpecialN_Ys_Capture,
    ftKb_MS_Unk_417,
    ftKb_MS_SpecialAirN_Ys,
    ftKb_MS_SpecialAirN_Ys_CaptureStart,
    ftKb_MS_Unk_420,
    ftKb_MS_SpecialAirN_Ys_Capture,
    ftKb_MS_Unk_422,

    ftKb_MS_SpecialN_Fx_Start,
    ftKb_MS_SpecialN_Fx_Loop,
    ftKb_MS_SpecialN_Fx_End,
    ftKb_MS_SpecialAirN_Fx_Start,
    ftKb_MS_SpecialAirN_Fx_Loop,
    ftKb_MS_SpecialAirN_Fx_End,

    ftKb_MS_SpecialN_Pk,
    ftKb_MS_SpecialAirN_Pk,

    ftKb_MS_SpecialN_Lg,
    ftKb_MS_SpecialAirN_Lg,

    ftKb_MS_SpecialN_Ca,
    ftKb_MS_SpecialAirN_Ca,

    ftKb_MS_SpecialN_Ns_Start,
    ftKb_MS_SpecialN_Ns_Charge,
    ftKb_MS_SpecialN_Ns_Explode,
    ftKb_MS_SpecialN_Ns_End,
    ftKb_MS_SpecialAirN_Ns_Start,
    ftKb_MS_SpecialAirN_Ns_Charge,
    ftKb_MS_SpecialAirN_Ns_Explode,
    ftKb_MS_SpecialAirN_Ns_End,

    ftKb_MS_SpecialN_Kp_Start,
    ftKb_MS_SpecialN_Kp_Loop,
    ftKb_MS_SpecialN_Kp_End,
    ftKb_MS_SpecialAirN_Kp_Start,
    ftKb_MS_SpecialAirN_Kp_Loop,
    ftKb_MS_SpecialAirN_Kp_End,

    ftKb_MS_SpecialN_Pe,
    ftKb_MS_SpecialN_Pe_Attack,
    ftKb_MS_SpecialAirN_Pe,
    ftKb_MS_SpecialAirN_Pe_Attack,

    ftKb_MS_SpecialN_Ic,
    ftKb_MS_SpecialAirN_Ic,

    ftKb_MS_SpecialN_Dk_ChargeStart,
    ftKb_MS_SpecialN_Dk_ChargeLoop,
    ftKb_MS_SpecialN_Dk_ChargeStop,
    ftKb_MS_SpecialN_Dk_EarlyPunch,
    ftKb_MS_SpecialN_Dk_FullChargePunch,
    ftKb_MS_SpecialAirN_Dk_ChargeStart,
    ftKb_MS_SpecialAirN_Dk_ChargeLoop,
    ftKb_MS_SpecialAirN_Dk_ChargeStop,
    ftKb_MS_SpecialAirN_Dk_EarlyPunch,
    ftKb_MS_SpecialAirN_Dk_FullChargePunch,

    ftKb_MS_SpecialN_Zd,
    ftKb_MS_SpecialAirN_Zd,

    ftKb_MS_SpecialN_Sk_StartCharge,
    ftKb_MS_SpecialN_Sk_ChargeLoop,
    ftKb_MS_SpecialN_Sk_EndCharge,
    ftKb_MS_SpecialN_Sk_Fire,
    ftKb_MS_SpecialAirN_Sk_StartCharge,
    ftKb_MS_SpecialAirN_Sk_ChargeLoop,
    ftKb_MS_SpecialAirN_Sk_EndCharge,
    ftKb_MS_SpecialAirN_Sk_Fire,

    ftKb_MS_SpecialN_Pr_ChargeStartR,
    ftKb_MS_SpecialN_Pr_ChargeStartL,
    ftKb_MS_SpecialN_Pr_ChargeLoop,
    ftKb_MS_SpecialN_Pr_FullyCharged,
    ftKb_MS_SpecialN_Pr_ChargeRelease,
    ftKb_MS_SpecialN_Pr_TurnStart,
    ftKb_MS_SpecialN_Pr_EndR,
    ftKb_MS_SpecialN_Pr_EndL,
    ftKb_MS_SpecialAirN_Pr_ChargeStartR,
    ftKb_MS_SpecialAirN_Pr_ChargeStartL,
    ftKb_MS_SpecialAirN_Pr_ChargeLoop,
    ftKb_MS_SpecialAirN_Pr_FullyCharged,
    ftKb_MS_SpecialAirN_Pr_ChargeRelease,
    ftKb_MS_Unk_488,
    ftKb_MS_SpecialAirN_Pr_EndR,
    ftKb_MS_SpecialAirN_Pr_EndL,
    ftKb_MS_SpecialN_Pr_Hit,

    ftKb_MS_SpecialN_Ms_StartCharge,
    ftKb_MS_SpecialN_Ms_ChargeLoop,
    ftKb_MS_SpecialN_Ms_EarlyRelease,
    ftKb_MS_SpecialN_Ms_FullyCharged,
    ftKb_MS_SpecialAirN_Ms_StartCharge,
    ftKb_MS_SpecialAirN_Ms_ChargeLoop,
    ftKb_MS_SpecialAirN_Ms_EarlyRelease,
    ftKb_MS_SpecialAirN_Ms_FullyCharged,

    ftKb_MS_SpecialN_Mt_StartCharge,
    ftKb_MS_SpecialN_Mt_ChargeLoop,
    ftKb_MS_SpecialN_Mt_FullyCharged,
    ftKb_MS_SpecialN_Mt_EndCharge,
    ftKb_MS_SpecialN_Mt_Fire,
    ftKb_MS_SpecialAirN_Mt_StartCharge,
    ftKb_MS_SpecialAirN_Mt_ChargeLoop,
    ftKb_MS_SpecialAirN_Mt_FullyCharged,
    ftKb_MS_SpecialAirN_Mt_EndCharge,
    ftKb_MS_SpecialAirN_Mt_Fire,

    ftKb_MS_SpecialN_Gw,
    ftKb_MS_SpecialAirN_Gw,

    ftKb_MS_SpecialN_Dr,
    ftKb_MS_SpecialAirN_Dr,

    ftKb_MS_SpecialN_Cl_Charge,
    ftKb_MS_SpecialN_Cl_FullyCharged,
    ftKb_MS_SpecialN_Cl_Fire,
    ftKb_MS_SpecialAirN_Cl_Charge,
    ftKb_MS_SpecialAirN_Cl_FullyCharged,
    ftKb_MS_SpecialAirN_Cl_Fire,

    ftKb_MS_SpecialN_Fc_Start,
    ftKb_MS_SpecialN_Fc_Loop,
    ftKb_MS_SpecialN_Fc_End,
    ftKb_MS_SpecialAirN_Fc_Start,
    ftKb_MS_SpecialAirN_Fc_Loop,
    ftKb_MS_SpecialAirN_Fc_End,

    ftKb_MS_SpecialN_Pc,
    ftKb_MS_SpecialAirN_Pc,

    ftKb_MS_SpecialN_Gn,
    ftKb_MS_SpecialAirN_Gn,

    ftKb_MS_SpecialN_Fe_StartCharge,
    ftKb_MS_SpecialN_Fe_ChargeLoop,
    ftKb_MS_SpecialN_Fe_EarlyRelease,
    ftKb_MS_SpecialN_Fe_FullyCharged,
    ftKb_MS_SpecialAirN_Fe_StartCharge,
    ftKb_MS_SpecialAirN_Fe_ChargeLoop,
    ftKb_MS_SpecialAirN_Fe_EarlyRelease,
    ftKb_MS_SpecialAirN_Fe_FullyCharged,

    ftKb_MS_SpecialN_Gk_Start,
    ftKb_MS_SpecialN_Gk_Loop,
    ftKb_MS_SpecialN_Gk_End,
    ftKb_MS_SpecialAirN_Gk_Start,
    ftKb_MS_SpecialAirN_Gk_Loop,
    ftKb_MS_SpecialAirN_Gk_End,
} ftKirby_MotionState;

#endif
