name: Check code style

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Check source for common style issues
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook: ['clang-format', 'style-check']
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: ${{ matrix.hook }} --all-files
