name: Check code style

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Check source for common style issues
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook:
          - clang-format
          - clang-check
          - editorconfig-checker
          - style-check
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Determine reference commit
      id: ref
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "from=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
        else
          echo "from=${{ github.event.before }}" >> $GITHUB_OUTPUT
        fi

    - uses: actions/setup-python@v5
      if: matrix.hook == 'editorconfig-checker'
      with:
        python-version: "3.12"

    # TODO: Install on build image
    - name: Install clang-tools
      if: matrix.hook == 'clang-check'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tools

    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: ${{ matrix.hook }} --from-ref ${{ steps.ref.outputs.from }} --to-ref HEAD
