name: Publish

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: ribbanya/melee:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout Doxygen Awesome repo
        uses: actions/checkout@v3
        with:
          repository: jothepro/doxygen-awesome-css
          path: tools/doxygen-awesome-css
      - name: Generate Doxygen documentation
        run: |
          mkdir -p build/doxygen
          doxygen Doxyfile
          touch build/doxygen/html/.nojekyll
        shell: bash
      - name: Generate context
        run: |
          . /usr/local/share/venv/bin/activate
          pip3 install -r requirements.txt --no-cache-dir
          python3 tools/m2ctx/m2ctx.py -pqr
          cp build/ctx.html build/doxygen/html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.5
        with:
          path: build/doxygen/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
